### ISSUE TITLE
Unsupported method

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1047]
I came across a method with the following form (I ripped out all "meat", replacing it with nop's, but the structure is intact)
```
.class public auto ansi beforefieldinit ProblemClass
{
	.method private hidebysig instance void ProblemMethod() cil managed 
	{
		.maxstack 4

		// loop start
		IL_0000: nop
		blt IL_0047

		nop
		brfalse IL_0037

		nop

		IL_0037: nop
		br L_exit

		IL_0047: nop
		brtrue IL_0083

		nop
		br IL_0000

		IL_0083: nop
		ble.un IL_00fa

		nop
		brfalse IL_00db

		nop
		brfalse IL_00fa

		IL_00db: nop

		IL_00fa: br L_exit

		br IL_0000
		// end loop

		L_exit: ret
	}
}
```
When trying to decompile to C#, `StatementBuilder.ConvertLoop` throws `NotSupportedException` - `container.Kind` is `Normal`.

**Comment by siegfriedpammer** [comment]
I think it will be hard to debug this with just the control flow instructions and nops... Could you provide a more complete sample? Thank you very much!

**Comment by tamlin-mike** [comment]
The code is verified to display the bug. Feed it to ilasm and see it in action.

While I haven't stepped through it in the debugger (yet), a suspicion is the looping back to IL_0000 (first time I ever seen such code I believe). It seems loop detection is failing, so I believe the control-flow should be all that is required.

Should it turn out it's not enough, I can provide the complete method IL.

**Comment by tamlin-mike** [comment]
Seems I was on the right track. The following patch fixes it, but it feels more like a hack than a complete solution. Still, it displays the problem and how to solve it.
```
index f9cdec17..db8b82f4 100644
--- a/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
+++ b/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs
@@ -749,6 +749,7 @@ Statement ConvertLoop(BlockContainer container)
                        BlockStatement blockStatement;
                        continueCount = 0;
                        breakTarget = container;
+                       again:
                        switch (container.Kind) {
                                case ContainerKind.Loop:
                                        continueTarget = container.EntryPoint;
@@ -828,6 +829,14 @@ Statement ConvertLoop(BlockContainer container)
                                                blockStatement.Add(new LabelStatement { Label = continueTarget.Label });                                        return forStmt;
                        }
+                       if (container.Children.Count > 0 &&
+                               container.Children[0].ILRange.Start == container.ILRange.Start &&
+                               container.Children[0].Children.Count > 0 &&
+                               container.Children[0].Children[0].ILRange.Start == container.ILRange.Start)
+                       {
+                               container = (BlockContainer)container.Children[0].Children[0];
+                               goto again;
+                       }
                        throw new NotSupportedException();
                }
```

**Comment by siegfriedpammer** [comment]
Btw... I didn't know that ilasm would accept this kind of IL skeleton, thanks for the hint! :)

I think the problem lies somewhere else:

```
ILFunction ProblemMethod {
	
	BlockContainer {
		Block IL_0000 (incoming: 2) {
			BlockContainer (do-while) {
				Block IL_0000 (incoming: 2) {
					if (comp(invalid.expr("Stack underflow") >= invalid.expr("Stack underflow"))) Block IL_0006 {
						if (logic.not(conv unknown->i4 <invalid>(invalid.expr("Stack underflow")))) leave IL_0000 (nop)
						leave IL_0000 (nop)
					}
					br IL_0014
				}

				Block IL_0014 (incoming: 1) {
					if (logic.not(conv unknown->i4 <invalid>(invalid.expr("Stack underflow")))) br IL_0000 else leave IL_0000 (nop)
				}

			}
			if (logic.and(comp(invalid.expr("Stack underflow") > invalid.expr("Stack underflow")), logic.and(conv unknown->i4 <invalid>(invalid.expr("Stack underflow")), logic.not(conv unknown->i4 <invalid>(invalid.expr("Stack underflow")))))) leave IL_0000 (nop)
			leave IL_0000 (nop)
		}

		Block IL_0037 (incoming: 0) {
			br IL_0000
		}

	}
}

```

The inner block container is correctly identified as do-while loop, whereas the outer block container cannot be a loop at all, because it is the root block container for the ILFunction and `container.Kind == Normal` is expected.

The problem is that the unreachable (!) block `IL_0037` contains a br to IL_0000, and because of that the entry-point block has 2 incoming edges (one because it's the entry-point plus the additional br in the other block) which makes the decompiler think that the block container is a loop.

Normally unreachable blocks should be removed at some point in the pipeline, i.e., `BlockContainer.SortBlocks(deleteUnreachableBlocks: true)` should be called at some point after another transform has run. In this case, no other higher level pattern (switch on nullables/strings, catch when, yield or async) is present and the block never gets deleted.

As I see it, we have two options:
* Explicitly remove unreachable blocks in the ILReader (set deleteUnreachableBlocks: true on line 437):
https://github.com/icsharpcode/ILSpy/blob/4c73a771a1ad884abb40929496622853a33c6c59/ICSharpCode.Decompiler/IL/ILReader.cs#L422-L441
But this is a rather "destructive" approach, as it potentially kills off a lot of code, which might be of interest to the developer inspecting the code. Ideally, we should only delete unreachable blocks in containers that have been modified by a transform. @dgrunwald Please comment on this approach.
* Alter StatementBuilder on line 726 to check `container.Kind != ContainerKind.Normal` as well.
https://github.com/icsharpcode/ILSpy/blob/4c73a771a1ad884abb40929496622853a33c6c59/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs#L724-L736
This second approach is the one I will implement, because it seems to be the easiest fix for this problem. Actually, I should have added this check right from the start, when refactoring a large part of the loop detection. I am sorry!

Thank you for reporting and analyzing this!

**Comment by siegfriedpammer** [comment]
@tamlin-mike Can you please verify that the test case in Issue1047.cs and Issue1047.il (in \ICSharpCode.Decompiler.Tests\TestCases\ILPretty) make sense and the produced C# is correct? I don't have the original binary, so it's a lot harder for me to see.

**Comment by tamlin-mike** [comment]
I reduced the repro to the following. Verified to fail without the extra check you added, and works with it. Gets rid of all decompilation warnings.
```
.class public auto ansi beforefieldinit ProblemClass
{
	.field private static bool dummy;
	.method private hidebysig instance void ProblemMethod() cil managed 
	{
		IL_0000: ldfld bool ProblemClass::dummy;
		brfalse L_tgt1
		br L_exit
		L_tgt1: br IL_0000
		br IL_0000
		L_exit: ret
	}
}
```
