### ISSUE TITLE
Don't open links to IL instructions

### ISSUE THREAD

**Issue by wmjordan** [icsharpcode/ILSpy#1064]
I found that the recent version of ILSpy had an annoyance.
In the IL or IL with C# view, if we click at the space behind any IL instructions, it opens the web browser and jump to the description page of the IL instruction.
We did not click **ON** the IL instructions, we just clicked an empty area behind them (the yellow part marked in the screenshot below) and the browser jumped in front of the window.
There's no way to suppress this behavior.

![shot](https://user-images.githubusercontent.com/12182730/36019456-5c320588-0dba-11e8-9d24-55a7040126cb.png)

**Comment by Radon222** [comment]
Fixed in #1066

**Comment by siegfriedpammer** [comment]
This is a problem I discovered and tried to fix a few months ago, but I could not come up with a satisfying solution. The problem here is:

https://github.com/icsharpcode/ILSpy/blob/b2d30dc6153aebd6bd1be4e011a4c1da95cb0f30/ILSpy/TextView/DecompilerTextView.cs#L747-L756

Line 751 returns a TextViewPosition with Column == VisualColumn and IsAtEndOfLine == false, which could be seen as a bug, but the line causing the bug is actually 755. `FindSegmentsContaining` returns all segments matching `start <= offset <= end`, `offset` is the offset directly at the end of the line, which then returns the segment of the `ldarg.0` reference.

Possible solutions:
1) Fix `GetPositionFromMousePosition` to return an "invalid" position in cases where the mouse position is after the end of the line.
2) Change semantics of `FindSegmentsContaining` to exclude the offset after the end of the segment.
3) The easiest fix would be to add a space before the EOL when printing instructions without arguments.

@dgrunwald which one is the best solution?

**Comment by dgrunwald** [comment]
I think 1 is a good solution. If the returned position is at the end of line, just compare the mouse position with the line's width. This way we don't follow links/show a context menu after the end of the line.

Note: don't be confused by `IsAtEndOfLine == false` -- that property only exists to disambiguate a special case in word wrapping.

**Comment by wmjordan** [comment]
I downloaded the latest build. The problem was solved.
