### ISSUE TITLE
How do you actually download the latest version?

### ISSUE THREAD

**Issue by spongyryno** [icsharpcode/ILSpy#1067]
If I try to download PREVIOUS version (3.0.1), there's a zip file that actually includes "ILSpy.exe".

However, with the latest (3.0.2), it says "Binaries are on NuGet". So, when I go to NuGet.org and search for ILSpy, it directs me to "ICSharpCode.Decompiler", and when I download the NuGet package, it includes a lot of "stuff", but no "ILSpy.exe". So... how do I actually get the latest binaries (that include the actual application)?

**Comment by christophwille** [comment]
https://github.com/icsharpcode/ILSpy/releases the binaries in this case are the actual nupkg files (the Nuget package). If you look through the Assets lists, it is not included for download - that's why there is the reference to NuGet. 

The WPF UI was not released for 3.0.2 simply because none of the changes were relevant.
