### ISSUE TITLE
There are ref variables even if the languge is C# 4.0 / VS 2010

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1082]
```
private void startMove()
{
	bool flag = Random.Range(0, 2) == 0 && true;
	for (int i = 0; i < this.arrPath.Length; i++)
	{
		this.arrPath[i] = base.transform.position + base.transform.forward * (float)i * 60f;
		Vector3 onUnitSphere;
		float num;
		do
		{
			onUnitSphere = Random.onUnitSphere;
			num = Vector3.Dot(base.transform.forward, onUnitSphere);
		}
		while (!(num > 0f));
		ref Vector3 val = ref this.arrPath[i];
		val += onUnitSphere * this.arrDist[i];
		if (this.arrPath[i].y > this.heightLimit)
		{
			this.arrPath[i].y = this.heightLimit;
		}
	}
	iTween.MoveTo(base.gameObject, iTween.Hash("path", this.arrPath, "time", this.fMoveTime, "easetype", iTween.EaseType.linear, "oncomplete", "DestroyFishPool", "oncompletetarget", base.gameObject));
}
```

**Comment by siegfriedpammer** [comment]
This is intentional. Some features cannot be disabled in any language version. Other examples include: Generics when decompiling to C# 1.0. They cannot be removed without changing the semantics. The language selection feature is mainly intended to reduce the number of options in the options dialog. It does not make sense to add a checkbox for each single feature, thus we decided to model the UI differently.

**Comment by CreateAndInject** [comment]
but the "ref" is unnecessary.
Reflector and dnSpy can deompile it without "ref":
dnSpy:
```
	private void startMove()
	{
		int num = (UnityEngine.Random.Range(0, 2) != 0) ? 0 : 1;
		for (int i = 0; i < this.arrPath.Length; i++)
		{
			this.arrPath[i] = base.transform.position + base.transform.forward * (float)i * 60f;
			Vector3 onUnitSphere;
			float num2;
			do
			{
				onUnitSphere = UnityEngine.Random.onUnitSphere;
				num2 = Vector3.Dot(base.transform.forward, onUnitSphere);
			}
			while (num2 <= 0f);
			this.arrPath[i] += onUnitSphere * this.arrDist[i];
			if (this.arrPath[i].y > this.heightLimit)
			{
				this.arrPath[i].y = this.heightLimit;
			}
		}
		iTween.MoveTo(base.gameObject, iTween.Hash(new object[]
		{
			"path",
			this.arrPath,
			"time",
			this.fMoveTime,
			"easetype",
			iTween.EaseType.linear,
			"oncomplete",
			"DestroyFishPool",
			"oncompletetarget",
			base.gameObject
		}));
	}
```

Reflector:
```
private void startMove()
{
    bool flag = Random.Range(0, 2) == 0;
    for (int i = 0; i < this.arrPath.Length; i++)
    {
        Vector3 onUnitSphere;
        this.arrPath[i] = base.transform.position + ((base.transform.forward * i) * 60f);
        do
        {
            onUnitSphere = Random.onUnitSphere;
        }
        while (Vector3.Dot(base.transform.forward, onUnitSphere) <= 0f);
        this.arrPath[i] += onUnitSphere * this.arrDist[i];
        if (this.arrPath[i].y > this.heightLimit)
        {
            this.arrPath[i].y = this.heightLimit;
        }
    }
    object[] args = new object[] { "path", this.arrPath, "time", this.fMoveTime, "easetype", iTween.EaseType.linear, "oncomplete", "DestroyFishPool", "oncompletetarget", base.gameObject };
    iTween.MoveTo(base.gameObject, iTween.Hash(args));
}
```

**Comment by siegfriedpammer** [comment]
ad dnSpy: dnSpy uses an old version of ILSpy that did not support ref at all and did not correctly preserve semantics of value type calls in compound assignments. ILSpy 3.x does this now, but has not yet special handling for older language versions that do not support ref.

ad Reflector: As noted above, ILSpy has no special handling that simplifies ref expressions in compound assignments with value types. Reflector does handle it correctly. As always: contributions are very welcome! If you have questions, you can always ask either via gitter or in an issue.

**Comment by dgrunwald** [comment]
The underlying cause here is that we don't support compound assignments with user-defined operators.

Full reproducer:
```
	struct Vector3
	{
		public static Vector3 operator +(Vector3 a, Vector3 b) { return default(Vector3); }

		static void Issue1082(Vector3[] vectors, int i, Vector3 offset)
		{
			vectors[i] += offset;
		}
	}
```

The method initially gets decompiled to:
```
     ref Vector3 val = ref vectors[i];
     val = Vector3.op_Addition(val, offset);
```
and only later steps change that to `val = val + offset` and then `val += offset`, but at that point it's too late to eliminate the ref-local.
To get rid of the local here, we'll need ILAst-level support for compound assignments with user-defined operators.

**Comment by dgrunwald** [comment]
Another option is to do what we did in ILSpy 2: eliminate ref locals by moving them to the site-of-use.
E.g.:
```
ref int x = GetArray()[GetIndex()];
DoSomething();
Use(ref x);
```
could almost be turned into:
```
var x_arr = GetArray();
var x_index = GetIndex();
DoSomething();
Use(ref x_arr[x_index]);
```

I say "almost" because the program behavior is now different if the index is out of bounds. But for most programs this probably doesn't matter. Not sure if such a transform is a good idea, though.

**Comment by CreateAndInject** [comment]
this one doesn't contains user-defined operators, but still contains ref with C# 4.0 / VS2010
```
					ref string val = ref array[1];
					string str = val;
					c = Key5[i];
					val = str + c.ToString();
```

**Comment by dgrunwald** [comment]
In that example, we don't know that `ToString()` doesn't somehow store/return the pointer to `c`, so eliminating the local variable could change program semantics as there are other uses of `c`.
I guess we'll have to analyze method signatures and see if the this reference could someone escape through the return value or an out parameter.
