### ISSUE TITLE
Get back the decompilation options

### ISSUE THREAD

**Issue by zvirja** [icsharpcode/ILSpy#1102]
I've just tested the latest beta (ILSpy 3.1 Beta 1) and noticed that you have stripped the decompilation options.
Before:
![image](https://user-images.githubusercontent.com/1074182/37725532-d99323fe-2d3b-11e8-89f2-20b10aa2305d.png)

After:
![image](https://user-images.githubusercontent.com/1074182/37725567-ec1893a6-2d3b-11e8-876d-05a6e78054e0.png)

This was a very useful feature. Sometimes I wanted to examine the internals of the particular state machine/iterator/expression tree and I was able to achieve that by simply disabling the decompilation feature. However, now there is no easy way to do that.

Is that technically possible to get back that decompilation options? If you believe that they pollute UI, we could move them somewhere separately.

Thanks.

**Comment by siegfriedpammer** [comment]
We have removed the individual options, because with the recent increase in different language features, the list of options got way too long. And second, many options depend on each other, so a simple list of check boxes is no longer useful.

If you have any idea how both features, i.e., "language versions" and "individual options", could be combined, we can discuss your ideas.

**Comment by dgrunwald** [comment]
You can still get a similar effect by switching the C# language version to one which didn't have those features.

The problem here is that we've implemented a bunch of new language features: there's currently 17 individual options controlled by the C# language version selection, and that number will only increase in the future. Having a checkbox for each individual option is no longer viable.
We could still have checkboxes for the most important ones, but then how would the checkbox state interact with the language version dropdown?

**Comment by zvirja** [comment]
The first question I tried to understand is whether this feature is about UI or implementation. Meaning, does the switches are still present in the code, or you decided to refactor the implementation to avoid them at all?

If question is about UI only, we might think about a way to implement that (e.g. combine that with C# Version picker). However, if you don't want to maintain switchers in the code - that's a completely different story.

So could you clarify the state of things?

**Comment by siegfriedpammer** [comment]
> Meaning, does the switches are still present in the code, or you decided to refactor the implementation to avoid them at all?

All the switches are still present... there are even more now, so we tried to simplify the UI.
The question is about the UI only.

**Comment by zvirja** [comment]
> All the switches are still present...

Ok, that's fine :)

Historically, each feature was introduced in the particular version of C#. That's exactly what you simulate when the version preset is selected.

What I suggest to do, is to extend that idea further and add one more C# version - `Custom`:
![image](https://user-images.githubusercontent.com/1074182/38194574-fbec5850-3680-11e8-8e52-dc85db1c277f.png)

When you pick that version, the pop-up appears where checkboxes for all the features are displayed, groupped by C# version. You could disable only features you need, keeping the rest features enabled. When you close application, we don't preserve the last customization and fallback to the latest available version (to not cause confusion). WDYT?

**Comment by zspitz** [comment]
If the problem is that there are now too many options, as an alternative to [zvirja's suggestion](https://github.com/icsharpcode/ILSpy/issues/1102#issuecomment-377911229) I suggest that the UI on the **View** -> **Options** -> **Decompiler** page have the following elements:

* (left) Listbox of C# language versions; should sync with the dropdown on the main window
* (right top) Textbox -- filter list of options based on text
* (right bottom) Listbox of options

If a particular C# version doesn't support a given option, then the user should not be able to select / deselect that option, and its value should be ignored.

**Comment by zvirja** [comment]
@siegfriedpammer Any final comments from your side before rejecting the idea? ;-)

**Comment by dgrunwald** [comment]
We think the presets based on language version are sufficient. Fine granular options would add a lot of complexity to the UI/settings code.
