### ISSUE TITLE
Issues with VS Extension v1.8 from Visual Studio Marketplace - can't open most assemblies from VS 2017

### ISSUE THREAD

**Issue by bbi-yggy** [icsharpcode/ILSpy#1125]
I just installed the latest version ("1.8 - Apr 8, 2018") from the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy). Installation was uneventful, and all the context menus appear in Visual Studio 2017, but ...

- right-click > Open in ILSpy on a reference yields an error "Could not find reference 'MyAssembly', please ensure the project and all references were built correctly." (The project has been rebuilt successfully.)
- right-click in the text editor > Open code in ILSpy does nothing at all

The assembly I tested with has two project references and two non-project references. One of the non-project references will open in ILSpy, the other will not. I tried toggling CopyLocal on and off for all references but it did not change the behaviour.

Has anyone else experienced these issues?

I'm using Visual Studio 2017, version 15.5.2. The Extensions and Updates window reports that the ILSpy add-in is version 1.8.0,.0.

I have previously built the add-in myself (I added the "Open code in ILSpy" feature), and can do so again to investigate what's happening, but thought I'd ask first to see if it's just me. Thanks!

**Comment by siegfriedpammer** [comment]
> I have previously built the add-in myself (I added the "Open code in ILSpy" feature), and can do so again to investigate what's happening, but thought I'd ask first to see if it's just me. Thanks!

Any help and contribution would be very welcome! Thank you!

I have refactored the code of the addin a bit in the last release, so I hope it will be easier to work with!

**Comment by zspitz** [comment]
I can confirm that I am seeing both issues.

**Comment by cremor** [comment]
I can also confirm this is still an issue with the latest version of the extension in Visual Studio 2017 15.7.2. I've tested it with a .NET Core project and found the following:

1. "Open code in ILSpy" in the text editor does nothing, just as @bbi-yggy said.
2. "Open in ILSpy" on a .NET Core SDK reference shows the error that @bbi-yggy mentioned.
3. But "Open in ILSpy" on a NuGet reference works fine!

**Comment by Rpinski** [comment]
The "Open in ILSpy" item has been shown on some nodes where it wasn't applicable at all. Fixes for all those cases are on the way.

**Comment by Rpinski** [comment]
Should be fixed with: 809354f175a4f128f1830ef67cf13f901dae9f1a.

If you like, you can test it as development drop from our build server:

https://ci.appveyor.com/api/buildjobs/502aqb2i7rn8s2pc/artifacts/ILSpy.AddIn%2Fbin%2FRelease%2Fnet46%2FILSpy.AddIn.vsix

**Comment by bbi-yggy** [comment]
@cremor thanks for testing. Yes, "Open code in ILSpy" in the text editor should be supported. That was a feature I added last year - it worked well at the time (after problems with overloaded methods and constructors in my initial commit, but I addressed those subsequently). I would also expect it to work on any assembly listed under References in the Solution Explorer. I no longer have the ILSpy development environment set up, but sounds like I should get it going again so I can investigate. My time is limited at the moment I'm afraid, so not sure when I will have a chance.

**Comment by Rpinski** [comment]
There were some issues with "Open code in ILSpy" feature, so we have disabled it for now. Currently I'm working on some fixes and then will reactivate it until next official release or one of the next dev drops. I agree that this feature is very useful and important.

**Comment by bbi-yggy** [comment]
@Rpinski OK, good to know, thanks. I did see a report of an issue of the feature not working with some project types - I had only developed and tested the feature with plain old C# projects, and I never had a chance to follow up on other types. I also developed and tested solely with Visual Studio 2015, so I don't know if 2017 introduced issues. Let me know if I can help.

**Comment by zspitz** [comment]
@Rpinski So perhaps this issue should be reopened?

**Comment by Rpinski** [comment]
Dev drop with reactivated and fixed "Open code in ILSpy" feature for code editor:

https://ci.appveyor.com/api/buildjobs/503fqj29s8yjkr3o/artifacts/ILSpy.AddIn%2Fbin%2FRelease%2Fnet46%2FILSpy.AddIn.vsix

**Comment by IanOfOz** [comment]
Thanks @Rpinski, looks good to me if the selected item is outside the solution, which I'd see as the most likely use case.

But if you hit 'Open code in ILSpy' within the text editor on a member that is defined within the current solution, it's getting an error. As it is, this gets  a failure when you open up ILSpy - it looks like the assembly in question isn't getting included on the ILSpy command line. The actual member is correct (as seen by the error that ILSpy reports). Ideally, though, would it possible to just perform a goto definition in this case (for intra-solution use)?  Or would you like a new issue for this?

**Comment by Rpinski** [comment]
Does the assembly exist in output directory? ILSpy is only able to access own project's members when the project has been built at least once.

Ok, now I reopen this issue as long as we have discussions here :)

**Comment by IanOfOz** [comment]
Yup, assembly exists in the output directory. I've tried members from within the same project (i.e. assembly) and others from other projects in the same solution. Both cases have the same result - the fully qualified member name reported within the ILSpy error is correct, but there's no sign of the accompanying assembly being loaded.

**Comment by Rpinski** [comment]
I've added several checks to detect the cases when referenced assemblies don't exist in expected path. In such cases a warning is shown instead of just launching ILSpy. For project references the add-in suggests to compile the solution.

Feel free to test the build and tell me, what you see now:

https://ci.appveyor.com/api/buildjobs/oywq4u8g8j44agmw/artifacts/ILSpy.AddIn%2Fbin%2FRelease%2Fnet46%2FILSpy.AddIn.vsix

**Comment by IanOfOz** [comment]
I've got a couple of solutions where I get the new error message every time I try to open ILSpy - even if I've the current code element is something from .Net Framework classes. And yet in other solutions it works totally fine - even finding code from within my solution.
The only difference I can pick between the working and non-working solutions is that the non-working solutions have projects that aren't in a direct sub-directory of the solution. e.g. following a pattern like this:

folderContainingSolution\folderJustForGroupingPurposes\folderContainingProject

Could that be an issue? If not, I'll see if I can pull the source down and debug it myself.

I just tried the same thing with the previous build you'd included on this issue and it does work for .Net framework classes (unlike the latest build), but as mentioned earlier fails for members from within the solution. But again it works fine in both cases where the solution structure is simpler (if that is the issue). So it looks like the checking that's been added in is a bit too aggressive for the more structured solutions.

Thanks

**Comment by Rpinski** [comment]
We don't make any assumptions on the path structure of projects. We just use the assembly output paths we get from project system and show an error message, if we can't find the file. Therefore I don't think that path structure is the reason. There must be something different. I assume the affected solutions are private and you can't share them with me? At least you could answer some questions about the working and non-working projects:

1. Which project type? Is the project .NET Core or "oldschool" .NET?
1. Which type of code element do you try to open?
1. Which message do you receive from the add-in exactly? (there are different...)
1. You've already said that, but to be sure: All projects you try to open in ILSpy are compiled and the output assembly in expected directory?

What happens in latest build (exact message, if any) when you try to open a .NET framework class?

**Comment by IanOfOz** [comment]
1. I've tried successfully on .Net Standard and "oldschool" .net. My two failing solutions are oldschool .Net (various versions).
2. Any code element I try seems to fail - method calls, constructors, interfaces. These can be from types from within the  solution or from .Net Framework types - i.e. in the solutions that don't work, nothing works. In the solutions that do work, everything works.
3. All cases give 'Can't show ILSpy for this code element'
4. Yup, everything is built.

I actually tried to build the ILSpy solution for myself to see if I could track it down, but ran into a build problem: 
Project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props" was not imported.... due to the file not existing.

Is there another part of VS 2017 I need to install? I have 15.7, with most of the C# workloads, but little C++. I couldn't find any suggestions in the readme here about what workloads are needed.

Thanks

**Comment by siegfriedpammer** [comment]
Sorry for the confusion. The dependency on the C++ compiler toolkit was added last weekend, so we could used the `editbin` utility to artificially increase the stack used for ILSpy.exe. In d23264248905efeda5204ccee10b35731b78e28f the dependency is now optional and I added some info on this to the readme  "How to build" section.

**Comment by IanOfOz** [comment]
Thanks, that got me further... now I'm running into 'project.assets.json' not found on every project. Unfortunately my corporate PC is stopping me from cloning the repo properly, so I can't update the git submodules... so I'm a little stuck unless @Rpinski has a brainwave about what's quirky about my solutions that's tripping over the add-in. Or maybe the stars will align and I'll be able to get the solution building locally.

**Comment by siegfriedpammer** [comment]
Could you please open a new issue for this? The submodules should actually be entirely optional, because the only submodule we currently use is `ILSpy-tests`, which is only needed for a small subset of tests. Thanks!

**Comment by siegfriedpammer** [comment]
Update: I downloaded the ILSpy source as zip file and tried it myself. I was only able to reproduce this problem once. It seems that VS 2017 got confused and was unable to restore the nuget packages automatically.

I was able to fix it by executing `nuget restore ILSpy.sln` in the "Package Manager Console" inside VS. Unfortunately I can no longer reproduce the problem, otherwise I would have filed a bug to VS.

Let's hope this works for you as well...

**Comment by IanOfOz** [comment]
Awesome, thanks, that confirmed that I was on the right path... once I took a guess and upgraded my version of nuget (we run 2.7 as we've got some custom commands added to it). I had tried 'nuget restore' before but it had very quickly done nothing, but given no error. So once you've confirmed that was the thing to do I tried harder.

So now everything is built happily and I've currently got a debug instance of Visual Studio running so I can look closer at the underlying issue.

@Rpinski  it's the third instance of the error message that's appearing, I'm just having some fun wading through the COM debugging to work out why that is. Hopefully I'll be able to report back soon.

**Comment by IanOfOz** [comment]
Well it turns out it is related to my nested projects. When there's projects within solution folders it seems enumerating through the projects in the solution only grabs the top level "projects", and in my case only one of this is actually a csproj file - the rest are solution folders. And each of these solution folders returns null for the FileName.

I managed to hack together a solution, but it failed as soon as I went one layer further down (i.e. solution folder within solution folder). Then I found this stack overflow post which looks to be a good basis for a solution (probably the second answer, I'd say): 

https://stackoverflow.com/questions/38740773/how-to-get-project-inside-of-solution-folder-in-vsix-project

I haven't managed to work that into a proper solution, but let me know if you'd like me to.

Thanks

**Comment by Rpinski** [comment]
Now I finally understood what you've meant with subfolders :)
I've added some code to handle the folder hierarchy correctly when trying to find the EnvDTE project instance: ea1b953b89ee55c69e7b670c14378c68e7ea5ad8

Please feel free to give it a try: https://ci.appveyor.com/api/buildjobs/33jjp4vi0u360gkp/artifacts/ILSpy.AddIn%2Fbin%2FRelease%2Fnet46%2FILSpy.AddIn.vsix

**Comment by Rpinski** [comment]
BTW: I've set up a test solution with several projects for the AddIn, where I also tried to reproduce your case:

https://github.com/Rpinski/ILSpy-TestProjects

**Comment by IanOfOz** [comment]
Ah, sorry for the confusion - I should have been referring to them as "solution folders" I suspect.

I've got that build and it now works as hoped within Visual Studio... until it actually runs ILSPY :(

I noticed that the VSIX runs a version of ILSpy that's installed beside the VSIX. That crashes every time I try to run it - either via VS or if I run it directly. It's reporting:

> Could not load file or assembly 'Microsoft.VisualStudio.Composition, Version=15.5.0.0...

Is there something else that I need to install?

**Comment by siegfriedpammer** [comment]
> Is there something else that I need to install?

No, but there was another bug I introduced in the build script. There is a post build target in ILSpy.csproj, that copies all the missing assemblies to the "Packages" folder in the AddIn. That way, all the dependencies, that are somehow forgotten by msbuild are added to the VSIX:

https://github.com/icsharpcode/ILSpy/blob/b5f0b8b2105a12b8b6ac585cc42167c0402e82f3/ILSpy/ILSpy.csproj#L396-L419

After adding another msbuild target with the name "PostBuild", only the last one was executed without any warning. On my machine this problem did not surface, because I already had all the required assemblies in the "Packages" folder of ILSpy.AddIn.

Now I have changed the names to something sensible and tested if that fixes the build.

Sorry again for messing this up!

**Comment by IanOfOz** [comment]
Ah, gotta love build scripts.

Thanks, that's sorted it out - after pulling the source down and building locally, the AddIn is now working as hoped.

And no worries about the hiccup - given the value that ILSpy brings, you're well and truly ahead :)

**Comment by cremor** [comment]
Is ILSpy.AddIn_3.2.0.3809-beta.vsix older than the test versions linked in this issue? Because since I installed the beta (both the WPF application and the Add-In) "Open code in ILSpy" is again doing nothing.

**Comment by dgrunwald** [comment]
Yes, there was a fix to the addin after the beta release.
You can find the current version on:
  https://ci.appveyor.com/project/icsharpcode/ilspy/branch/master
then click "Configuration: Release" then "Artifacts"
Please let us know if that solves your problem.

**Comment by cremor** [comment]
"Open code in ILSpy"  works fine with the latest artifact, thanks. (Except for the problem already reported in #1164)

But those things are still missing in SDK style projects (e.g. .NET Core project):

- "Open in ILSpy" on a NuGet reference sub node (which could either be another NuGet package or an assembly).
- "Open in ILSpy" on a SDK reference. I think this makes sense because the SDK node itself is just a collection. (Although it would be great if it could open all assemblies from the SDK at once.) But it would make sense to show it on the child nodes, which could be NuGet packages or assemblies, just like child nodes of NuGet references.
