### ISSUE TITLE
Some options on the Decompiler page seem to be more related to Display

### ISSUE THREAD

**Issue by zspitz** [icsharpcode/ILSpy#1130]
![2018-05-10 02_28_27-options](https://user-images.githubusercontent.com/312166/39844632-bc636138-53f9-11e8-9dd8-8529e6e0a00b.png)
AFAICT, the two options **Enable folding on all blocks in braces** and **Expand member definitions after decompilation** don't affect the text output in any way, so perhaps they should be on the Display page.

**Comment by siegfriedpammer** [comment]
You are correct from the user's point of view. But, in order to set fold markers and their initial state (collapsed/expanded) we need to tell the output layer of the decompiler during text generation to insert these markers. That's how the option landed in the DecompilationSettings class and thus in the DecompilerSettingsPanel.

I think it would involve a bit of work to move these settings to the other panel. Currently each panel has only one settings class it deals with. Is it worth the effort? You could try to move it and contribute a pull request. But, to be honest, I cannot think of a really clean way to solve this...

Two ideas, both of them are breaking changes to our public APIs and will affect plugin devs:
* Extend the Language class to add an "OutputOptions" class to each Decompile method.
* Extend the ITextOutput interface: Add properties for options or a single property for the options class. I think this is a bad idea, because the ITextOutput interface should stay unidirectional, i.e., only be the target of invocations and not carry any additional visible state.

I don't think this is going to happen in the 3.x version. Even if contributed, the earliest would be 4.0, due to semver constraints.

**Comment by dgrunwald** [comment]
I don't see why the API of `ICSharpCode.Decompiler` and the ILSpy UI have be related.
