### ISSUE TITLE
Syntax for ref re-assignment needs to be updated to match the actual syntax implemented in C# 7.3

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1147]
We've been emiting code to represent re-assignment of references before it was specified and allowed in C# 7.3. The syntax we have been using is: `ref a = ref b`, but it turns out that this is not the way it was actually implemented in C# 7.3 and causes the parser to get heavily confused. It completely breaks all IDE features.

We should update the expression builder and output visitor to emit the proper syntax for ref re-assignment. As per https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/ref-local-reassignment.md the proper syntax is: `a = ref b`.

The following snippet shows various problems with our current implementation of ref (or rather lack thereof, because it is actually not implemented):

	public static void Scale(ref Matrix4x4 mat, Vector3 s, bool trans)
	{
		Matrix4x4 identity = Matrix4x4.identity;
		identity[0, 0] = s.x;
		identity[1, 1] = s.y;
		identity[2, 2] = s.z;
		mat = identity * mat;
		if (trans)
		{
			ref Matrix4x4 reference;
			((Matrix4x4)(ref reference = ref mat))[0, 3] = reference[0, 3] * s.x;
			((Matrix4x4)(ref reference = ref mat))[1, 3] = reference[1, 3] * s.y;
			((Matrix4x4)(ref reference = ref mat))[2, 3] = reference[2, 3] * s.z;
		}
	}

After correcting the syntax errors mentioned at the beginning, we still get the following errors:
CS8174: A declaration of a by-reference variable must have an initializer at the line `ref Matrix4x4 reference`.
CS0131: The left-hand side of an assignment must be a variable, property or indexer on the following lines.

A compilable version of the code that is as close as possible to the code the decompiler currently emits, is the following:

	public static void Scale(ref Matrix4x4 mat, Vector3 s, bool trans)
	{
		Matrix4x4 identity = Matrix4x4.identity;
		identity[0, 0] = s.x;
		identity[1, 1] = s.y;
		identity[2, 2] = s.z;
		mat = identity * mat;
		if (trans)
		{
			ref Matrix4x4 reference = ref mat;
			reference[0, 3] = reference[0, 3] * s.x;
			reference[1, 3] = reference[1, 3] * s.y;
			reference[2, 3] = reference[2, 3] * s.z;
		}
	}

The optimal solution would be to decompile it to this beauty:

	public static void Scale(ref Matrix4x4 mat, Vector3 s, bool trans)
	{
		Matrix4x4 identity = Matrix4x4.identity;
		identity[0, 0] = s.x;
		identity[1, 1] = s.y;
		identity[2, 2] = s.z;
		mat = identity * mat;
		if (trans)
		{
			mat[0, 3] *= s.x;
			mat[1, 3] *= s.y;
			mat[2, 3] *= s.z;
		}
	}

**Comment by dgrunwald** [comment]
The issue with the inline ref-assignments is interesting: these occur only due to the early extra run of TransformAssignments prior to CopyPropagation. If that's disabled, then the compound assignment transform wins before the normal inline assignment transform, and we arrive at the optimal code.

For now I've disabled inline assignments for ref locals (mostly because we need to keep the first ref-assignment on statement level to avoid CS8174), which gives us the optimal code here.
However there are more cases where the pass ordering may cause problems. I think we need to consider some major changes to CopyPropagation, as this isn't the first time it causes serious pass ordering issues.
