### ISSUE TITLE
ILSpy doesn't show the variables declared locally

### ISSUE THREAD

**Issue by sudipto80** [icsharpcode/ILSpy#1170]
So if I have a method 

void fun ()
{
  int x;
}

It doesn't show up

**Comment by siegfriedpammer** [comment]
Can you please show the IL?

Normally the compiler will remove variables that are not used.

And the decompiler removes variables that are not used as well. Because sometimes the compiler generates temporary variables and it makes the code more readable, if we remove variables that are not used.

The compiler is free to optimize away local variables as it pleases, as long as they are not used as ref or out parameters. And the decompiler does the same to make the code more readable.

Why would you want to see declarations of variables that are not used?

This is a decompiler, not a source code converter.

**Comment by siegfriedpammer** [comment]
Closed. Reason: no feedback from OP.
