### ISSUE TITLE
Add an assembly filter category

### ISSUE THREAD

**Issue by richardszalay** [icsharpcode/ILSpy#1175]
I'm often in the position where I'd like to find a type (or method) within a particular assembly or group of assemblies. It would be great to be able to add an additional category that can be used in combination with an existing one. Something like:

```
# Find the String type in mscorlib
t:String a:mscorlib

md:Route a:/System\.Web\.Routing$/
```

I haven't looked into how this would fit into your current model, but is it something you'd accept a PR for?

**Comment by richardszalay** [comment]
Interesting. I'll look more into the detail of the current implementation and see if I can think of a way forward.

**Comment by miloush** [comment]
Okay, here is my go at this one: https://github.com/miloush/ILSpy/commit/5edf93f1e545659e9b6d32d904926b4d6c34a2a3

Search strategies must now implement a match decision on a `SearchResult`. The new `ScopedSearchStrategy` (not in dropdown) takes a main strategy and list of scoping strategies. The main strategy is performing the actual search, the scoping strategies filter the results. There is a pre-search phase which can exclude modules from searching, partially addressing #828 (only makes sense on assembly level though). Basically the results from main strategy go through an intermediate queue that does the filtering - all scoping strategies must report match in order to include the result.

As for syntax, use separate `in:` keyword. If the search text is multi-keyword and one of the terms is `in:`, then everything before goes to the main strategy and everything after goes to scoping strategies one keyword each. If any of the strategies cannot be resolved, no filtering happens.

Currently, you can scope by type name, resource name and assembly name. Some examples of syntax, assuming _Search for_ is set to _Type_:

All types in an assembly: `in: a:mscorlib`
All members in a class called AppContext: `m: in: =AppContext a:mscorlib`
Events containing "pin" in types containing "serial": `e:pin in: t:serial`
Resource file names containing "image" inside generated resource files: `r:image in: r:.g`

Thoughts?

**Comment by miloush** [comment]
Added namespace search strategy too (https://github.com/miloush/ILSpy/commit/2bea875fc672da3ddd9f069b01f212fab2cb125c), so you can scope search to namespace (using `n:`). This strategy supports pre-search matching as well, i.e. if the assembly does not contain any matching namespace it will not be searched by e.g. member search.

**Comment by siegfriedpammer** [comment]
This is nice, but it seems it's going to get too complex really soon... this is drifting in the direction of #742 or even #842...

**Comment by siegfriedpammer** [comment]
Also we should not forget to update https://github.com/icsharpcode/ILSpy/wiki/Search-Options and make sure everything is consistent and that there are no conflicts.

**Comment by miloush** [comment]
Yeah I am aware this is getting complex and with limited generalizability. Probably anything more complicated (such as AND/OR or parenthesis prioritization) will need a bit of redesign or proper parser. That's why I suggest this one more for a discussion, trying to address the most articulated need.
