### ISSUE TITLE
Tabbed UI

### ISSUE THREAD

**Issue by arturek** [icsharpcode/ILSpy#119]
The current version of ILSpy is able to display only one decompiled item at a time. Usually I need to see more methods or classes to find out how they work together, so I have added support for tabbed interface (based on AvalonDock). It's available in master branch of my arturek/ILSpy fork (arturek/ILSpy@a58dbcf108be591e6390) if you want to try it out. It's not a complete solution, rather a working example. What do you think about this idea? Should ILSpy stay SDI or could it be enhanced this way?

**Comment by MatthewBonner** [comment]
Please add tabs, this issue has been open since 2011 when tabs where not widely implemented, they are now, and people are used to tabs, please provide the option to either have a new window or a new tab as at present you cannot open multiple tabs at the same time. The reason the .NET Reflector UI has problems with tabs is because you don't get the option to open in a new tab by middle-clicking the mouse. In order to provide tabs you should have a context menu to open in a new tab, middle click on function references and the option to turn tabs on or off and then there won't be any issues.

**Comment by migig** [comment]
+1 tabs would make it so much more useful

**Comment by Verser** [comment]
+1
This is a very big thing. In general, some UI features could be incredibly helpful. Tabs, Favorite/bookmarks, Projects/Groups (to throw specific parts of assemblies together, like making a link to grouped buggy code).

I know some of this is on the roadmap, but as someone who uses it almost every day to make obfuscation checks, IL reading, and version differentials, it would be incredibly helpful to have these features.

**Comment by dolkensp** [comment]
@siegfriedpammer @Radon222 Is there any progress on this?

Honestly, I'd settle for "bookmarks" - I finally found one method I need, in a list of 1000 methods, but now I need to check another method, and coming back here is going to be a pain :P

Tabs would resolve this, as would bookmarks if a UI overhaul is imminent.

**Comment by siegfriedpammer** [comment]
Implementing bookmarks is on my list. However, I am currently very very busy, so no idea, when or if I ever will get around to it. :(

**Comment by siegfriedpammer** [comment]
superseded by #1724
