### ISSUE TITLE
How to get ModuleDefinition from LoadedAssembly?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1207]
It seems that ILSpy 4.x changes so much, my plugin can not compile.

**Comment by CreateAndInject** [comment]
I want to get the instance of ModuleDefinition from LoadedAssembly like GetModuleDefinitionOrNull/GetModuleDefinitionAsync in ILSpy3

**Comment by siegfriedpammer** [comment]
There is no Cecil ModuleDefinition anymore, we completely moved away from Cecil. You can use `GetPEFileOrNull().Metadata` to access the metadata tables.

**Comment by CreateAndInject** [comment]
Why don't use dnlib?

**Comment by christophwille** [comment]
We intentionally decided to use the official library used by the official .NET tooling. This makes us more or less "bug-compatible" when it comes to assemblies ILSpy can accept with ones that VS et al accept. Note that on purpose we do not venture into "overcoming security measures intended to make decompiling impossible".

**Comment by CreateAndInject** [comment]
SRM seems very low level and anti man, it's very hard to use
for example, the following method indicate whether a type is a component, how can I do it use SRM:
```
        public static bool IsComponent(this TypeDefinition td)
        {
            while (true)
            {
                if (td == null)
                    return false;
                var tr = td.BaseType;
                if (tr == null || tr.Scope.Name == "WindowsBase")
                    return false;
                if (tr.Scope.Name == "System" && tr.Name == "Component" ||
                    tr.Scope.Name == "System.Windows.Forms" && "Form Control UserControl".Split().Contains(tr.Name))
                    return true;
                td = tr.Resolve();
            }
        }
```

**Comment by dgrunwald** [comment]
We have a high-level type system (ICSharpCode.Decompiler.TypeSystem) wrapped around SRM.
Anytime you need `Resolve()`, that's a sure sign you should be working with the type system and not SRM directly. (only the type system provides a resolve implementation)

Note: there are different options to configure the type system. The ILSpy UI is using it essentially in "single-assembly-mode", so it can't resolve across assembly boundaries. You can create a full type system via `new DecompilerTypeSystem(...)`.

Use `typeSystem.MainModule.GetDefinition()` to get the `ITypeDefinition` for a `TypeDefinitionHandle`. Then you can use the `GetAllBaseTypeDefinitions()` extension method to walk the list of basetypes.

**Comment by CreateAndInject** [comment]
Why isn't there a 'Body' property in IMethod? How can I get instructions/variables/exceptionhandlers?

**Comment by siegfriedpammer** [comment]
We do not load method bodies in the type system, because it is metadata-only. Method bodies are stored in a different part of the binary.

You can take a look at the ILSpy source code. For example: https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/Analyzers/IAnalyzer.cs#L65

Note that there is no object model for instructions. You will have to do the byte parsing yourself. However there are some extension / helper methods in `ICSharpCode.Decompiler.IL.ILParser`. Having fine-grained control over the IL byte stream is one of the reasons, we moved to SRM. You can read more about it here: https://github.com/icsharpcode/ILSpy/wiki/srm

The analyzers (in ILSpy/Analyzers/Builtin) provide a great number of examples of how to parse byte streams using the new APIl.

For local variables you need to decode the local signature in MethodBodyBlock. For exception handlers decode the list of ExceptionRegions.

Hope this helps!

**Comment by siegfriedpammer** [comment]
If you have further questions, please open a new issue. Thanks!
