### ISSUE TITLE
Assertion failed: Struct fields can only be accessed with a pointer on the stack

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1224]
Using ILSpy 4
Assertion fails when compiled in both Debug and Release.

Source:
```cs
class AssertTest
{
    struct DataStruct { }

    struct WrapperStruct
    {
        internal DataStruct Data;
    }

    class SomeClass
    {
        internal WrapperStruct DataWrapper;
    }

    SomeClass someClass;

    public void Test()
    {
        GetMember(() => someClass.DataWrapper.Data);
    }

    public static MemberInfo GetMember<T>(Expression<Func<T>> p) => default;
}
```

**Comment by cshung** [comment]
Hello maintainers, I am interested in fixing this bug.

**Comment by dgrunwald** [comment]
Great! I haven't looked at it in detail, but believe the bug here is in `TransformExpressionTrees` producing an invalid ILAst in this case.
If you haven't seen the ILAst yet, check out [this comment](https://github.com/icsharpcode/ILSpy/issues/1126#issuecomment-384523392).

You can decompile the equivalent function using a lambda instead of expression tree, to see how the ILAst should look in this situation.

**Comment by cshung** [comment]
Thanks for the idea, I will look into the ILAst of the lambda.

I think I have an idea about what gone wrong in `TransformExpressionTrees `, here is what I am thinking right now.

https://github.com/icsharpcode/ILSpy/compare/master...cshung:dev/andrewau/1224?expand=1
