### ISSUE TITLE
async code missing from decompilation?

### ISSUE THREAD

**Issue by BrainSlugs83** [icsharpcode/ILSpy#1260]
Related to #529, I believe -- but I was trying to recover lost source for an exe I wrote, and one of the methods gets decompiled as:
````
[AsyncStateMachine(typeof(<ScheduledRebooter>d__4))]
[DebuggerStepThrough]
private static Task ScheduledRebooter(bool startRightAway)
{
	<ScheduledRebooter>d__4 stateMachine = new <ScheduledRebooter>d__4();
	stateMachine.startRightAway = startRightAway;
	stateMachine.<>t__builder = AsyncTaskMethodBuilder.Create();
	stateMachine.<>1__state = -1;
	AsyncTaskMethodBuilder <>t__builder = stateMachine.<>t__builder;
	<>t__builder.Start(ref stateMachine);
	return stateMachine.<>t__builder.Task;
}
````
But nowhere in ILSpy is the <ScheduledRebooter>d__4 class available (at least that I can find).

It does show up in the search, but, but clicking / double-clicking the items doesn't do anything. -- Additionally, when exporting the code as a .csproj, it's also missing, and the project doesn't compile because of it.

![image](https://user-images.githubusercontent.com/5217366/44233011-8f1bf180-a157-11e8-9bd0-fc7f6132a32e.png)

**Comment by BrainSlugs83** [comment]
(by the way, searching for just `d__4` does reveal a bunch of classes in the search, with a similar pattern, except that most of those seem to work, so I believe this is probably _not_ a UI bug.)

**Comment by BrainSlugs83** [comment]
Not sure if it's helpful at all, but I cloned the ILSpy source in the off-chance hope that maybe this would be fixed in latest (it's not. :( ) -- but I did notice that every time I clicked on that class, I saw this exception (which did not get thrown for other classes that I navigated to):

![image](https://user-images.githubusercontent.com/5217366/44234044-6cd7a300-a15a-11e8-8e5c-2e5e545efc35.png)

**Comment by dgrunwald** [comment]
The decompiler is looking for the fixed pattern that the C# compiler emits for `async/await`, and your assembly for some reason doesn't fit that pattern.

The class with the async/await implementation details is intentionally hidden in the UI, as the decompiler is supposed to reconstruct the original async method. The UI just does a quick check using attributes like `[CompilerGenerated]`, we can't afford to test-decompile whole classes just to see if a nested class should appear in the UI. If you select a language version that does not support async/await (C# 4 or older), the UI will show the class.

You would need to provide us with your assembly so that we can see why it has a different `MoveNext` structure. Maybe it was compiled with Mono? The async/await transform only supports the csc/roslyn code patterns.

**Comment by siegfriedpammer** [comment]
Concerning the UI: You now can set ILSpy to show all types and members, even compiler-generated code that is transformed, if properly detected.

Regarding the async detection bug: If you still have the executable, would you be able to provide it for further investigation? If you don't want to provide it publicly, you can send it to siegfried.pammer@gmail.com. Thank you very much!

**Comment by siegfriedpammer** [comment]
No feedback -> close.
