### ISSUE TITLE
Open from GAC results in unhandled exception

### ISSUE THREAD

**Issue by DotMPP** [icsharpcode/ILSpy#1267]
I go to File->Open from GAC... and get this exception dialog:

![image](https://user-images.githubusercontent.com/42625405/44494983-dbb57000-a622-11e8-80cb-aa692bac99f9.png)

Help->About:

ILSpy version 3.3.0.0-no-branch-alpha

ILSpy is the open-source .NET assembly browser and decompiler.
Website: https://ilspy.net/
Found a bug?: https://github.com/icsharpcode/ILSpy/issues/new

Copyright 2011-2017 AlphaSierraPapa for the SharpDevelop team
License: ILSpy is distributed under the MIT License.

Included open-source libraries:
 Mono.Cecil: MIT License (part of ICSharpCode.Decompiler)
 LightJson: MIT License (part of ICSharpCode.Decompiler)
 Humanizer: MIT License (part of ICSharpCode.Decompiler)
 AvalonEdit: MIT License
 SharpTreeView: LGPL
 Ricciolo.StylesExplorer: MS-PL (part of ILSpy.BamlDecompiler.Plugin)
 CommandLineUtils: Apache License 2.0 (part of ICSharpCode.Decompiler.Console)

Current and past contributors: https://github.com/icsharpcode/ILSpy/graphs/contributors

**Comment by siegfriedpammer** [comment]
I am unable to reproduce this. Seems there's something wrong with your .NET setup, because ILSpy uses the .NET Fusion COM interfaces for GAC traversal and that seems to be broken.

**Comment by DotMPP** [comment]
My real complaint is the exception handling does not appear to check for inner exceptions so there’s no clue (from within ILSpy) as to which file is not found. I suspect the issue is with my environment but it is lame to point at the “check the fusion log” when ILSpy could show a failing file path.

**Comment by siegfriedpammer** [comment]
Sorry for not being clear: the issue seems to be that the Fusion COM API `IAssemblyEnum.GetNextAssembly` we use returns null in its second out parameter. This is unexpected and the only thing we could do is skip all items that return null instead of a proper assembly name.

```
if (assemblyName == null) continue;
```

is the only solution to the exception. But that would only hide the problem of a seemingly broken .NET setup.

> the exception handling does not appear to check for inner exceptions 

The message shows all there is. There is no inner exception, as these would be shown as it is the default in .NET. I don't see how we could improve this other than ignoring null values, as explained above.

> but it is lame to point at the “check the fusion log”

I never told you to "check the fusion log", these words do not appear in my previous comment. I just explained that the problem is not within ILSpy, but rather within Microsoft's .NET Fusion COM API.

> when ILSpy could show a failing file path

Except when ILSpy cannot do that, because there is no info besides "the call to GetNextAssembly succeeded" (so there is no unmanaged error info either), and "oops, the name is null".

It is hard to further analyze the problem, because I cannot replicate it at all on my machine.
