### ISSUE TITLE
All Tokens of SyntaxTree given by Decompiler are Null

### ISSUE THREAD

**Issue by gatodevelop** [icsharpcode/ILSpy#1271]

**Comment by dgrunwald** [comment]
This is by design. The `SyntaxTree` classes are from NRefactory, which had a parser that was setting all those tokens.
But for code generation, ILSpy doesn't need to create token objects, so we avoid that step.
If we end up creating a purpose-built [SyntaxTree for ILSpy](https://github.com/icsharpcode/ILSpy/issues/1088#issuecomment-405047201). we'd leave out the token classes completely.

**Comment by siegfriedpammer** [comment]
What would you need the tokens for?

**Comment by gatodevelop** [comment]
For nothing. Thank you.
