### ISSUE TITLE
C++/CLI pinned local could be translated to fixed block

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1292]
[22.zip](https://github.com/icsharpcode/ILSpy/files/2453161/22.zip)

1.switch bug:
RxjhServer.物品类.fa(string)

2.There're ref locals even if I check C#4.0/VS2010 in RxjhServer.HUtil32 class
such as:
IntToArrat
ObjectToInt
StringToByteAry...

**Comment by dgrunwald** [comment]
In this case we might be able to generate something like `fixed (int *ptr = array)`, but in the general case there may always be left over ref locals that don't match any high-level patterns.
We can't magically make ref locals magically disappear, just like we can't magically erase generics just because you might select C# 1.0.
