### ISSUE TITLE
Visual Studio extension terminates VS instead of starting ILSpy

### ISSUE THREAD

**Issue by ygoe** [icsharpcode/ILSpy#1302]
When I right-click on a type or method in the code, an ASP.NET Core 2.1 project, the Visual Studio 2017 window freezes for a few seconds and then disappears. Nothing else happens. ILSpy is never started. This used to work a while ago.

This also happens on another machine (same configuration) here in the office.

All applications are up-to-date, no updates available. (stable branch, officially released)

**Comment by christophwille** [comment]
Can you please try the 4.0 Beta extension?

**Comment by Rpinski** [comment]
I could reproduce an exception in VS extension even with HEAD version. We'll investigate.

**Comment by Rpinski** [comment]
In case of an ASP.NET Core project we seem to exceed the [32767 byte limit for command lines](https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553/) when trying to launch ILSpy.exe. I've seen a command line of > 37000 bytes in my test. For a normal console app there were about 13000 bytes, so everything worked :)

I'll try using ILSpy's IPC interface instead of command line parameters. Unfortunately I can't offer any workaround to survive until the fix is ready.
