### ISSUE TITLE
Delegate and property references are incorrect 

### ISSUE THREAD

**Issue by Agrair** [icsharpcode/ILSpy#1369]
Ex:
Source code:
```cs
Main.OnTick += () => {...};
```

ILSpy code:
```cs
Main.add_OnTick(() => {...});
```

Ex:
Source code:
```cs
public static int SomeInteger { get; }
...........
otherInteger = SomeInteger;
```

ILSpy code:
```cs
public static int SomeInteger { get; }
...........
otherInteger = get_SomeInteger();
```

**Comment by Agrair** [comment]
Sorry if this is already an issue, sorry if it’s intentional, and sorry about the quality, I wrote all this on my phone.

**Comment by siegfriedpammer** [comment]
I cannot say for sure, but it seems that the decompiler is missing some references. Without the property or event definition we cannot say for sure whether a method is a property or event accessor, that's why we cannot use property/event access syntax.

Currently we do not have some smart algorithm that tries to infer that information from the method name. Looking at the current code, this would take some more work to get done.

**Comment by Agrair** [comment]
That’s probably why, considering I’m decompiled a plug-in.

**Comment by Agrair** [comment]
How would I fix it though? How do I add the reference?

**Comment by greenozon** [comment]
Drag-drop the ref. assembly into tree-view pane

**Comment by Agrair** [comment]
Thanks.
