### ISSUE TITLE
Fixed blocks not being generated in some cases

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1386]
Tested at commit 17d19cd04a9f6c8419772dcd88dce8d01f17e2d6
Test case compiled with VS 2013 Update 5.
Newer compilers generate the fixed block but incorrectly as in #1339.

Source:
```cs
class UnsafeArrayTest
{
    static object CreateBuffer(int length, IntPtr dataPtr)
    {
        throw new NotImplementedException();
    }

    unsafe static object Test(int arraySize, bool createFirstBuffer)
    {
        if (createFirstBuffer)
        {
            var array = new byte[arraySize];

            fixed (byte* ptr = array)
            {
                return CreateBuffer(array.Length, new IntPtr(ptr));
            }
        }

        var array2 = new byte[arraySize];

        fixed (byte* ptr = array2)
        {
            return CreateBuffer(array2.Length, new IntPtr(ptr));
        }
    }
}
```

Output:
```cs
internal class UnsafeArrayTest
{
    private static object CreateBuffer(int length, IntPtr dataPtr)
    {
        throw new NotImplementedException();
    }

    private unsafe static object Test(int arraySize, bool createFirstBuffer)
    {
        if (createFirstBuffer)
        {
            byte[] array = new byte[arraySize];
            byte[] array2 = array;
            reference = /*OpCode not supported: ArrayToPointer*/;
            return CreateBuffer(array.Length, new IntPtr(&reference));
        }
        byte[] array3 = new byte[arraySize];
        byte[] array4 = array3;
        reference2 = /*OpCode not supported: ArrayToPointer*/;
        return CreateBuffer(array3.Length, new IntPtr(&reference2));
    }
}
```

Occurs when compiled in both debug and release. The output from debug is mostly the same as above but some of the variable declarations are different.

**Comment by dgrunwald** [comment]
What's interesting about this case is that the compiler never resets the pinned local back to `null`, as is usual when control flow leaves a `fixed` block.
I guess this is because the control flow never really leaves the `fixed` block, but instead directly returns.
At least in non-optimized builds, the C# compiler re-uses a single `ret` instruction for all returns in the method, so the decompiler tries to move the block containing the `ret` into the fixed blocks. However, it's not possible for control flow to enter a `fixed` block anywhere but at the beginning, so the two control flow edges into the shared `ret` block cause the transform to give up.

The fix seems to be as simple as changing the pass ordering so that we copy the `ret` blocks before the PinnedRegions transform.
However there still seems to be an additional problem when compiling with Roslyn instead of the old csc.
