### ISSUE TITLE
class's static constructor is not displayed in the tree view

### ISSUE THREAD

**Issue by DaneSpiritGOD** [icsharpcode/ILSpy#1396]
class's static constructor is not displayed.

ILSpy version 4.0.0.4520-rc2

wpf DependencyProperty initialize progress disappears.Generally, it is in the static constructor.

**Comment by siegfriedpammer** [comment]
Can you please post an example binary?

The static constructor should only be hidden by ILSpy if it was not explicitly defined in the source code. We only hide the cctor if all statements could be moved to field initializers and if the `beforefieldinit` flag was set.

Take a look at these three cases:

```csharp
    public class ImplicitStaticCtor
    {
        private static readonly string someField = "Test";
        // no static ctor
        // it is emitted by the compiler and the type is marked `beforefieldinit`
        // see IL view.
    }

    public class ExplicitStaticCtor
    {
        private static readonly string someField = "Test";

        static ExplicitStaticCtor()
        {
            // no statements
            // `beforefieldinit` flag is not emitted on the type
        }
    }

    public class ExplicitStaticCtorWithInitializer
    {
        private static readonly string someField;

        static ExplicitStaticCtorWithInitializer()
        {
            // moved initializers
            someField = "Test";
            // `beforefieldinit` flag is not emitted on the type
        }
    }
```

Please note that the decompiler cannot distinguish the case in `ExplicitStaticCtor` and `ExplicitStaticCtorWithInitializer`. It will always emit a static constructor, because the `beforefieldinit` flag is not set on the type.

Generally hiding the static constructor on a type is not wrong, because the generated IL is different if it is not explicitly declared.

This might be wrong in your case, however, I can only analyze your specific case, if you provide the binary for further investigation. Thank you very much!

**Comment by DaneSpiritGOD** [comment]
// C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll
// PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// This assembly is signed with a strong name key.
// Hash algorithm: SHA1
// Public key: 0240048000940006200024005253413104001010b5fc90e727f67871e773a8fde8938c81dd42ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131aebd333c5ee6021672d9718ea31a8aebdda072f25d87dba6fc9ffd598ed4da35e44c398c45437e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c3855da9

sorry for my description. I make a mistake. I found the static cctor is in the right code but not in the class member list (left list).
All controls such as `Button`,`CheckBox` has static cctor in the code but not in the member list.
![image](https://user-images.githubusercontent.com/4377454/51172431-33b08400-18ee-11e9-8ff8-bb9c1c1a49e2.png)

**Comment by siegfriedpammer** [comment]
Seems like the "Show internal types and members"/"Show all types and members" option is turned off.

![grafik](https://user-images.githubusercontent.com/344204/51172946-adc41700-18b4-11e9-8155-c195c80aa0db.png)

If it is disabled, all private/internal code is hidden from the tree view, but still present in the code view. Static constructors are hidden, because they are always private.

**Comment by DaneSpiritGOD** [comment]
yes, you are right.
sorry for my neglect.
