### ISSUE TITLE
About MemberReferenceExpression in 4.0

### ISSUE THREAD

**Issue by sjx95** [icsharpcode/ILSpy#1407]
```C#
namespace Test
{
    class TSB
    {
        public void h()
        {
        }
        public void Tester()
        {
            h();
        }
    }
}

```
When I try to decompile a DLL as above, the behavior changed while building AST.

In Test.TSB.Tester(), it's an InvocationExpression "h()", with a MemberReferenceExpression property Target "h", while I'm using 3.1.
But in 4.0 the Target "h" is now an IdentifyExpression, I have no idea how to identify if h is a member of TSB or local function or delegate, and if it's a static member.

Could I get some hint here?

**Comment by sjx95** [comment]
Thanks! This is very helpful!

Besides, should I expect `(invocationExpression.GetResolveResult() as CSharpInvocationResolveResult).IsDelegateInvocation` return true while decompiling the `f()` as below? In my test case, this return false.
```C#
class T
    {
        public void M()
        {
            var f = new Func<string>(() => "STRING");
            f();
        }
    }
```

**Comment by siegfriedpammer** [comment]
Yes, that was missing. I fixed that.

**Comment by sjx95** [comment]
BTW in invocationExpression {h ()} where h is a normal member method, the `invocationExpression.Target.GetResolveResult()` return an `ErrorResolveResult`, is it expected?

**Comment by siegfriedpammer** [comment]
`ErrorResolveResult` is only returned, if there's no annotation available.

I tested the code you posted above and it returns an `ILVariableResolveResult` as expected.

```
invocationExpression.Target.GetResolveResult()
{[ILVariableResolveResult System.Func`1[[System.String]]]}
    ConstantValue: null
    IsCompileTimeConstant: false
    IsError: false
    Type: {System.Func`1[[System.String]]}
    Variable: "f" : {System.Func`1[[System.String]]}
    @type: {System.Func`1[[System.String]]}
```

Can you please post the code that causes this behavior? Thanks!

**Comment by sjx95** [comment]
Yeah delegate is OK, but member method failed. Here is the code, which using nuget package:
```C#
using System;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.TypeSystem;

namespace ILSpyCase
{
    class Program
    {
        class Visitor : DepthFirstAstVisitor
        {
            public override void VisitMethodDeclaration(MethodDeclaration methodDeclaration)
            {
                if (methodDeclaration.Name != "targetMethod") 
                    return;
                base.VisitMethodDeclaration(methodDeclaration);
            }

            public override void VisitIdentifierExpression(IdentifierExpression identifierExpression)
            {
                base.VisitIdentifierExpression(identifierExpression);
                Console.WriteLine(identifierExpression);
                Console.WriteLine(identifierExpression.GetResolveResult());
                Console.WriteLine(identifierExpression.GetSymbol());
                Console.WriteLine("========");
            }
        }

        static void Main(string[] args)
        {
            var dec = new CSharpDecompiler(System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName, new DecompilerSettings());
            var ast = dec.DecompileType(new FullTypeName("ILSpyCase.Case"));
            ast.AcceptVisitor(new Visitor());
        }
    }

    class Case
    {
        private Func<int> func = () => 233;
        int method() { return 233;}

        void targetMethod()
        {
            func();
            method();
        }
    }
}
```
And here is the result:
```
func
[MemberResolveResult 04000001 ILSpyCase.Case.func]
04000001 ILSpyCase.Case.func
========
method
[ErrorResolveResult ?]

========
请按任意键继续. . .
```

**Comment by siegfriedpammer** [comment]
Yes, that is expected.

The information is stored on the `InvocationExpression`. That is because the name of the method alone is not enough to identify the method. We only could attach a `MethodGroupResolveResult` to the identifier, but currently we do not do this.

**Comment by sjx95** [comment]
Excuse me, `CSharpInvocationResolveResult.IsExtensionMethodInvocation` doesn't work as I expect, could you please have a check? It used to return `True` in 3.1, but now False.

I think this may be a similar problem as `IsDelegateInvocation`.

Here is my test case:

```C#
using System;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.Resolver;
using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.TypeSystem;

namespace ILSpyCase
{
    class Program
    {
        class Visitor : DepthFirstAstVisitor
        {
            public override void VisitMethodDeclaration(MethodDeclaration methodDeclaration)
            {
                if (methodDeclaration.Name != "targetMethod") 
                    return;
                base.VisitMethodDeclaration(methodDeclaration);
            }

            public override void VisitInvocationExpression(InvocationExpression invocationExpression)
            {
                var irr = invocationExpression.GetResolveResult() as CSharpInvocationResolveResult;
                Console.WriteLine(invocationExpression);
                Console.WriteLine($"IsExtensionMethodInvocation: {irr.IsExtensionMethodInvocation}");

                base.VisitInvocationExpression(invocationExpression);
            }
        }

        static void Main(string[] args)
        {
            var dec = new CSharpDecompiler(System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName, new DecompilerSettings());
            var ast = dec.DecompileType(new FullTypeName("ILSpyCase.Case"));
            ast.AcceptVisitor(new Visitor());
        }
    }

    static class StaticMethods
    {
        public static void ExtMethod(this Case c) { }
    }

    class Case
    {
        void targetMethod()
        {
            this.ExtMethod();
        }
    }
}
```

**Comment by siegfriedpammer** [comment]
Do you need any other help? Can this be closed?

**Comment by Piedone** [comment]
Sorry to revive an old issue but I just stumbled upon this too. As far as I see `h()` will be an `InvocationExpression` with an `IdentifierExpression` as a target only when the invocation is within the declaring type. If it's called from another class for example then the target will be a `MemberReferenceExpression`.

Prior to v3 both cases were `MemberReferenceExpression`s and I'd argue that semantically that's correct: the method `h` is a member, no matter where it is called from, not a local function or variable containing a delegate for example. @siegfriedpammer can you share the rationale behind this design decision? I'd guess it was a deliberate change since if previously a `MemberReferenceExpression` was possible to create at the same place it should be now as well.

BTW this is true not just for methods but at least for properties as well.

The issue with this new AST style is that while previously the same logic could process an invocation of a given method everywhere in the AST now the logic needs to care about both a `MemberReferenceExpression` and `IdentifierExpression`. I think I'll do an AST processor that find all of these and changes them into `MemberReferenceExpression`s.

**Comment by sjx95** [comment]
In my case I make a transformer before processing, too.
I guess this change is following a more strict definitions from C#?

**Comment by Piedone** [comment]
I'm not sure. For anybody else stumbling upon this, this is the visitor I run through the whole `SyntaxTree`:

```
        private class MemberIdentifiersFixingVisitor : DepthFirstAstVisitor
        {
            public override void VisitIdentifierExpression(IdentifierExpression identifierExpression)
            {
                base.VisitIdentifierExpression(identifierExpression);

                var parent = identifierExpression.Parent;
                var identifier = identifierExpression.Identifier;

                var member = parent.GetResolveResult<MemberResolveResult>()?.Member;
                ThisResolveResult thisResolveResult;
                if (parent is InvocationExpression invocation && invocation.Target == identifierExpression)
                {
                    // A normal method invocation.
                    thisResolveResult = new ThisResolveResult(member.DeclaringType);
                }
                else if (identifierExpression.GetResolveResult<MemberResolveResult>() is MemberResolveResult memberResolveResult)
                {
                    // A property access.
                    if (memberResolveResult.Member.Name != identifier)
                    {
                        return;
                    }

                    member = memberResolveResult.Member;
                    thisResolveResult = memberResolveResult.TargetResult as ThisResolveResult ?? new ThisResolveResult(member.DeclaringType);
                }
                else
                {
                    return;
                }

                var thisReferenceExpression = new ThisReferenceExpression().WithAnnotation(thisResolveResult);

                var memberReference = new MemberReferenceExpression(thisReferenceExpression, identifier)
                    .WithAnnotation(new MemberResolveResult(thisResolveResult, member));
                identifierExpression.ReplaceWith(memberReference);
            }
        }
```

Not thoroughly tested yet. Note that this adds `this` expressions to every member access.

**Comment by Piedone** [comment]
@siegfriedpammer could you check out the above messages, please?

**Comment by siegfriedpammer** [comment]
> Sorry to revive an old issue but I just stumbled upon this too.

@Piedone in general, I would prefer if you would open a new issue for such things, because closed issues are off my radar and if I accidentally mark the notification email as read it gets lost and I simply forget about your comment. I am sorry for this, but these things happen.

> As far as I see h() will be an InvocationExpression with an IdentifierExpression as a target only when the invocation is within the declaring type. If it's called from another class for example then the target will be a MemberReferenceExpression.

This change was introduced by #1093, which was at the request of Microsoft.

> Prior to v3 both cases were MemberReferenceExpressions and I'd argue that semantically that's correct: the method h is a member, no matter where it is called from, not a local function or variable containing a delegate for example. @siegfriedpammer can you share the rationale behind this design decision? I'd guess it was a deliberate change since if previously a MemberReferenceExpression was possible to create at the same place it should be now as well.

There isn't actually a design decision. Prior to the change, we simply never emitted any unqualified member access, but we were asked to improve the decompiler to generate less verbose code.

> The issue with this new AST style is that while previously the same logic could process an invocation of a given method everywhere in the AST now the logic needs to care about both a MemberReferenceExpression and IdentifierExpression.

The problem is that the AST is not a semantic tree, but is a syntax tree and syntactically <identifier> and <identifier>.<member> are different. For your use case, a semantic tree similar to the ILAst would be more useful (as @dgrunwald already pointed out in https://github.com/icsharpcode/ILSpy/issues/1848#issuecomment-562722939).

Note that Roslyn's syntax tree is very similar in this regard, because it's derived directly from the C# specification. If you were implementing an analyzer in Roslyn, you would have to deal with both variants of the syntax.

**Comment by Piedone** [comment]
Thanks for your replay Siegfried. I didn't want to open a new issue because I think my inquiry is the same as this one, and I wouldn't want to add clutter.

So if I understand correctly this is then deliberate and then this can be closed again? I've worked around this with a visitor. Unfortunately, using ILAst is not a realistic option at this stage.

**Comment by siegfriedpammer** [comment]
> So if I understand correctly this is then deliberate and then this can be closed again?

Yes.

> I've worked around this with a visitor.

I hope this is a bearable solution for you.

> Unfortunately, using ILAst is not a realistic option at this stage.

That is unfortunate, however, we think, it would save you a lot of trouble in the long run.

**Comment by Piedone** [comment]
Got it, thanks.
