### ISSUE TITLE
 Can ILSpy.Debugger.Plugin.dll file be placed in binaries? 

### ISSUE THREAD

**Issue by nonomal** [icsharpcode/ILSpy#1427]
Can ILSpy.Debugger.Plugin.dll file be placed in binaries? Or can you provide a source code compilation tutorial?

**Comment by christophwille** [comment]
That isn't listed in https://github.com/icsharpcode/ILSpy/wiki/Plugins - where would you have gotten that from? (if it is from an old ILSpy version, nope, that shouldn't work)

**Comment by dgrunwald** [comment]
Some background info:
ILSpy 2.x used to have an experimental debugger; but it was too much work to maintain a debugger engine in addition to the decompiler engine, so we dropped that approach. Commit 7ce68392deaac0 was the last one before the debugger was removed.
The current ILSpy builds (5.x) instead generate debug symbols (.pdb files), so that you can use an existing debugger like Visual Studio.
