### ISSUE TITLE
Hanging when decompiling

### ISSUE THREAD

**Issue by terrylao** [icsharpcode/ILSpy#1429]
[TransCode.zip](https://github.com/icsharpcode/ILSpy/files/2883784/TransCode.zip)
as attachment,
when save code, it always show decompiling, over 10 minutes.

**Comment by siegfriedpammer** [comment]
This is caused by huge array initializers in `CodeConvert..ctor`:
1) 41670 elements (`Host2UTF_tbl`)
2) 65536 elements (`EBCDIC_tbl`)
3) 65536 elements (`BIG5_tbl`)

These are expanded from `RuntimeHelpers.InitializeArray`, so not generating the initializer syntax is not possible. I think the main problem is the code that converts ILAst to C# code as detailled in #1202.

**Comment by siegfriedpammer** [comment]
Decompiling the CodeConvert class is now down to 14 seconds in debug build.
