### ISSUE TITLE
when save code,  decompiling not ended

### ISSUE THREAD

**Issue by terrylao** [icsharpcode/ILSpy#1430]
not like my previous problem, this time, it looks all cs file are generated, but the dialogbox
decompiling not ended.

**Comment by siegfriedpammer** [comment]
Can you please provide the assembly that causes the problem? Thank you very much!

**Comment by siegfriedpammer** [comment]
Any update on this? Thank you!

**Comment by terrylao** [comment]
Sorry, this time cannot provide DLL.
but the code looks generate correctly, but dialog box not ended.

**Comment by siegfriedpammer** [comment]
That is unfortunate. By "dialog box" you mean the "wait bar" (i.e. the "Decompiling" text plus the progress bar)? Or are you talking about the "Save file" dialog box?

**Comment by terrylao** [comment]
1. "the decompiling dialog"
2. i found that .csproj will not generate correctly. when i click cancel, it leave "Decompiled was cancelled." in .csproj

**Comment by terrylao** [comment]
file uploaded

**Comment by siegfriedpammer** [comment]
Thank you for providing the file. Are you using a release or debug build of ILSpy to decompile the code? Keep in mind that a debug build is excessively slower than a release build due to a massive amount of correctness checks that are performed after each step.

**Comment by siegfriedpammer** [comment]
A release build completes after 117,4 seconds on my machine.

**Comment by siegfriedpammer** [comment]
Performance analysis: There are two methods that take a long time:
* CLR_Library_CS.ChineseCommercialCode.ChinaChineseCommercialCodeConverter..ctor
* CLR_Library_CS.ChineseCommercialCode.TaiwanCommercialCodeConverter..ctor

The majority of time is spent inside `ILInlining.InlineOne` at `block.Instructions.RemoveAt(pos);`.

@dgrunwald is it possible to defer the update of the child indices in `RemoveAt`?

The structure of the method looks similar to a collection initializer. So there are a lot of calls to an Add method.

**Comment by dgrunwald** [comment]
`ChildIndex` is one of the properties that is assumed to be always-up-to-date, and is used internally for `ReplaceWith()` and similar operations. I don't see a way to defer that without making the ILAst much more error-prone to work with.

Even if it wasn't for the child index update, the underlying `list.RemoveAt()` is still O(N).

An alternative might be to replace the instructions with a dummy `Nop` and then later clean that up with a single `RemoveAll` call (but that still needs to happen within the same transform, otherwise all other transforms would have to learn to look past those `Nop`s).

**Comment by dgrunwald** [comment]
Well I guess we could use a more clever data structure to allow `RemoveAt()` including child-index update in O(lg N) time (something like AvalonEdit already does when deleting a line). But that might end up running quite a bit slower for small collections (and there's lots of those!). I guess we could switch between implementations depending on the collection size... not sure if that complexity is worth it.

**Comment by dgrunwald** [comment]
It turns out there was a simple win available: `ILInlining.InlineAllInBlock()` was working forwards, when backwards makes more sense (as with most other statement transforms).

Unfortunately it also changed the way in which inlining fails when fully inlining is not possible, which in turn affects the named arguments transform. So I had to refactor that a bit to handle the new cases.

For me, this change improves performance in release builds from 85.5s to 20.5s.

Debug builds remain slow for very large functions; this is because debug builds validate the whole function after each transform step.

**Comment by terrylao** [comment]
in 5.0.0.4772 this problem appear again
