### ISSUE TITLE
Name collision, local generated var

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1454]
I just encountered the following decompiled output (I believe input IL shouldn't matter for this case - it should stand out what is in error):

```
foreach (int num2 in array)
{
	int num2 = num2 - ((num2 >> 1) & 0x55555555);
...
}
```
That second `num2`-definition is clearly a troublemaker. :-)

**Comment by siegfriedpammer** [comment]
Can this be reproduced using a Microsoft compiler? If not, it would be very helpful, if you could provide a simplified version of the original IL as file. I would like to add it to our tests. Thank you very much!

**Comment by tamlin-mike** [comment]
Well, it is introduced by PatternStatementTransform, turning a for i loop into foreach.

Here's the IL. I hope it helps:
```
.method public hidebysig static 
	int32 GetCardinality (
		class [mscorlib]System.Collections.BitArray bitArray
	) cil managed 
{
	.maxstack 5
	.locals init (
		[0] int32[],
		[1] int32,
		[2] int32,
		[3] int32
	)

	IL_0000: ldarg.0
	IL_0001: callvirt instance int32 [mscorlib]System.Collections.BitArray::get_Count()
	IL_0006: ldc.i4.5
	IL_0007: shr
	IL_0008: ldc.i4.1
	IL_0009: add
	IL_000a: newarr [mscorlib]System.Int32
	IL_000f: stloc.0
	IL_0010: ldarg.0
	IL_0011: ldloc.0
	IL_0012: ldc.i4.0
	IL_0013: callvirt instance void [mscorlib]System.Collections.BitArray::CopyTo(class [mscorlib]System.Array, int32)
	IL_0018: ldc.i4.0
	IL_0019: stloc.1
	IL_001a: ldloc.0
	IL_001b: ldloc.0
	IL_001c: ldlen
	IL_001d: conv.i4
	IL_001e: ldc.i4.1
	IL_001f: sub
	IL_0020: ldelema [mscorlib]System.Int32
	IL_0025: dup
	IL_0026: ldind.i4
	IL_0027: ldc.i4.m1
	IL_0028: ldarg.0
	IL_0029: callvirt instance int32 [mscorlib]System.Collections.BitArray::get_Count()
	IL_002e: ldc.i4.s 32
	IL_0030: rem
	IL_0031: ldc.i4.s 31
	IL_0033: and
	IL_0034: shl
	IL_0035: not
	IL_0036: and
	IL_0037: stind.i4
	IL_0038: ldc.i4.0
	IL_0039: stloc.2
	IL_003a: br.s IL_007b
	// loop start (head: IL_007b)
		IL_003c: ldloc.0
		IL_003d: ldloc.2
		IL_003e: ldelem.i4
		IL_003f: stloc.3
		IL_0040: ldloc.3
		IL_0041: ldloc.3
		IL_0042: ldc.i4.1
		IL_0043: shr
		IL_0044: ldc.i4 1431655765
		IL_0049: and
		IL_004a: sub
		IL_004b: stloc.3
		IL_004c: ldloc.3
		IL_004d: ldc.i4 858993459
		IL_0052: and
		IL_0053: ldloc.3
		IL_0054: ldc.i4.2
		IL_0055: shr
		IL_0056: ldc.i4 858993459
		IL_005b: and
		IL_005c: add
		IL_005d: stloc.3
		IL_005e: ldloc.3
		IL_005f: ldloc.3
		IL_0060: ldc.i4.4
		IL_0061: shr
		IL_0062: add
		IL_0063: ldc.i4 252645135
		IL_0068: and
		IL_0069: ldc.i4 16843009
		IL_006e: mul
		IL_006f: ldc.i4.s 24
		IL_0071: shr
		IL_0072: stloc.3
		IL_0073: ldloc.1
		IL_0074: ldloc.3
		IL_0075: add
		IL_0076: stloc.1
		IL_0077: ldloc.2
		IL_0078: ldc.i4.1
		IL_0079: add
		IL_007a: stloc.2

		IL_007b: ldloc.2
		IL_007c: ldloc.0
		IL_007d: ldlen
		IL_007e: conv.i4
		IL_007f: blt.s IL_003c
	// end loop

	IL_0081: ldloc.1
	IL_0082: ret
}
```

**Comment by siegfriedpammer** [comment]
Thank you for providing the IL as test case.

@dgrunwald Do you think it would make sense to recombine ILVariables with the same name and index after the ILAst transformation is finished?

Of course we can fix this by adding the following check to the transform:

```csharp
if (itemVariable.Function.Variables.Any(v => v != itemVariable && v.Name == itemVariable.Name))
	return null;
```

However, this would prevent us from transforming two separate loops that use an "item" variable with the same name. Which is perfectly legal in C#.

Or is there some logic in `DeclareVariables` I could reuse here? As far as I understand `DeclareVariables` has to solve this exact problem in order to avoid declaring multiple variables with the name `num2`.

**Comment by dgrunwald** [comment]
Yes, `DeclareVariables` has logic for exactly this case:
Commit cad933184a13be582606ca3994699558a6466f99:  Don't introduce foreach when doing so would create a conflict with another variable of the same name as the loop variable.

I guess that PST change was lost because back then we didn't have "foreach over array" logic; and all the foreach logic we had back then was moved to the ILAst. And of course the relevant test cases in that commit use `IEnumerable`, not arrays.

**Comment by dgrunwald** [comment]
Note that simply recombining the variables in the ILAst is not possible: variables need to stay separate until `DeclareVariables` runs, otherwise it would be unable to declare a variable twice in different scope. (the current DeclareVariables assumes that variables are already split; unlike the ILSpy 2.x approach which had to re-run definite assignment analysis when declaring variables)
