### ISSUE TITLE
View panel sees the "www" variable as a link

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1496]
ILSpy Version: `5.0.0.4688-preview1`

Example:

```
WWW www = new WWW("example.jpg"));
yield return www;
if (www.error != null) {
	Debug.LogError(www.error + " with " + puzzleLevelName);
}
```

Image:

![date](https://user-images.githubusercontent.com/16493751/56473213-7f844380-6470-11e9-9c85-f939b915d8b1.png)

If the variable name is `www`; accordingly, ILSpy understands it as a link. Therefore, if we click that, web browser opens.

**Comment by Dentrax** [comment]
@siegfriedpammer 

Should we have to deal with [ReferenceElementGenerator.cs](https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/TextView/ReferenceElementGenerator.cs) file?

In the [DecompilerTextView.cs](https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/TextView/DecompilerTextView.cs#L655), `isLink()` function returns hard-coded `true` value. Shouldn't we return `false` if variable name is `www`?

Also I think the hyperlinks already being checked in a function from **AvalonEdit** which is already defined in `ReferenceElementGenerator`.

**Comment by siegfriedpammer** [comment]
These hyperlinks are not generated by `ReferenceElementGenerator`. [LinkElementGenerator](https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Rendering/LinkElementGenerator.cs) from AvalonEdit is responsible for these.

I am not sure how common URIs/URLs are in source code and whether providing automated links in ILSpy is important. If we decide it is not necessary to provide links, we can simply disable the feature by setting `TextEditorOptions.Enable[Email]Hyperlinks` to false. Otherwise we might need a more elaborate workaround: basically disabling/removing the built-in `LinkElementGenerator` and providing a more sophisticated implementation, that knows whether the current text segment is inside a comment or string and only then generate hyperlinks.

**Comment by dgrunwald** [comment]
Hyperlinks might occur in XmlDoc or string literals, but I think we can live without that feature in decompiled code. The AboutPage still needs hyperlinks, though.
