### ISSUE TITLE
same as #1430 appear again

### ISSUE THREAD

**Issue by terrylao** [icsharpcode/ILSpy#1513]
please refer to #1430 and its attachment, the slow save code appear again

**Comment by terrylao** [comment]
ILSPY 2.4.0.1963 spent 14.8 seconds.
5.0.0.4772-preview1 suddenly spent 24.5 seconds to complete
5.0.0.4794-preview2 suddenly spent21.6 seconds to complete
when i make this issue, version 5 cannot complete, but after use ver 2.4.0.1963, they can completed.

**Comment by dgrunwald** [comment]
I cannot reproduce this with the current version:
5.0.0.4932-preview3 takes 18 seconds on my machine (release build of ILSpy).
A debug build of the same ILSpy version takes 50 seconds for me, but that's normal as the debug builds perform a ton of additional consistency checks.

That ILSpy 5 is slower than ILSpy 2 is normal -- ILSpy 2 was mostly just guessing the corresponding C# code, and would often get it wrong. ILSpy 3+ use a more accurate approach -- ILSpy actually now contains half a C# compiler implementation, for example it tries to re-compile any decompiled function calls to check if the generated code will call the correct overload (if not, it inserts additional casts). This improved accuracy costs a lot of CPU time, so ILSpy 5 being a bit slower than ILSpy 2 is expected.

**Comment by dgrunwald** [comment]
Looking at the profile for your assembly, I think a significant speed up is possible if we already construct simple trees in `ILReader`, so that we don't need to generate as many `StackSlot` variables and `ILInlining` doesn't have to work as hard.
But that will require a pretty significant rewrite of the ILReader (which is already planned for other reasons, see #901)
