### ISSUE TITLE
casted argument passed to implicit operator loses cast

### ISSUE THREAD

**Issue by arbruijn** [icsharpcode/ILSpy#1574]
ILSpy master 2019-06-19

The following code, where A and C are a valuetype and `implicit operator bool (A a)` and `implicit operator C(bool b)` exists,

```cs
C c = (bool)default(A)
```
decompiles to:
```cs
C c = (C)((byte)default(A) != 0);
```

The `(bool)` cast is reconstructed from the first (A->bool) implicit operator call, but removed from the ILAst when processing the second (bool->C) implicit operator call. The cast is removed by `arg.ConvertTo()` in `CallBuilder.BuildArgumentList` because `allowImplicitConversion` is true.

I've changed the `ConvertTo()` call to set `allowImplicitConversion` to false when the called method is an implicit operator:
`allowImplicitConversion: arg.Type.Kind != TypeKind.Dynamic && (!method.IsOperator || method.Name != "op_Implicit")`

This seems to work, the example is correctly decompiled and tests still pass.

Example code:
```cs
class Test {
        struct A {
                public static implicit operator bool (A a) { return false; }
        }
        struct C {
                public static implicit operator C(bool b) { return default(C); }
        }
        void M() {
                C c = (bool)default(A);
        }
}
```

.NET Core 2.2 IL for method M:
```
IL_0000: nop
IL_0001: ldloca.s 1
IL_0003: initobj Test/A
IL_0009: ldloc.1
IL_000a: call bool Test/A::op_Implicit(valuetype Test/A)
IL_000f: call valuetype Test/C Test/C::op_Implicit(bool)
IL_0014: stloc.0
IL_0015: ret
```
Assembly: [testconv.zip](https://github.com/icsharpcode/ILSpy/files/3388998/testconv.zip)

**Comment by dgrunwald** [comment]
Thanks for the detailed bug report.

I don't think your proposed fix is sufficient; it does not fix related issues such as:
```
		public void Call_Overloaded()
		{
			Overloaded((bool)default(A));
                        // also gets decompiled as: Overloaded((byte)default(A) != 0);
		}

		private void Overloaded(A a)
		{
		}

		private void Overloaded(bool a)
		{
		}
```

The CallBuilder first tries to leave out implicit conversions and then later re-introduces them if necessary (here: only if the second overload exists). Unfortunately, it forgets that the original conversion was user-defined, and uses a code path meant to re-introduce built-in conversions.
In most cases the end result is a straight cast so that problem wasn't noticed, but conversions to `bool` are special-cased to use the `(byte)val != 0` trick, since that is the expected semantics when an integer is converted to `bool` in IL.
