### ISSUE TITLE
Feature 'ref reassignment' is not available in C# 7.0

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1605]
Looks like language combobox does not update the "ref" feature usage

eg, setting Language to C# 7.0 / VS2017
produces error

error CS8107: Feature 'ref reassignment' is not available in C# 7.0. Please use language version 7.3 or greater.

PS
used ILSpy version 5.0.0.4970-preview3

**Comment by dgrunwald** [comment]
What should ILSpy use instead?

Ref assignments are a fundamental IL feature, it's not a high-level construct that can be disabled to decompile the low-level code instead.

**Comment by greenozon** [comment]
Yes, you are right, using 7.3 is a must for these kind of constructions
then last question on ref usage in this context would be this one:

```
		private double vectorVariance(int[] v)
		{
			double[] array = new double[3];
			double num = 0.0;
			int upperBound = v.GetUpperBound(0);
			ref double reference2;   // <<<<<<<<<<<<<<<<<<<<<<<<

Error	CS8174	A declaration of a by-reference variable must have an initializer	

			for (int i = 0; i <= upperBound; i = checked(i + 3))
			{
				ref double reference = ref array[0];
				reference2 = ref reference;
				reference = reference2 + (double)v[i];
				ref double reference3 = ref array[1];
				reference2 = ref reference3;
				reference3 = reference2 + (double)v[checked(i + 1)];
				ref double reference4 = ref array[2];
				reference2 = ref reference4;
				reference4 = reference2 + (double)v[checked(i + 2)];
			}
			ref double reference5 = ref array[0];
			reference2 = ref reference5;
..............
```

**Comment by dgrunwald** [comment]
ILSpy 2.x (which dnSpy is still using) had a trick to avoid ref locals for the specific case of array elements:
```
ref T arrayElement = ComputeArray()[ComputeIndex()];
Stuff();
Use(ref arrayElement);
```
can almost be replaced with
```
var array = ComputeArray();
int index = ComputeIndex();
Stuff();
Use(array[index])
```

The difference is that this moves any `NullReferenceException`/`IndexOutOfRangeException` from the real position (`ldelema` opcode) to whereever the address is used --> Stuff() incorrectly gets executed when an exception happens.

The problem here is that ILSpy failed to detect the `array[0] +=  (double)v[i];` compound assignment, which in turn seems to be caused by a failure to detect that the various uses of `reference2` are independent of each other. I'd need to see the whole method to check what might be causing it; is this part of one of the assemblies that you already uploaded?

**Comment by greenozon** [comment]
https://www.sendspace.com/file/ne9e7i

**Comment by dgrunwald** [comment]
Actually, SplitVariables managed to separate the `reference2` uses just fine here.

It's just that where C# compound assignments store the array element reference on the IL evaluation stack; VB seems to use a compiler-generated ref local instead (and reuses that ref local for multiple compound assignments). Enabling ILInlining for ref locals seems to be sufficient to solve this issue.
