### ISSUE TITLE
Inline ref locals more aggressively

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#1610]
[test.zip](https://github.com/icsharpcode/ILSpy/files/3464804/test.zip)
```
public static float[] fa = new float[1] { 234f };
public static void Main(string[] args)
{
	ref float reference = ref fa[0];
	ref float reference2 = ref reference;
	float num = reference;
	reference2 = num + 1000f;
	Console.WriteLine(fa[0]);
}
```

Is it possible to inline these locals?
e.g. `fa` was not assigned, so all these assignments can be optimized to `fa[0] += 1000f;`

**Comment by dgrunwald** [comment]
The problem here is the local variable `float num` -- it doesn't fit any of the normal cases of compiler-generated variables, so we don't eliminate it.
Usually I'd expect a compiler to directly use the result of loading from the array in the addition, without the local in between.
Aggressively removing local variables whenever possible would result in unreadable code (too much packed into a single line).

I made copy propagation a bit more aggressive, which at least eliminates `ref float reference2`.
But if `float num` isn't eliminated, the `+=` pattern doesn't apply, and without that, `ref float reference` has to stay.

Which compiler did you use to create this assembly?

**Comment by sgkoishi** [comment]
> 
> 
> The problem here is the local variable `float num` -- it doesn't fit any of the normal cases of compiler-generated variables, so we don't eliminate it.
> Usually I'd expect a compiler to directly use the result of loading from the array in the addition, without the local in between.
> Aggressively removing local variables whenever possible would result in unreadable code (too much packed into a single line).
> 
> I made copy propagation a bit more aggressive, which at least eliminates `ref float reference2`.
> But if `float num` isn't eliminated, the `+=` pattern doesn't apply, and without that, `ref float reference` has to stay.
> 
> Which compiler did you use to create this assembly?

I found this code in a copyrighted XNA game assembly, which I'm not sure what compiler was used.
However, Visual Studio 2019 (Visual C# Compiler version 3.2.0-beta4) did generate these local variables: when I use regex to replace this pattern to assignments and recompile it.

This pattern only happens in big methods (with >= 80000 lines of IL), and affecting most of the assignment of float / hardcode-indexed float array. The decompiled  result looks the same as my sample, but the IL was a little bit different.
```
// ref float reference = ref something[0];
ldelema [mscorlib]System.Single
// (no C# code)
stloc.2
// ref float reference2 = ref reference;
ldloc.2
// float num74 = reference;
ldloc.2
ldind.r4
stloc.s 99
// reference2 = num74 + 1f;
ldloc.s 99
ldc.r4 1
add
stind.r4
```

After commit fc73851bb4f90c09818845982b24aceb4d79e7f8:
```
// ref float reference = ref something[0];
ldelema [mscorlib]System.Single
// (no C# code)
stloc.2
// reference = num74 + 1f;
ldloc.2
// float num74 = reference;
ldloc.2
ldind.r4
stloc.s 99
// (no C# code)
ldloc.s 99
ldc.r4 1
add
stind.r4
```

**Comment by dgrunwald** [comment]
We now have an option "Always inline local variables if possible" that will force inlining of `num` even though I don't see a reason why a compiler would emit a local here.
