### ISSUE TITLE
DeclareVariables.EnsureExpressionStatementsAreValid causes local variable naming conflict

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#1681]
[Sample.zip](https://github.com/icsharpcode/ILSpy/files/3561035/test.zip)
```csharp
using System;

public struct Target
{
}

public class Parent
{
    public Target target;
}

public class C : Parent
{
    public void Foo()
    {
        var target = this.target;
    }
}
```

Result:
```csharp
public void Foo()
{
    Target target = target;
}
```
`this.` was hidden, and second `target` leads to `CS8174 A declaration of a by-reference variable must have an initializer`.

**Comment by siegfriedpammer** [comment]
Which version of the decompiler did you use? I can no longer reproduce this in rev, 5099, however was able to reproduce this in rev. 5066.

Can you confirm? Thanks!

**Comment by sgkoishi** [comment]
I can reproduce it in both `5066` and `5109`(CI build).

**Comment by siegfriedpammer** [comment]
Sorry, I cannot reproduce this. Note that 5109 is a PR build, which may or may not contain relevant changes. Please always check whether the build is from master.

**Comment by sgkoishi** [comment]
> 
> 
> Sorry, I cannot reproduce this. Note that 5109 is a PR build, which may or may not contain relevant changes. Please always check whether the build is from master.

I've test `5066` and `5099` on a new virtual machine, and `base.target` was used correctly. Is there any options/config file controlling this?

**Comment by sgkoishi** [comment]
I see the problem. I've upload the wrong sample binary - sorry for that.
[Sample.zip](https://github.com/icsharpcode/ILSpy/files/3563888/test.zip)

**Comment by siegfriedpammer** [comment]
The problem is: The field access is not stored in a variable. `DeclareVariables.EnsureExpressionStatements` creates a variable, but at that point we no longer can change the field access and add a qualifier.

Possible solution:
* for C# 7 or later we can always use discards, e.g., `_ = target;`.
* for all earlier versions, we could use `_` as variable name, which would be very much less likely to collide with a non-local name. Multiple declarations would then use `_2`, `_3`, but I guess that this will be a very rare case.

@sgkoishi The setting `Remove dead stores` will cause this bug to appear more frequently, however I don't think that this was the problem in your case.
