### ISSUE TITLE
SwitchDetection/SwitchOnStringTransform does not work, if hash method is not named "ComputeStringHash"

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1702]
search method : `comboBox1_SelectedValueChanged`

```
private void comboBox1_SelectedValueChanged(object sender, EventArgs e)
{
.....
	uint num2 = <PrivateImplementationDetails>.smethod_0(text2);
	if (num2 <= 1583700141)
	{
		if (num2 <= 806828493)
		{
			if (num2 <= 386101911)
			{
				if (num2 != 351508891)
....
```

[1.zip](https://github.com/icsharpcode/ILSpy/files/3625069/1.zip)

**Comment by CreateAndInject** [comment]
one more:
[2.zip](https://github.com/icsharpcode/ILSpy/files/3639460/2.zip)

Analyze <PrivateImplementationDetails>.smethod_0 (show all types and members)
There're 4 results.

**Comment by siegfriedpammer** [comment]
Triage: The switch transform does not work, because the method located in `<PrivateImplementationDetails>` is not named `ComputeStringHash`. The only thing I can think of right now is that we might have to add some "semantic" pattern detection to deduce whether the method produces a hash. Looking at different `ComputeStringHash` method instances, it seems the IL is always identical. So we could check whether the IL instructions are the same?

See https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Compiler/MethodBodySynthesizer.Lowered.cs#L14-L42 for the code that is generated by Roslyn.´

The only problem with this approach I can think of (other than performance issues) is that obfuscators might start to change the IL of this generated function.

**Comment by CreateAndInject** [comment]
It's not a issue for me now
