### ISSUE TITLE
VSIX: Open code in ILSpy doesn't navigate

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1711]
Repro: use Frontends.sln in this repo, open IlspyCmdProgram.cs and eg try to "open code in ilspy" with Path.GetFileNameWithoutExtension (line 88). Neither tree nor decompiled view shows the expected navigation but instead goes to last selected item from previous ILSpy session.

**Comment by Rpinski** [comment]
Analysis so far: The AddIn passes correct information to ILSpy, but ILSpy sometimes (!) doesn't navigate and just opens last location instead. Maybe some sort of race condition in ILSpy or with the IPC interface.

**Comment by dgrunwald** [comment]
Is the AddIn trying to use the IPC interface while ILSpy is still starting up?
It would be easier for ILSpy if the arguments were passed via command-line in that case.

I think the problem might be that ILSpy is asynchronously restoring the last selected item from the previous session; we'd need to ensure that the IPC call doesn't race ahead of that operation / cancels it.

**Comment by dgrunwald** [comment]
That can't be it; there's a `treeView.SelectedItem == initialSelection` check, so `NavigateOnLaunch` is canceled if there's a user/IPC navigation while the assembly-load is awaited.

But the IPC call also uses this code path, so I guess it's possible that:
 * ILSpy OnLoad navigation starts
 * IPC navigation starts
 * ILSpy OnLoad navigation finished
 * IPC navigation is aborted because the selected item changed while the navigation was in-progress

**Comment by Rpinski** [comment]
Now passing `/navigateTo:none` from AddIn in 115f8ab0d9485f61a31bbf3dd989070147bb84d0.
Seems to be stable now.
