### ISSUE TITLE
.NET Core App: It always open reference assembly

### ISSUE THREAD

**Issue by wiz0u** [icsharpcode/ILSpy#1720]
When writing a .NET Core application, ILSpyAddIn seems to direct to 'reference assemblies' most of the time, which makes it kind of useless because these assemblies don't contain the code of the methods.

Step to reproduce:
* Under VS2019, create a new project "Windows Forms App (.NET Core)"
* In Program.Main(), type `var folder = Environment.CurrentDirectory;`
* Right-click on `CurrentDirectory` > "Open code in ILSpy"
* You land on the method with a warning "This assembly is marked as 'reference assembly'

ILSpy/ILSpyAddIn 5.0.0.5124

**Comment by Rpinski** [comment]
Tried exactly the same like you did with VS 16.3.1 (.NET Core 3.0 final) and it worked correctly with `CurrentDirectory`. I've found another problem with unresolved assemblies, which occurred specifically with Windows Forms framework assemblies, which should be fixed with c12b5d60ec26d439907fd825dabb80fdf87d5448, but that doesn't look exactly like your problem.

**Comment by wiz0u** [comment]
What can i do to provide more details?

(note also that if ILSpy is not already open, it will open but stay on the previously navigated node -in last usage- instead of the symbol under Visual Studio's caret, it's another problem I have, but not related to the 'reference assembly' issue)

**Comment by Rpinski** [comment]
Ah, sorry, now I see the issue with reference assemblies is occurring here, too. There seems to be an issue with resolving the correct assembly between .NET Core and .NET Framework.

**Comment by daniel-liuzzi** [comment]
This issue seems to have come back as of **ILSpy/ILSpyAddIn 6.0.0.5836**.

Following the steps described in the original post results in the same _This assembly is marked as 'reference assembly'_ behavior:

![image](https://user-images.githubusercontent.com/143884/88223890-7f24ba80-cc68-11ea-9b10-a49342f9e0c9.png)

**Comment by christophwille** [comment]
Please open a new issue
