### ISSUE TITLE
switch(string) decompilation via Dictionary doesn't handle static readonly string fields

### ISSUE THREAD

**Issue by lbmaian** [icsharpcode/ILSpy#1742]
I have a `switch` statement operating on a string that's compiled as a `Dictionary<string, int>` definition and lookup. This doesn't decompile correctly because a ~~`const`~~ `static readonly` string field's value is added as a key in the dictionary.

Current example decompilation:
```cs
if (symbol != null)
{
	if (<>f__switch$map0 == null)
	{
		Dictionary<string, int> dictionary = new Dictionary<string, int>(40);
		dictionary.Add(string.Empty, 0);
		dictionary.Add("label", 1);
		dictionary.Add(MyClass.MyStaticReadonlyString, 2);
		dictionary.Add("description", 3);
	}
	if (<>f__switch$map1.TryGetValue(symbol, out value))
	{
		switch (value)
		{
		case 0:
			// string.Empty case
			break;
		case 1:
			// "label" case
			break;
		case 2:
			// MyClass.MyStaticReadonlyString case
			break;
		case 3:
			// "description" case
			break;
		}
	}
}
```

Expected example decompilation:
```cs
switch (symbol)
{
case "":
	break;
case "label":
	break;
case "happyfuntimes":
	break;
case "description";
	break;
}
```

Don't have an example dll readily available, since the dll is proprietary and is compiled in a way I can't replicate (some old mcs compiler, I think), and it would take a long time to manually craft the example CIL.

**Comment by siegfriedpammer** [comment]
This is tricky... would it be possible for you to provide the DLL through a private channel?

We would have to evaluate the value produced by the `ldsfld` instruction if the field is `static readonly`, because referencing non-constant fields in switch cases is prohibited by any modern C# compiler (I tested both legacy csc and Roslyn). If the field is a const field, all modern compilers directly use the string value, even if it is defined in a referenced assembly.

If mcs once allowed `static readonly` fields to be used as switch cases, this is a compiler bug and as we want to preserve semantics correctly, we cannot transform the generated IL back to C# as it violates the specification and would change semantics.

**Comment by lbmaian** [comment]
Oops, I meant `static readonly` fields, not `const` fields (since `const` fields are always "inlined" as you point out). `string.empty` indeed is a `static readonly` field.

I could provide the dll through a private channel, but github no longer has DMs and I don't see an email address for you.

**Comment by lbmaian** [comment]
Also, the dll only has the `string.empty` case, no other `static readonly` string fields are involved, so I suspect it's just special-casing for the empty string.

**Comment by siegfriedpammer** [comment]
Please send it to siegfried.pammer@gmail.com. Thank you!

**Comment by lbmaian** [comment]
Thanks, confirmed the latest build fixes the issue.
