### ISSUE TITLE
ILSpy tries to get address of managed type

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1759]
ILSpy version 6.0.0.5288-alpha1

```
	[SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed")]
		public unsafe void AlterStoredProcedure<TParameters>(string name, Func<ParameterBuilder, TParameters> parametersAction, string body, object anonymousArguments = null)
		{
			Check.NotEmpty(name, "name");
			Check.NotNull(parametersAction, "parametersAction");
			AlterProcedureOperation alterProcedureOperation = new AlterProcedureOperation(name, body, anonymousArguments);
			AddOperation(alterProcedureOperation);
			TParameters parameters = default(TParameters);
			*(TParameters*)(&parameters) = parametersAction(new ParameterBuilder());
			((TParameters*)(&parameters))->GetType().GetNonIndexerProperties().Each(delegate(PropertyInfo p, int i)
			{
				ParameterModel parameterModel = p.GetValue(*(TParameters*)(&parameters), null) as ParameterModel;
				if (parameterModel != null)
				{
					if (string.IsNullOrWhiteSpace(parameterModel.Name))
					{
						parameterModel.Name = p.Name;
					}
					alterProcedureOperation.Parameters.Add(parameterModel);
				}
			});
		}
```

Issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0208	Cannot take the address of, get the size of, or declare a pointer to a managed type ('TParameters')	EntityFramework	C:\Temp\delme\EntityFramework\System.Data.Entity.Migrations\DbMigration.cs	48	Active

**Comment by greenozon** [comment]
[EntityFramework.zip](https://github.com/icsharpcode/ILSpy/files/3761034/EntityFramework.zip)

**Comment by siegfriedpammer** [comment]
Original source:

https://github.com/aspnet/EntityFramework6/blob/7d7d5fe22240bebaae76352828165822aa99940a/src/EntityFramework/Migrations/DbMigration.cs#L167-L199

**Comment by dgrunwald** [comment]
The `parameters` variable uses the type parameter from the display class; whereas the field accesses/calls use the type parameter from `AlterStoredProcedure` itself. These are different types, so ILSpy inserts a cast. Casts between reference types are currently expressed as pointer casts.

I think this is a bug in `TransformDisplayClassUsage`; it should be substituting the type arguments so that all types used during the decompilation of a method are from that method's scope.
