### ISSUE TITLE
Problem with boolean logic

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1830]
It appears there is an issue with boolean logic. Following is the original code.
```
public Program()
{
    bool b1 = true;
    bool b2 = false;

    Debug.Assert(b1 &= true);
    Debug.Assert(b1 |= true);
    Debug.Assert(b1 ^= false);
}
```
Following is the translated code
```
public Program()
{
    bool b5 = true;
    bool b4 = false;
    Debug.Assert(b5 = b5);
    int num = (b5 ? 1 : 0) | 1;
    b5 = ((byte)num != 0);
    Debug.Assert((byte)num != 0);
    Debug.Assert(b5 = b5);
}
```

**Comment by dgrunwald** [comment]
The translated code seems correct to me, though it's unfortunate that the decompiler decided to switch from `bool` to `int` and back.

The `x & true` and `x ^ false` are optimized out by the C# compiler.

**Comment by dgrunwald** [comment]
When using `byte` instead of bool, the first step of the transformation is to construct an inline assignment.
This works by transforming:
```
			stloc S_5(conv i4->u1 (binary.bit.or.i4(ldsfld b2, ldc.i4 3)))
			stloc V_0(ldloc S_5)
			stsfld b2(ldloc S_5)
```
to
```
			stloc V_0(stsfld b2(conv i4->u1 (binary.bit.or.i4(ldsfld b2, ldc.i4 3))))
```
This transform is only valid if the store to `b2` doesn't perform implicit truncation -- IL works with `I4` as stack type, so a store to memory will truncate the value when storing to a `bool`/`byte`/`short`.
In this case, the decompiler sees that a `conv i4->u1` can only produce values that fit into a `byte`, so the store doesn't perform any additional truncation, and the transform is valid.

In the `bool` case, the C# compiler doesn't produce any `conv` instruction:
```
			stloc S_4(binary.bit.or.i4(ldsfld b1, ldc.i4 1))
			stloc V_0(ldloc S_4)
			stsfld b1(ldloc S_4)
```
(and even if it did, a conv to `u1` doesn't prove that the value fits into `bool`)

So the decompiler needs to learn to reason about the possible values produced by `bit.or` to safely perform the transformation back to `b1 = b1 | true`.

**Comment by dgrunwald** [comment]
New output with 93806b46fa8bef::
```
	Debug.Assert(b5 = b5);
	Debug.Assert(b5 = ((byte)((b5 ? 1 : 0) | 1) != 0));
	Debug.Assert(b5 = b5);
```
The bool->int->bool issue only occurs when using a compile-time constant `true`. I don't think that's a realistic use of `|=`, so I don't think I'll introduce a special case just for this.
The cases with normal non-constant booleans are fixed now.
