### ISSUE TITLE
Invalid decopmilation: accessibility level for CompilerGenerated method

### ISSUE THREAD

**Issue by Vasar007** [icsharpcode/ILSpy#1863]
Recently, I've played with [SharpLab](https://sharplab.io/) service which uses ILSpy internally and found a bug with invalid accessibility level for CompilerGenerated method.

Code samples you can find in [this issue](https://github.com/ashmind/SharpLab/issues/451) (I've reported at [SharpLab repository](https://github.com/ashmind/SharpLab) at first).

I don't know if there's enough information in that issue to figure out what the problem is.

**Comment by siegfriedpammer** [comment]
This is by design. See https://github.com/icsharpcode/ILSpy/blob/0d6ac5030cb857d06d15279d734643da006e0f77/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs#L1250-L1257

Currently we change the accessibility of local functions to `private` although they are defined as `internal` in IL. This is because if a local function captures variables, the C# compiler generates `private structs`, which are then used as parameter types of the local function. A method exposing types of lesser accessibility in their signature causes `CS0051: Inconsistent accessibility: parameter type 'T' is less accessible than method 'M'`.

see for example https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQOB2AhgLYCmAzgA4EDGJABMugOw4DeOdnDqAzB1+2xdhdCgCcwANwLB6jAGwMALHQCyBMHgAUASn4i6ggwc3A6ADzoBeOj1QBufcc6m6AMV3WAfHSWo68BaOQs5cHjrBzgC+TjHYUUA===

We always want to produce compilable and semantically correct code: changing the accessibility has no impact on semantic correctness, because the method is only used inside the current type anyway. And it allows us to produce code that is compilable. The only thing we lose is consistency between IL and C# metadata in this one case.

@ashmind The only thing we could do is add another option that lets you control this behavior.
@dgrunwald Any thoughts?

**Comment by siegfriedpammer** [comment]
Addendum: I will add extra checks, so we only perform this transformation, if `private structs` are used in the local functions implementation. Changing the accessibility is not necessary in your specific case.

**Comment by Vasar007** [comment]
Oh, that's an interesting fact about local functions for me! Thanks for explanation.

But I cannot understand one thing. Why is changing the accessibility wrong in my specific case? In my example, compiler generated `private` class has a `private` method that is called **outside** the class. If we try to compile such code, we will get something like:

```csharp
error CS0122: 'Program.Class.Foo()' is inaccessible due to its protection level
```

**Comment by siegfriedpammer** [comment]
> But I cannot understand one thing. Why is changing the accessibility wrong in my specific case?

See my follow-up comment https://github.com/icsharpcode/ILSpy/issues/1863#issuecomment-565989753
