### ISSUE TITLE
System.BadImageFormatException: Invalid coded index.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1877]
Expand any type and click Derived types.

**Comment by siegfriedpammer** [comment]
Can you please provide an example? Thank you!

**Comment by CreateAndInject** [comment]
Just click it:
![image](https://user-images.githubusercontent.com/2529999/71523312-68e99280-2903-11ea-98a5-11bf6f4d6564.png)

**Comment by CreateAndInject** [comment]
Why can't I reproduce it? I didn't update ILSpy.

**Comment by siegfriedpammer** [comment]
The "Derived Types" node looks at all assemblies in the current assembly list and collects all types that derive from the current type (`AggregateException` in your case). The cause for this exception is another (invalid) assembly in your assembly list.

I think the reason that you can not longer reproduce the exception is that you removed the culprit/invalid assembly from the assembly list. Just like I cannot reproduce the exception because I do not have the assembly.

**Comment by CreateAndInject** [comment]
You're right, just now, I loaded an obfuscated file and got this:
![image](https://user-images.githubusercontent.com/2529999/71548843-040b6680-29ef-11ea-9ede-4227c00e47fb.png)

**Comment by siegfriedpammer** [comment]
@CreateAndInject Can you still reproduce the exception? I cannot verify the fix I added in the commit above, as I do not have the assembly that causes the problem. Thank you very much!

**Comment by CreateAndInject** [comment]
I draged thoughts of files to ILSpy, but I can't reproduce BadImageFormatException, maybe I delete that file or I can't find it.

But I find 2 files to reproduce ArgumentNullException, one is fixed in the lastest commit, another one isn't fixed:
[test.zip](https://github.com/icsharpcode/ILSpy/files/4090215/test.zip)

**Comment by siegfriedpammer** [comment]
Thank you very much!
