### ISSUE TITLE
[Question] Why is it necessary to check for the CompilerGenerated Attr

### ISSUE THREAD

**Issue by frankli0324** [icsharpcode/ILSpy#1905]
Some obfuscators seems to be removing the `CompilerGenerated` attributes (maybe I didn't get it right), but `TypeDefinition.IsCompilerGenerated` checked whether the attribute existed.
Why is it necessary?
I find it confusing. I thought it's some kind of bug.
![image](https://user-images.githubusercontent.com/20221896/72222656-419cf180-35a2-11ea-9551-70aae948e59b.png)

**Comment by siegfriedpammer** [comment]
Decompilation is pattern matching for the most part. In order to reduce the number of false positives, we use all information available to discern compiler-generated code from user code. Things like async-await and yield state machines or lambda/local function closures use a lot of compiler-generated code, which if misdetected leads to completely broken code.

Note that obfuscation is a technique to make decompilation useless and we neither want nor can play tag with obfuscation engines. This is a game where the obfuscation engine creators have a huge advantage and trying to catch up with them is neither fun nor interesting.

**Comment by frankli0324** [comment]
thanks for replying
is it reasonable to judge whether a symbol is compiler generated by determing whether a illeagal character appeared in the name?
