### ISSUE TITLE
Unable to decompile some expression with Nullable reference type(C#8.0)=on

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1940]
Tested with 6.0.0.5593-preview2

Some expression is able to decompile with C#7.3, but failed with `Nullable reference type`(C#8.0) on

It can be tested with the below code, or `Microsoft.EntityFrameworkCore.Storage.ValueConversion.StringToBytesConverter..ctor(Encoding,ConverterMappingHints)` from `Microsoft.EntityFrameworkCore`(An extra assert is fired for the latter, but it should be the same reason)

`Expression<Func<string, object>> exp = (string str) => ((str != null) ? str.ToLower() : null);`

**Comment by dgrunwald** [comment]
Whether this reproduces seems to depend on the set of reference assemblies loaded.
If I open EntityFrameworkCore in an otherwise empty assembly list, ILSpy auto-loads the reference from `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.17` and the assertion does not occur (probably because .NET Core 2.1 doesn't have any nullable reference types).
But if I use an existing assembly list that has System.Runtime etc. loaded from `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3`, the entity framework decompilation seems to use the already-loaded reference assemblies, and ends up triggering the assertion.
Some assemblies like `System.Private.CoreLib.dll` have version 4.0.0.0 in both cases, thus the assembly list thinks that it's already loaded. Maybe we should change our assembly loading to keep the different .NET Core versions better apart? @siegfriedpammer 

In this case it should be harmless that we use System.Private.CoreLib from a newer .NET core version (apart from the bug with nullable reference types); but it can also happen the opposite way around: loading EntityFrameworkCore first causes future .NET Core 3 projects in the same assembly list to use the older System.Private.CoreLib  version, which then results in "Unknown result type (might be due to invalid IL or missing references)" warnings and potentially incorrect decompilation.

**Comment by dgrunwald** [comment]
Without nullable reference types, the `StringToBytesConverter` ctor decompiles to:
```
public StringToBytesConverter([JetBrains.Annotations.NotNull] Encoding encoding, [JetBrains.Annotations.CanBeNull] ConverterMappingHints mappingHints = null)
	: base((Expression<Func<string, byte[]>>)((string v) => (v == (string)null) ? null : encoding.GetBytes(v)), (Expression<Func<byte[], string>>)((byte[] v) => (v == null) ? null : encoding.GetString(v)), mappingHints)
{
}
```

In C# 8 mode with .NET Core 3 `System.Private.CoreLib.dll`, the `StringToBytesConverter` ctor triggers the `foreach (var child in Children) { Debug.Assert(child.Parent == this);` assertion, and decompiles to:
```
public StringToBytesConverter([JetBrains.Annotations.NotNull] Encoding encoding, [JetBrains.Annotations.CanBeNull] ConverterMappingHints mappingHints = null)
{
	ParameterExpression parameterExpression = Expression.Parameter(typeof(string), "v");
	<>c__DisplayClass0_0 CS$<>8__locals0;
	Expression<Func<string, byte[]>> convertToProviderExpression = Expression.Lambda<Func<string, byte[]>>(Expression.Condition(Expression.Equal(parameterExpression, Expression.Constant(null, typeof(string))), Expression.Constant(null, typeof(byte[])), Expression.Call(Expression.Field(Expression.Constant(CS$<>8__locals0, typeof(<>c__DisplayClass0_0)), FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/)), (MethodInfo)MethodBase.GetMethodFromHandle((RuntimeMethodHandle)/*OpCode not supported: LdMemberToken*/), parameterExpression)), new ParameterExpression[1]
	{
		parameterExpression
	});
	parameterExpression = Expression.Parameter(typeof(byte[]), "v");
	base..ctor(convertToProviderExpression, Expression.Lambda<Func<byte[], string>>(Expression.Condition(Expression.Equal(parameterExpression, Expression.Constant(null, typeof(object))), Expression.Constant(null, typeof(string)), Expression.Call(Expression.Field(Expression.Constant(CS$<>8__locals0, typeof(<>c__DisplayClass0_0)), FieldInfo.GetFieldFromHandle((RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/)), (MethodInfo)MethodBase.GetMethodFromHandle((RuntimeMethodHandle)/*OpCode not supported: LdMemberToken*/), parameterExpression)), new ParameterExpression[1]
	{
		parameterExpression
	}), mappingHints);
}
```

I think this is the result of three different bugs interacting:
 1) Depending on assembly list contents, we may decompile with the wrong `System.Private.CoreLib.dll`.
 2) In the presence of nullable reference types, the `ExpressionTreeTransform` may fail.
 3) In case of a failed conversion, the `ExpressionTreeTransform` may have an unexpected side-effect on the ILAst: by reusing nodes from the main ILAst in a temporary ILAst for the converted ET, it marks those nodes as stale in the main ILAst. This isn't noticed for successful conversions as then the stale nodes end up being replaced; but failed conversions it ends up being an unexpected side-effect on the ILAst, and triggers the assertion.
