### ISSUE TITLE
Feature request: Generate new-style csproj when saving code

### ISSUE THREAD

**Issue by IanKemp** [icsharpcode/ILSpy#1947]
Currently ILSpy always generates old-style (Visual Studio) csproj files when saving code. These are very large and contain a lot of cruft that is no longer needed for .NET Core projects.

It would be useful if there was an option to generate the csproj files in either the current/legacy Visual Studio format, or the current/latest .NET Core format.

**Comment by dymanoid** [comment]
@siegfriedpammer I'd be glad to help with this one. Anything I need to be aware of? Do you maybe have a general idea how you want this to work? E.g. when to choose which format, etc.

**Comment by siegfriedpammer** [comment]
Thank you for volunteering to do this!

First off, I haven't thought much about this feature yet, as we're currently more focused on getting rid of bugs, however, I can think of two different approaches (which of course, could be combined):

1) Let the user select the format by adding an entry to the Save dialog's FileFilter. Of course, some assemblies, will never work with the new project format (.NET 1.x or 2.x comes to mind), we should be able to infer the target framework and hide/disable (?) the option in that case.

2) Always use the new project format unless the version is < .NET 4.6.2, which is the first version that is fully compatible to .NET Standard 2.0.

Another thing that will be difficult and sometimes impossible is correctly detecting package references and package versions from the assembly references used.

If you have any other question, I will try to help you, however, I am currently very time-constrained, so please excuse any delays. Thank you for your understanding.

I am looking forward to your pull request!

**Comment by dymanoid** [comment]
Actually, the project format is not that restrictive regarding the target framework. You can perfectly build assemblies targeting .NET Framework 2.0 using the SDK style `csproj` format. (Is anyone using .NET 2.0 yet?) For example, I'm using the SDK style format for old Unity3D game plugins targeting .NET Framework 3.5.

However, the project file format *does* matter for the build environment (MSBuild/dotnet) being used to build the project. E.g. Visual Studio 2013 cannot build such projects.

My proposal:

- introduce an option for the project format to generate (you normally only need to change it once according to the build environment on your machine)
- set this option to the SDK style format by default (we hope that most users have at least Visual Studio 2017 or .NET Core SDK)

Regarding the package references: I don't think we should even do this. The assembly metadata has not info about which packages have been used to build an assembly. So the best we can do is *guessing* which might be very unreliable. Instead of guessing, I'd propose to generate simple `Reference` items that reference assemblies, not packages. This is what the currently generated projects contain.

What do you think?

(BTW I can help with getting rid of bugs too. You could attach the `Help wanted` label to some bugs.)

**Comment by siegfriedpammer** [comment]
Yes, your proposal sounds good, please go for it!

> BTW I can help with getting rid of bugs too. You could attach the Help wanted label to some bugs.

Thank you very much for the offer. Most of the bugs are somewhat difficult to fix, however if you are interested, you could help with:
* #1388 / #1928 this should be added to the `AsyncAwaitDecompiler`
* #1949 especially https://github.com/icsharpcode/ILSpy/issues/1949#issuecomment-612110749
* #1836 would be a nice UI feature, which should be easy to implement independently

If there are any questions, please feel free to ask.
