### ISSUE TITLE
ref locals are sometimes inlined too aggressively

### ISSUE THREAD

**Issue by hemidemisemiquaver** [icsharpcode/ILSpy#1965]
ILSpy version 5.0.2.5153
C# 7.3 / VS 2017.7 (and 7.0, and 7.1, and 7.2, and 8.0)

ILSpy decompiler seems to be disliking `ldloca` and `ldind` and simply collapses them into a reference to whatever `ldloca` was pointing to, skipping any mention of the local ref variable. (In fact, this is not really "simple", as it has do some extra logic to figure out the original variable the ref is pointing to. What I would expect it do instead is "simply" show the C# version of what is happening in IL.)

original source code (compiled with VS2019 using default Debug configuration, without specifying the langversion, using .net framework 4.8 - which defaults to C# 7.3):
```
var a = "1";
var b = "2";
ref var r = ref a;
Console.WriteLine(r);
r = ref b;
Console.WriteLine(r);
Console.ReadKey();
```
ILSpy decompiled:
```
string a = "1";
string b = "2";
Console.WriteLine(a);
Console.WriteLine(b);
Console.ReadKey();
```
IL with C#
```
	.locals init (
		[0] string a,
		[1] string b,
		[2] string& r
	)

	// (no C# code)
	IL_0000: nop
	// string value = "1";
	IL_0001: ldstr "1"
	IL_0006: stloc.0
	// string value2 = "2";
	IL_0007: ldstr "2"
	IL_000c: stloc.1
	// (no C# code)
	IL_000d: ldloca.s 0
	IL_000f: stloc.2
	IL_0010: ldloc.2
	// Console.WriteLine(value);
	IL_0011: ldind.ref
	IL_0012: call void [mscorlib]System.Console::WriteLine(string)
	// (no C# code)
	IL_0017: nop
	IL_0018: ldloca.s 1
	IL_001a: stloc.2
	IL_001b: ldloc.2
	// Console.WriteLine(value2);
	IL_001c: ldind.ref
	IL_001d: call void [mscorlib]System.Console::WriteLine(string)
	// (no C# code)
	IL_0022: nop
	// Console.ReadKey();
	IL_0023: call valuetype [mscorlib]System.ConsoleKeyInfo [mscorlib]System.Console::ReadKey()
	IL_0028: pop
```

**Comment by dgrunwald** [comment]
This is by design.
The C# compiler introduces ref locals in some cases where the user didn't write them (e.g. compound assignments), so ILSpy aggressively tries to eliminate them. This also helps producing code that works with older C# versions + is easier to read.
Note that ILSpy only does this if it's possible without changing the semantics of the code -- as soon as taking the address has side effects (such as null pointer checks or array bound checks) and there's other code in between taking the address and using it, ILSpy will generate ref locals.
