### ISSUE TITLE
Question regarding nullability property

### ISSUE THREAD

**Issue by daningalla** [icsharpcode/ILSpy#2011]
I was curious about the following implementation. `MetadataTypeDefinition` defines
```
public Nullability NullableContext { get; }
``` 

but when the `Nullability` property is implemented on `IType`, it returns hard coded `Oblivious`.

```csharp
Nullability IType.Nullability => Nullability.Oblivious;
```

Any way I can get to the true Nullability value as `MetadataTypeDefinition` is internal?

**Comment by daningalla** [comment]
And just for some context, this is type definition pulled from a generic type constraint, so I'm trying to get to:
```
public class ConstrainedAsNullableRef<T> where T : class? {}
```

**Comment by dgrunwald** [comment]
I'm not sure which type definition you are looking at -- `T` is a `MetadataTypeParameter`, not a `MetadataTypeDefinition`.
I think you're looking for the `ITypeParameter.NullabilityConstraint` property.

**Comment by dgrunwald** [comment]
Also, `NullableContext` is not the "true Nullability value" you are looking for -- instead it's related to the `[NullableContextAttribute]`, which is an optimization -- it's the most commonly used nullability within the class body, in order to minimize the number of `[NullableAttribute]` that would need to be emitted.

Type definitions themselve have no nullablility -- there's no `class MyClass? { }`.

**Comment by daningalla** [comment]
Thank you - that's it.
