### ISSUE TITLE
Wondering where to start

### ISSUE THREAD

**Issue by edkazcarlson** [icsharpcode/ILSpy#2029]
Hello, I am Edward Carlson and I am interested in helping with this project.  I have recently been in contact with Mei-chin Tsai and she mentioned you would be open to having someone help with this project.  I have some c# and assembly experience, how would you like me to proceed and is there anything specific I should start looking at?

**Comment by christophwille** [comment]
We have https://github.com/icsharpcode/ILSpy/labels/Help%20Wanted - however, quite a few of those still are a tad steep simply because a decompiler is a tad more involved than most other OSS projects.

**Comment by siegfriedpammer** [comment]
Thank you for getting in touch with us. May I ask which part of the project you would be most interested in?

**Comment by edkazcarlson** [comment]
Decorating the disassembly is the part that interests me the most, however I realize that as ChristophWille said, working with the decompiler might be harder than most oss projects, and so I am open to helping with any part of the project that needs help.

**Comment by MeiChin-Tsai** [comment]
@cshung Andrew, this is Mei-Chin. Ed Carlson is the college student looking to learn and contribute to your ReadToRun space.

**Comment by cshung** [comment]
@MeiChin-Tsai, thank you for looping me in this issue. 

Let's get started with a brief introduction so that we are all on the same page.

@MeiChin-Tsai was my former skip-level manager, we were working on the .NET runtime for Microsoft, we are located in Redmond, Washington, US.
@Siegfriedpammer and @Christophwille are the ILSpy maintainers, they are currently in Europe.

Not long ago (16th, December 2019), I [proposed](https://github.com/icsharpcode/ILSpy/issues/1864) to work on a feature for ILSpy to disassemble ReadyToRun binaries. We spent some time on it and result in the [ILSpy.ReadyToRun](https://github.com/icsharpcode/ILSpy/tree/master/ILSpy.ReadyToRun) plugin. It is functional, but it is incomplete. We are looking forward to some help to make it better.

To make it easier, I am planning to write some ramp-up documentation on how to get started. In the meantime, feel free to check out the code, build it, and run it to get acquainted. The [wiki](https://github.com/icsharpcode/ILSpy/wiki/ILSpy.ReadyToRun) should be able to get you started using the plugin to do some interesting disassembly.

**Comment by christophwille** [comment]
I am closing this generic issue - if specific questions crop up, please create new issues.
