### ISSUE TITLE
for statement detection fails

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2070]
0x06000064 IndexOf_NoLock
0x06000076 GetEnumerable_NoLock
and more
in dnspy, they are decompiled correctly

original:
``` cs
int IndexOf_NoLock(TValue item) {
	for (int i = 0; i < list.Count; i++) {
		if (list[i].GetValue_NoLock(i) == item)
			return i;
	}
	return -1;
}

internal IEnumerable<TValue> GetEnumerable_NoLock() {
	int id2 = id;
	for (int i = 0; i < list.Count; i++) {
		if (id != id2)
			throw new InvalidOperationException("List was modified");
		yield return list[i].GetValue_NoLock(i);
	}
}
```

ilspy:
``` cs
private int IndexOf_NoLock(TValue item)
{
        int num = 0;
        while (true)
        {
                if (num >= list.Count)
                {
                        return -1;
                }
                if (list[num].GetValue_NoLock(num) == item)
                {
                        break;
                }
                num++;
        }
        return num;
}

internal IEnumerable<TValue> GetEnumerable_NoLock()
{
        int id2 = id;
        int i = 0;
        while (true)
        {
                if (i >= list.Count)
                {
                        yield break;
                }
                if (id != id2)
                {
                        break;
                }
                yield return list[i].GetValue_NoLock(i);
                i++;
        }
        throw new InvalidOperationException("List was modified");
}
```

ilspy version: latest commit

[dnlib.x.dll.zip](https://github.com/icsharpcode/ILSpy/files/4935593/dnlib.x.dll.zip)

**Comment by dgrunwald** [comment]
Since ILSpy 3, the loop detection already early on decides which single branch target out of the loop becomes the loop's exit point.
Your loops have two possible exits, which both are `return` statements. One of them can be placed outside the loop, the other must be inside (otherwise we'd need a `goto`). The higher-level detection of loop condition, loop type etc. then depends on the chosen exit point (and on other stuff that happens long after loop detection).
In your examples the `PickExitPoint` heuristic should come into play, which picks one of the `return` statements as exit-point. For this it uses the order of the blocks in the IL bytecode, as normally the C# compiler emits the code in (near) syntactic order.

With `IndexOf_NoLock`, if I compile your "original", I get different IL code. That IL code then decompiles back to the original. Which compiler did you use?

With `GetEnumerable_NoLock` I can reproduce the problem; I think here the `yield return` infrastructure causes the IL offsets used by the `PickExitPoint` heuristic to be wrong.

**Comment by dgrunwald** [comment]
With the commit I just pushed, both your "original" methods can be decompiled correctly after being compiled with the compilers in our test suite (roslyn 3.7.0; legacy csc; mcs 2.6.4).
I have no idea which compiler would arrange the blocks of a `for` as they are in the assembly you provided.

**Comment by wwh1004** [comment]
sorry, it is not generated by compiler. i rewrited control flow for them using my tool like de4dot (will change the order of basic blocks), and ilspy can't decompile all methods well. because I just changed the order of the basic blocks and removed nops, so i think ilspy could also decompile them as the original code.

**Comment by dgrunwald** [comment]
When there's multiple edges leaving the loop body; only one of them can be the `break;` target and all other will need to be part of the loop.
We've found that considering the block order works really well with code compiled by the C# compiler, so it's quite intentional that the decompilation result depends on the block order.

How do you suggest we identify which edge to consider as the loop's exit point?

**Comment by wwh1004** [comment]
i don't know much about decompilation. if it is difficult, free to close this issue. 😀
