### ISSUE TITLE
TypeDeclaration.TypeKeyword returns CSharpTokenNode.Null

### ISSUE THREAD

**Issue by mcmikecreations** [icsharpcode/ILSpy#2136]
### Steps to reproduce
1. I've used a debug version of a project that I use for testing stuff. [Tests.zip](https://github.com/icsharpcode/ILSpy/files/5151519/Tests.zip)
2. Loaded a `SyntaxTree` using `SyntaxTree tree = GetDecompiler(sourceFilePath).DecompileWholeModuleAsSingleFile();` as in the [command line frontend](https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs).
3. Converted nodes to a graph using an implementation of `IAstVisitor<GraphNode>`.
4. Converted `TypeDeclaration` to string with `$"typedecl: {typeDeclaration.TypeKeyword}"`.

I expected to see something like "class", but there was nothing. Upon further inspection all `TypeDeclaration`s had `CSharpTokenNode.Null` as `TypeKeyword`.
After loading the Frontends solution provided by the ILSpy repository, I've noticed that `TypeKeyword` has 0 references, so maybe it is unused / deprecated?

### Details
* Product in use: ICSharpCode.Decompiler 6.1.0.5902 from nuget.
* Version in use: 6.1.0.5902.

**Comment by dgrunwald** [comment]
We are using the C# syntax tree originally from [NRefactory](https://github.com/icsharpcode/NRefactory/), which was designed to represent parsed C# code.
For generating C# code, it's not necessary to create instances of the tokens -- they usually don't carry any information except for their source position.
However, they can be recreated by using the `InsertMissingTokensDecorator` (which can be accessed via `TokenWriter.CreateWriterThatSetsLocationsInAST()`) -- once you ask the syntax tree to store the positions of the code as it is written out, it will create the token instances in order to store those positions.

But you don't need that to distinguish classes and structs, for that you can use `typeDeclaration.ClassType`.
