### ISSUE TITLE
redundant cast with ConversionKind.StopGCTracking

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2152]
in ClassLibrary2.Class1.Method1

ilspy output:
```
.method /* 06000003 */ public hidebysig 
	instance void Method1 () cil managed 
{
	// Method begins at RVA 0x2174
	// Code size 77 (0x4d)
	.maxstack 6
	.locals /* 11000008 */ init (
		[0] class ClassLibrary2.Class1 pinned
	)

	IL_0000: ldarg 0
	IL_0004: stloc 0
	IL_0008: ldstr "EmitPinArguments end" /* 70000024 */
	IL_000d: pop
	IL_000e: ldc.i4 0
	IL_0013: ldc.i4 100663299
	IL_0018: ldc.i4 1
	IL_001d: newarr void* /* 1B000006 */
	IL_0022: ldstr "EmitInitCall end" /* 7000004E */
	IL_0027: pop
	IL_0028: dup
	IL_0029: ldc.i4 0
	IL_002e: ldarg 0
	IL_0032: conv.i
	IL_0033: stelem.i
	IL_0034: ldstr "EmitLoadArguments end" /* 70000070 */
	IL_0039: pop
	IL_003a: ldnull
	IL_003b: ldnull
	IL_003c: call void [Zexil.DotNet.Emulation]Zexil.DotNet.Emulation.InterpreterStub::Dispatch(int32, int32, void*[], class [mscorlib]System.Type[], class [mscorlib]System.Type[]) /* 0A000019 */
	IL_0041: ldnull
	IL_0042: stloc 0
	IL_0046: ldstr "EmitUnpinArguments end" /* 7000009C */
	IL_004b: pop
	IL_004c: ret
} // end of method Class1::Method1
```
``` cs
public unsafe void Method1()
{
	fixed (Class1 @class = this)
	{
		InterpreterStub.Dispatch(0, 100663299, new void*[1]
		{
			(void*)(long)(IntPtr)(void*)this
		}, null, null);
	}
}
```

(void*)(long)(IntPtr)(void*)this should be a redundant cast, (void*)this is enough

ilspy version: 6.2.0.6088-preview1
[ClassLibrary2.zip](https://github.com/icsharpcode/ILSpy/files/5185968/ClassLibrary2.zip)

**Comment by dgrunwald** [comment]
`(void*)this` doesn't compile. Do we really need to add a code path that avoids turning `conv.i` into a cast to `IntPtr` for invalid code?

Ideally we'd turn this into something like `Unsafe.AsPointer(this)`, but there doesn't seem to be any method that allows you to get the address of a managed object. `Unsafe.AsPointer(ref this.field)` could be used to get the pointer to a class member; but I'm not aware of any method that allows you to get the address of the object itself.

In C# 9 mode we cast via `nint` instead of `IntPtr` which avoids the extra casts: `(void*)(nint)this`.

**Comment by wwh1004** [comment]
No, it is just IL i use in my emulator. I wonder why ILSpy will generate redundant cast.
