### ISSUE TITLE
Adapt the NuGet Dependencies for ICS.D

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2173]
We want to align with https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/3.8.0-3.final (and later Roslyn RTM on .NET 5.0 RTM)

* Via https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/3.8.0-3.final that means System.Collections.Immutable (>= 5.0.0-preview.8.20371.14) and System.Reflection.Metadata (>= 5.0.0-preview.8.20371.14). Humanizer remains untouched. (see also: https://github.com/dotnet/roslyn/blob/master/eng/Versions.props)

This will need to roll back https://github.com/icsharpcode/ILSpy/commit/a93ac0cc32ef284cccaa564064364cc359361123

Additional fix-up: 

* Remove System.ValueTuple https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=netcore-3.1 package reference. Seems we forgot to remove that when we went netstandard2.0-only. (why doesn't that trigger https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1685?)

**Comment by dgrunwald** [comment]
> why doesn't that trigger https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1685?

Not sure... the old 4.3.0 version we are using doesn't have the typical trick with an empty assembly (containing only type-forwarders) for netstandard.2.0. Maybe we're getting upgraded to a newer System.ValueTuple version by another dependency?
MS has these compatibility hacks precisely so that it's possible to reference a .NET standard 1.0 assembly exposing the old System.ValueTuple in a .NET standard 2.0 project without getting CS1685 compiler errors.

**Comment by christophwille** [comment]
@cshung would the dependency upgrade be a problem for the r2r functionality?

**Comment by cshung** [comment]
I don't believe upgrading `Microsoft.CodeAnalysis.CSharp.Workspaces` by itself has any impact on r2r functionality. That being said, it never hurt to test to make sure that's the case.

**Comment by christophwille** [comment]
https://github.com/dotnet/roslyn/issues/49281 3.8.0 is here with 5.0.0 dependencies.
