### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in ICSharpCode.Decompiler.dll

### ISSUE THREAD

**Issue by ChristianHoe** [icsharpcode/ILSpy#2180]
### Steps to reproduce
1.  Open Dll (can be provided)
2.  Browsing to a specific class (most other seems okay)
3.  Crash

### Error message shown

```
Eine Ausnahme vom Typ "System.StackOverflowException" wurde ausgelöst.
```

### Details
* Product in use: VIsual Studio 2019 (ILSpy)
* Version in use: e.g. 6.2.0.6124
* Opened Dll NETCoreApp, V3.1 / Linux

**Comment by siegfriedpammer** [comment]
Yes, please provide the DLL. If you prefer a private channel, please send it to siegfried.pammer@gmail.com. Thanks!

**Comment by ChristianHoe** [comment]
Send. There should be nothing important in the DLL.
PollAnswer in EventBot.Business.Commands.Raid

**Comment by siegfriedpammer** [comment]
I haven't received anything yet...

**Comment by ChristianHoe** [comment]
Send again.

**Comment by siegfriedpammer** [comment]
Still nothing... no spam... nothing... sorry. Might be GMail blocking executables as attachments...

**Comment by ChristianHoe** [comment]
https://github.com/ChristianHoe/test

**Comment by siegfriedpammer** [comment]
Downloaded, thanks!

**Comment by siegfriedpammer** [comment]
@dgrunwald the infinite recursion starts here: https://github.com/icsharpcode/ILSpy/blob/65a5af2c990530983695032d10203eecae2b6b5f/ICSharpCode.Decompiler/CSharp/TranslatedExpression.cs#L504-L514

I am not sure, what the best fix would be.

**Comment by dgrunwald** [comment]
We're starting with `{0} : {[ConstantResolveResult 0200012B System.Int32 = 0]}` and try to convert that to `Nullable<Unknown>`.
This hits the special case for converting compile-time constants to nullable types, which first converts to `Unknown` and then to `Nullable<Unknown>`.
However a conversion to `Unknown` is actually a no-op, so the function ends up calling itself infinitely.
I think we can restrict the special case to integer types in order to fix the recursion.

Note: the unknown types occur because the assembly references are missing. ILSpy needs to load referenced assemblies for proper decompilation.
