### ISSUE TITLE
Decompilation issue

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2182]
[1.zip](https://github.com/icsharpcode/ILSpy/files/5328230/1.zip)
1. 
```C#
public static bool CanBufIO
{
	get
	{
		//Discarded unreachable code: IL_0048, IL_004f
		int num;
		switch (DprName)
		{
		default:
		{
			string text; 
			string left = text; //error here
			string sChinese = "测高仪";
			if (Operators.CompareString(left, MdlLanguage.Translate(ref sChinese), false) != 0)
			{
				num = 0;
				break;
			}
.......
}
```

2. ILSpy defines 2 lables with the same name `IL_c9c2` in `视觉点胶机.MdlRun.DprRun()`
```C#
					Run.StopRuning = true;
					MdlFile.ResetFile(Run.OldFileName);
					goto end_IL_1b651;
					IL_c9c2: //same name
					while (true)
					{
						IL_c9c2: //same name
						if ((MdlCCD.CCDS[MdlCCD.CCD.Mark1CameraIndex].LightEnabled == 1 && MdlCCD.CCDS[MdlCCD.CCD.Mark1CameraIndex].LightPhoto != Cameras.LightMode.KeepClosed) ? true : false)
						{
							MdlCCD.CCDS[MdlCCD.CCD.Mark1CameraIndex].LightOpen(Cameras.LTypes.Mark1);
						}
```

3. Assert failed in `视觉点胶机.FrmDisCheck.ImageAutoSize`

4. StackOverflowException in `视觉点胶机.MdlLanguage.Translate` except `modify the stack size used by ILSpy.exe from 1MB to 16MB`
This assembly isn't obfuscated, is this method so complex or ILSpy makes some mistake?

**Comment by siegfriedpammer** [comment]
ad 4) CodeSize of `视觉点胶机.MdlLanguage.Translate` is 268703 bytes... so, yes, this method is very complex. It contains one really big string switch, I guess it's too much for ILSpy.

**Comment by xuan2261** [comment]
> ad 4) CodeSize of `视觉点胶机.MdlLanguage.Translate` is 268703 bytes... so, yes, this method is very complex. It contains one really big string switch, I guess it's too much for ILSpy.

Hello, can you just help me how to remove this default (int) when decompiler out? When the decompiler has a default (int), when running multi-thread, there will be a lack of data to be run. The way to fix is to declare a variable when running as in the image I edit below. How can I auto-edit the way I do? Thank you very much.
![Fix Loi default int](https://user-images.githubusercontent.com/17797687/95274987-760fb680-0871-11eb-918e-b8cf53466c67.PNG)
![Loi default int](https://user-images.githubusercontent.com/17797687/95274988-76a84d00-0871-11eb-8a69-688482607b5a.PNG)

**Comment by CreateAndInject** [comment]
@xuan2261 Please don't hajack my issue, open a new issue yourself, please delete or edit your reply.

@siegfriedpammer Can you delete his reply?

**Comment by xuan2261** [comment]
> @xuan2261 Please don't hijack my issue, open a new issue yourself, please delete or edit your reply.
> 
> @siegfriedpammer Can you delete his reply?

I have the same problem as you, so I always reply to your post. Thanks you very much.

**Comment by dgrunwald** [comment]
1) This is a bug in SwitchOnStringTransform (SimplifyCascadingIfStatements): the switch variable is deleted even though it's still used.

2) Interesting case. Either we need to make the labels unique somehow; or discard the inner label since the outer label is equivalent while being usable in a wider scope.

3) Here we transform
`call Size..ctor(ldflda SourceImageSize(ldloc obj), ldc.i4 571, ldc.i4 428)`
to
`stfld SourceImageSize(ldloc obj, newobj Size..ctor(ldc.i4 571, ldc.i4 428))`
However this is an invalid transformation: if `obj` is `null`, the original code throws an exception prior to the `new Size()` ctor call; whereas the transformed code will throw the exception after the ctor call.

4) In release builds of ILSpy MdlLanguage.Translate takes 21 seconds for me. A bit slow but not unexpected for such a huge method. High stack usage with large methods is normal for ILSpy, that's why we increase the stack size of ILSpy.exe.
