### ISSUE TITLE
Decompilation of fixed statements sometimes generates uncompilable code

### ISSUE THREAD

**Issue by LADSoft** [icsharpcode/ILSpy#2189]
Hi

early in the summer we had a discussion in LADSoft/OrangeC#510 about some changes you suggested for my CIL C compiler to cooperate with ILSPY a little better.   I'm finally to the point of working on that again.

One of the changes was to use the 'correct' types in fixed statements.  I implemented that and the output is much improved.   But the difficulty is in the way I implemented arrays of structured elements is as new classes that reserve a fixed amount of space for array element count of the old classes.    The classes are otherwise unrelated except by naming convention.

For arrays of scalars ilspy uses CompilerServices.Unsafe.As<array type, scalar type>(ref array instance) in the fixed statement and it works out well.   But when ilspy decompiles for arrays of structures you use a cast of the result of CompilerServices.Unsafe.AsPointer instead of As<>, and the csc doesn't like that use of a fixed statement and throws lots of errors.

I'm wondering if it would be appropriate for you to use CompilerServices.Unsafe.As<array type, structured type> in the the fixed statement, instead of AsPointer and a cast ?

I've attached a the ILASM code for a program that shows the issue.   The problem shows up in a lot of places but for example there is one in the function 'M_addtomtf_L_8_66c1428b'   look for the fixed statement involving mod.mtfhist.
	
[comp.zip](https://github.com/icsharpcode/ILSpy/files/5395072/comp.zip)

thanks

**Comment by dgrunwald** [comment]
The IL is a bit weird:
```
	IL_0000: ldsflda valuetype __anontype_b76acefe_0002 '<Module>'::mod /* 04000036 */
	IL_0005: ldflda valuetype __anontype_b76acefe_0001_array_32768 __anontype_b76acefe_0002::mtfhist /* 04000054 */
	IL_000a: conv.u
	IL_000b: stloc.1
```
`ldflda` produces a managed reference, `conv.u` converts it to an unmanaged pointer; then `stloc.1` implicitly converts it back to a managed reference (since the local is of type `valuetype __anontype_b76acefe_0001& pinned`).

Without the `conv.u`, ILSpy outputs valid code using `Unsafe.As<>`.

**Comment by dgrunwald** [comment]
ILSpy is correct with the `Unsafe.AsPointer` output signifying the non-pinning conversion due to the `conv.u`.
I think I'll fix the "uncompilable code" issue by generating the following C# for your IL:
```
fixed (__anontype_b76acefe_0001* ptr = &Unsafe.AsRef<__anontype_b76acefe_0001>(Unsafe.AsPointer(ref mod.mtfhist)))
```
That way the C# code represents the weird back-and-forth conversion between managed reference and unmanaged pointer.

**Comment by LADSoft** [comment]
thanks for your help!
