### ISSUE TITLE
keep scrollbar position when change tab

### ISSUE THREAD

**Issue by ahdung** [icsharpcode/ILSpy#2207]
version: 6.2.1.6137

after change tab, scrollbar will back to top, i hope keep it's position.

**Comment by christophwille** [comment]
It is actually more than just the scrollbar state that is lost on tab switch - region expansion isn't preserved either.

![loosingallstate](https://user-images.githubusercontent.com/344208/98078982-6638c180-1e73-11eb-8fe4-3f0a0dd6b3be.gif)

**Comment by siegfriedpammer** [comment]
This is because the whole decompilation view gets refreshed when changing tabs. The problem is that internally we only have one current language/version state. This state is modified whenever you change tabs and the state of the newly active tab is applied to the global state. Changing tabs should trigger a refresh of the tree view (iff language or version changed), but not a full decompilation cycle (which erroneously also destroys folding/scroll state).

**Comment by ahdung** [comment]
Consider don't automatically refresh the existing tabs, instead let the user refresh manually, in context menu something.
