### ISSUE TITLE
Support multi-module assemblies

### ISSUE THREAD

**Issue by KevinCathcart** [icsharpcode/ILSpy#221]
ILSpy really does not support multi-module assemblies

Admittedly the most common case is a single module assembly, which is usually self-contained, but occasionally linking to external resources. However some multimodule assemblies do exist, and currently ILSpy can only decompile the module that contains the the assembly manifest. 

Reflector shows all the modules as distinct icons in the tree view, immediately underneath the Assembly node, and alongside the resource node.

Honestly, ILSpy's behavior of not showing a module node is preferable in the common case of a single-module-assembly. However, for multi-module assemblies, the modules really should show up in the tree, to allow decompiling all of them.

**Comment by siegfriedpammer** [comment]
Ever since v5 the decompiler engine supports resolving and reading additional modules, with some fixes to ILSpy in v6.

The UI has the following features:
a) decompiling an assembly that references a module automatically loads the module(s) from the same directory as the assembly itself
b) clicking the module node in the references tree resolves the module
c) AssemblyTreeNodes that refer to a .netmodule have `(.netmodule)` added to their name (as there is no version)

The only thing that is missing would be an additional level in the tree-view that allows the user to effectively group all files/modules that belong to an assembly. This involves some work, which I don't think is worth the effort. Multi-module assemblies are very niche. From the number of issues (counting 2 including this one) that have requested this in the past 9 years, it seems that demand for this is almost non-existent.

If anyone thinks, ILSpy should add this additional level in the tree-view and/or should have even better support for multi-module assemblies, feel free to provide a pull request that adds the feature.

Thank you!
