### ISSUE TITLE
Unable to resolve System.Private.CoreLib v5.0.0

### ISSUE THREAD

**Issue by brettfo** [icsharpcode/ILSpy#2228]
### Steps to reproduce
1. Install [dotnet 5.0 SDK](https://dotnet.microsoft.com/download/dotnet/5.0).
2. Use `CSharpDecompiler` with `UniversalAssemblyResolver` to decompile a `net5.0` app that has a reference to `System.Private.CoreLib`.
3. `System.Private.CoreLib, v5.0.0` can't be found.

### Result
```
ICSharpCode.Decompiler.Metadata.AssemblyResolutionException: 'Failed to resolve assembly: 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e''
```

The error appears to come from [`UniversalAssemblyResolver::ResolveInternal()`](https://github.com/icsharpcode/ILSpy/blob/a97e7518c4cd85b476c1b6119240286256a70f5f/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs#L322).  Line 332 properly sets `framework_dirs`, but because `System.Private.CoreLib` isn't retargetable the condition on line 336 isn't hit and since its version is > 4 the condition on line 356 isn't hit.  The end result is that the file is reported as not found, even though it exists on disk in the `framework_dir` folder.

### Full repro
decompile.csproj:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!--
    Note that if this value is changed to `netcoreapp3.1` then everything works, because
    the assembly version is < 4 so `framework_dir` above is examined.
    -->
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="7.0.0.6225-preview1" />
  </ItemGroup>

</Project>
```

Program.cs

``` csharp
using System.IO;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp.OutputVisitor;
using ICSharpCode.Decompiler.Metadata;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace decompile
{
    class Program
    {
        static void Main(string[] args)
        {
            // create assembly
            var source = "public class MyMath { static void Main(string[] args) { } }";
            var syntaxTree = CSharpSyntaxTree.ParseText(source);
            var compilation = CSharpCompilation.Create("myassembly")
                .AddSyntaxTrees(syntaxTree)
                .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));
            var dllStream = new MemoryStream();
            var emitResult = compilation.Emit(peStream: dllStream);
            dllStream.Seek(0, SeekOrigin.Begin);
            var module = new PEFile("myassembly.dll", dllStream);

            // decompile
            var assemblyResolver = new UniversalAssemblyResolver("myassembly.dll", true, "net5.0");
            var settings = new DecompilerSettings(ICSharpCode.Decompiler.CSharp.LanguageVersion.Preview);
            var decompiler = new ICSharpCode.Decompiler.CSharp.CSharpDecompiler(module, assemblyResolver, settings);
            var decompiledSyntaxTree = decompiler.DecompileWholeModuleAsSingleFile();
            var decompiledCSharpCode = new StringWriter();
            var formattingOptions = FormattingOptionsFactory.CreateAllman();
            formattingOptions.IndentationString = "    ";
            new CSharpOutputVisitor(decompiledCSharpCode, formattingOptions).VisitSyntaxTree(decompiledSyntaxTree);
            var code = decompiledCSharpCode.ToString();
        }
    }
}
```

**Comment by siegfriedpammer** [comment]
```
var assemblyResolver = new UniversalAssemblyResolver("myassembly.dll", true, "net5.0");
```

The problem is this line. UAR expects the string to be of the format used by the `System.Runtime.Versioning.TargetFrameworkAttribute`. In case of .NET 5.0 this is `".NETCoreApp,Version=v5.0"`. I suggest you use the `DotNetCorePathFinderExtensions.DetectTargetFrameworkId` extension method to solve this. It will extract the TargetFrameworkAttribute.

https://github.com/icsharpcode/ILSpy/blob/a97e7518c4cd85b476c1b6119240286256a70f5f/ICSharpCode.Decompiler/Metadata/DotNetCorePathFinderExtensions.cs#L45-L48

.NET 5.0 is completely different from .NET 4.8 or earlier. The `ResolveInternal` method you mention only works with traditional .NET Framework, i.e., <= 4.8. For .NET Core and .NET >= 5, this code should be used:

https://github.com/icsharpcode/ILSpy/blob/a97e7518c4cd85b476c1b6119240286256a70f5f/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs#L202-L217

The `TargetFrameworkAttribute` still uses ".NETCoreApp" even though the official (marketing?) name is ".NET 5.0".

**Comment by brettfo** [comment]
Thank you for the detailed reply; using `".NETCoreApp,Version=v5.0"` for the `targetFramework` parameter as suggested indeed was the correct fix.
