### ISSUE TITLE
Decompiling local variables

### ISSUE THREAD

**Issue by mikt** [icsharpcode/ILSpy#2237]
Hi,
Perhaps someone could help explain or guide me in the right direction.
I was first puzzled, as to why a piece of code would get decompiled as 
```csharp
private static bool #NAb(int userLimit)
```
Until I realized, that's just how it is for private methods and variables when you don't have a pdb, which is sort of okay.
So it makes sense the decompiler has to come up with a fictive name, but #DAb is not valid c# syntax, which had me baffled.

For funzies I tried to edit this particular function, and even if I removed all the code inside it and simply return false, it wouldn't allow me to save it.

Could someone help me understand how this comes to be, and perhaps give a few pointers for where to go from here, in case I'm very set on editing this piece of code?

Full code of the function if needed:
```csharp
private static bool #NAb(int userLimit)
{
	DirectorySearcher directorySearcher = new DirectorySearcher(null, false);
	directorySearcher.SearchParameters.Filter = #T.#CAb();
	directorySearcher.SearchParameters.BaseObjectPath = new AdsPath(BackendInfo.Current.Server, #b.Get(1852));
	directorySearcher.SearchParameters.CacheResults = false;
	directorySearcher.SearchParameters.PageSize = 100;
	directorySearcher.SearchParameters.PropertiesToLoad.Add(#b.Get(1865));
	directorySearcher.SearchParameters.ReferralChasing = 0;
	directorySearcher.SearchParameters.SearchScope = 2;
	directorySearcher.SearchParameters.VirtualRoot = true;
	int num = 0;
	using (IEnumerator<AdmSearchResult> enumerator = directorySearcher.GetEnumerator())
	{
		while (enumerator.MoveNext())
		{
			bool flag = false;
			if (enumerator.Current.Properties.Contains(#b.Get(1865)))
			{
				Sid accountSid = new Sid((byte[])enumerator.Current.Properties[#b.Get(1865)].Value, 0);
				flag = #rd.Instance.#Fqc(accountSid);
			}
			if (!flag)
			{
				num++;
			}
			if (num % 10 == 0)
			{
				Thread.Sleep(0);
			}
			if (userLimit < num)
			{
				return true;
			}
		}
	}
	return false;
}
```

**Comment by siegfriedpammer** [comment]
> Until I realized, that's just how it is for private methods and variables when you don't have a pdb, which is sort of okay.
> So it makes sense the decompiler has to come up with a fictive name, but #DAb is not valid c# syntax, which had me baffled.

Usually private methods have valid names too (they were named by a developer after all and the compiler just keeps the name), unless it's a compiler-generated method or from an obfuscated assembly. This looks like an identifier from an obfuscated assembly. The decompiler has to use the name as given in the metadata in order to produce the expected output. There are tools which can reverse the name-obfuscation, however this is not a decompiler's responsibility, thus it is out of scope for ILSpy (the tool you are looking for is called a de-obfuscator).

Also, if you were to export the whole assembly as project, ILSpy will apply a transform to make identifiers compilable. In ILSpy itself, we want to keep the names as-is.

**Comment by mikt** [comment]
Thank you so much @siegfriedpammer :)

I don't suppose that when I change the code with ILspy, and press the save module, the code is actually compiled and will run?
I suppose I have to export it to a visual studio project and build it properly, or?

**Comment by siegfriedpammer** [comment]
ILSpy does not offer any on-the-fly editing capabilities. Yes, you will have to generate a project and then fix the errors until it builds.
