### ISSUE TITLE
Incorrect decompilation of branching

### ISSUE THREAD

**Issue by CollinAlpert** [icsharpcode/ILSpy#2262]
### Steps to reproduce
1. Declare boolean
2. Use it in an empty branch
3. Decompile

Code: 
![image](https://user-images.githubusercontent.com/14217185/103652971-24f08b00-4f64-11eb-8756-3ac431e2cf4f.png)
Decompiled code: 
![image](https://user-images.githubusercontent.com/14217185/103653041-3cc80f00-4f64-11eb-9e21-91965b1fe60e.png)

As you can see, the decompiled code shows the condition `0 == 0`, which would evaluate to `true`. This does not correspond with the compiled code.

### Details
* Product in use: Avalonia ILSpy 5.0 RC 2

**Comment by siegfriedpammer** [comment]
This is very similar to  https://github.com/icsharpcode/ILSpy/issues/1687 and also https://github.com/icsharpcode/ILSpy/issues/1484

**Comment by siegfriedpammer** [comment]
What makes you think the decompiled code is incorrect? Looks compilable and semantically equivalent to me. As linked in my previous comment, it is not always possible to reconstruct the exact code.

**Comment by CollinAlpert** [comment]
Right, but why not reconstruct code that would evaluate to `false`?

**Comment by fschneidereit** [comment]
It's interesting that the C# compiler is even emitting IL because the condition can never be true.

**Comment by CollinAlpert** [comment]
@fschneidereit That might be because I built in Debug and not in Release.

**Comment by dgrunwald** [comment]
ILSpy works on the control-flow graph, and will happily re-arrange the IL code in order to form high-level structures. The original IL order is mostly ignored, except for a special case that sometimes negates the `if` condition and swaps the `then` and `else` blocks.
But here you have the extra-special case where both the `then` and `else` branches of the `if` jump to the same instruction. Thus both `then` and `else` have the same IL offset, so ILSpy's reordering logic can't distinguish which way around the branch was originally.

We're not going to build any extra logic in ILSpy to track extra state just to disambiguate empty `if` statements.
