### ISSUE TITLE
Notes for .NET 5 / .NET 6

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2324]
Before we are ready to move to .NET 5 / 6, we must change the way plugins are loaded:

* Use `AssemblyLoadContext.Default` instead of plain `Assembly.Load`
* Assemblies referenced by plugins need a custom `AssemblyLoadContext.Resolving` handler

**Comment by isaiah** [comment]
How much effort is it needed?

**Comment by christophwille** [comment]
See https://github.com/icsharpcode/ILSpy/pull/2323 - this PR lays the groundwork with the exception of what Siegfried mentioned in this issue (we have a prototype, it is rather simple). The reason for not moving to multi-tfm is that (a) our unit tests target netcore31, (b) the wapproj doesn't like multi-tfm. Not because this issue is hard.

**Comment by siegfriedpammer** [comment]
Once we have moved to .NET 5 or 6, we could adapt our deployment strategy to produce a framework-dependent binary release, which is then zipped (like today).
