### ISSUE TITLE
Add new output option, "modern idl"

### ISSUE THREAD

**Issue by ChrisGuzak** [icsharpcode/ILSpy#2384]
IDL files are used to author WinRT APIs and .winmd files. The old idl format has been replaced with "Modern idl", [MIDL 3](https://docs.microsoft.com/en-us/uwp/midl-3/), by design this is very close to C#. Many windows project still use the old format and would like to upgrade for the legibility and maintenance benefits. ILSpy could be used in the conversion process by by supporting another "decompile" language "Modern IDL".

Add a new option to the "select language to decompile to" combo box "Modern IDL". Implement the idl output functionality.

![image](https://user-images.githubusercontent.com/2507280/116596512-4b528180-a8d9-11eb-92b9-bd5d4162c54c.png)

**Comment by siegfriedpammer** [comment]
This looks like to be a lot of work. I don't think the core team has the resources to implement this. However, you can easily extend ILSpy and add your own language (just like ReadyToRun does!). The "generation" part of MIDL 3 could be done similar to https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/Disassembler/ReflectionDisassembler.cs, however, would expect it to be more work and code than that because it is not just printing metadata straight from the System.Reflection.Metadata.MetadataReader.

If you need any help dealing with System.Reflection.Metadata or the ILSpy plugin API, feel free to ask!

If it were contributed and maintained by said contributor or anyone except the core team (just like ReadyToRun), we could even add it to the main distribution of ILSpy, however, I think due to its niche usage, adding it to the https://github.com/icsharpcode/ILSpy/wiki/Plugins page might be better.
