### ISSUE TITLE
Step by step instructions how to migrate Language Addin from version 6 to 7

### ISSUE THREAD

**Issue by RobertvanderHulst** [icsharpcode/ILSpy#2449]
**Is your feature request related to a problem? Please describe.**
I have tried to migrate a language add-in from version 6 to version 7 but it is not working.
I have updated the package references, I have added new methods that were added to interfaces, new parameters to the WholeProjectDecompiler and processed changes  in the BraceStyle enum.
My extension now compiles but when I copy it in the ILSpy folder it does not seem to get loaded.
Apparently there is something missing or incorrect

**Describe the solution you'd like**
It would be nice if you make breaking changes that they are documented somewhere. I looked but could not find this documentation.

**Additional context**
It would also be nice if ILSpy would log the problems why it cannot load a Language DLL.
Maybe this feature is there already but I could not find it.

**Comment by siegfriedpammer** [comment]
In general we are careful enough to honor the semantic versioning principle and not introduce breaking changes in minor revisions.
We also try to keep track of all changes between major releases, however, providing migration guides is definitely too much work.
Remember, there are only a handful of plugins and the ILSpy ecosystem is centered around the reusable decompiler library, and there is too much other work to do.

However, if you have problems with migrating your plugin and you open an issue with all the details, then I will try to help you as soon as possible. Some problems are even fixed in less than 24 hours, if time permits.

Thank you for your understanding!
