### ISSUE TITLE
Most "virtual" is decompiled to "override"

### ISSUE THREAD

**Issue by mskgroup** [icsharpcode/ILSpy#2462]
Most "virtual" is decompiled to "override"

public override void __BB_OBFUSCATOR_47()

error CS0115: "XanafiedFonctions.__BB_OBFUSCATOR_47()": No suitable method was found to rewrite

**Comment by Terrain2** [comment]
The name __BB_OBFUSCATOR_47 tells me this code was probably obfuscated. I encountered a similar issue once when i had to write IL code, and i found that if a method has the ``virtual`` keyword in front of it when disassembled to IL (idk what that's actually called), it is decompiled to an override C# method, but if it has ``newslot virtual`` it is decompiled to a virtual C# method.

The code would still run as expected, given that the base class doesn't define a virtual method with the same signature (that's what ``newslot`` is for), and i know obfuscators like messing with metadata to make it invalid and hard for decompilers. So i think this is the obfuscator messing with the metadata about the method, and a ``virtual`` IL method has no exact equivalent in C#. The closest is ``override``, which works the same, but requires that the base class defines a ``newslot virtual`` method. In IL, that's not necessary, so this method can't be decompiled to C# accurately. (at least not in a way that you can recompile it)

I'm not sure it should be decompiled to a ``virtual`` C# method (since it actually isn't), but maybe the decompiler could detect this and add a comment that it couldn't accurately decompile the method to a state where it can be recompiled.

**Comment by mskgroup** [comment]
> The name __BB_OBFUSCATOR_47 tells me this code was probably obfuscated. I encountered a similar issue once when i had to write IL code, and i found that if a method has the `virtual` keyword in front of it when disassembled to IL (idk what that's actually called), it is decompiled to an override C# method, but if it has `newslot virtual` it is decompiled to a virtual C# method.
> 
> The code would still run as expected, given that the base class doesn't define a virtual method with the same signature (that's what `newslot` is for), and i know obfuscators like messing with metadata to make it invalid and hard for decompilers. So i think this is the obfuscator messing with the metadata about the method, and a `virtual` IL method has no exact equivalent in C#. The closest is `override`, which works the same, but requires that the base class defines a `newslot virtual` method. In IL, that's not necessary, so this method can't be decompiled to C# accurately. (at least not in a way that you can recompile it)
> 
> I'm not sure it should be decompiled to a `virtual` C# method (since it actually isn't), but maybe the decompiler could detect this and add a comment that it couldn't accurately decompile the method to a state where it can be recompiled.

When I use dnspy, its decompilation is normal

**Comment by christophwille** [comment]
We do not employ a deobfuscation step prior to decompilation. This is intentional. We do not "circumvent effective techniques".

**Comment by NDSilence** [comment]
virus

**Comment by Terrain2** [comment]
> When I use dnspy, its decompilation is normal

You're right. dnSpy checks the base class and creates a ``virtual`` C# method if the base class doesn't define it, even if it is not ``newslot`` IL. This isn't correct (and neither is ILSpy's output), because the original IL doesn't represent valid C#. It's not possible to decompile that correctly, but i guess dnSpy does actually have a more convenient result for your use case.

**Comment by mskgroup** [comment]
> > 当我使用dnspy时，它的反编译是正常的
> 
> 你说得对。dnSpy 检查基类并`virtual`在基类没有定义它时创建一个C# 方法，即使它不是`newslot`IL。这不正确（ILSpy 的输出也不正确），因为原始 IL 不代表有效的 C#。不可能正确地反编译它，但我猜 dnSpy 实际上确实为您的用例提供了更方便的结果。

thanks for you
