### ISSUE TITLE
Regular expressions in search does not work properly

### ISSUE THREAD

**Issue by Georgy-Losenkov** [icsharpcode/ILSpy#2481]
### Steps to reproduce
Enter `t:/^I/` into Search

### Expected behavior
Search results are empty

### Actual behavior
Search results contain all types with name starting with letter `I`

### Comments
Search `t:/^IE/` works correctly

**Comment by siegfriedpammer** [comment]
I believe this is currently by design as the search term must be at least 4 characters long in the case of regular expressions.

https://github.com/icsharpcode/ILSpy/blob/7473ff238bd25cb193ed0d2f2638f3506ed262b8/ILSpy/Search/AbstractSearchStrategy.cs#L28

However, I agree that this does not make a lot of sense.
