### ISSUE TITLE
BAML decompilation fails for early (Longhorn-era) BAMLs

### ISSUE THREAD

**Issue by Googulator** [icsharpcode/ILSpy#2535]
It appears that in beta versions of .NET Framework 2.0 and WPF, additional BAML record types were used that never made it into the final release. As a result, Longhorn-era BAMLs fail to decompile.

### Steps to reproduce
1. Obtain a Longhorn 4xxx-era assembly with BAMLs inside (e.g. Microsoft.Windows.WCPClient.dll)
2. Load it in ILSpy
3. Browse to one of the BAML resources

### Error message shown

System.NotSupportedException: Specified method is not supported.
   at ILSpy.BamlDecompiler.Baml.BamlReader.ReadDocument(Stream str, CancellationToken token)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver, Stream stream, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.LoadBaml(AvalonEditTextOutput output, CancellationToken cancellationToken)
   at ILSpy.BamlDecompiler.BamlResourceEntryNode.<>c__DisplayClass1_2.<View>b__3()

### Details
* Product in use: ILSpy
* Version in use: 7.1
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by siegfriedpammer** [comment]
Could you please provide such an assembly? Thanks!

**Comment by Googulator** [comment]
[xaml-sidebar-desktopaurora-original.zip](https://github.com/icsharpcode/ILSpy/files/7477012/xaml-sidebar-desktopaurora-original.zip)
This was included in Longhorn build 4074, and the BAML parser in that build can decode it.

[481.zip](https://github.com/icsharpcode/ILSpy/files/7477028/481.zip)
This is also from build 4074, but it's an even older BAML format that 4074's default BAML parser actually fails to decode.

**Comment by Googulator** [comment]
[Microsoft.Windows.WCPClient.zip](https://github.com/icsharpcode/ILSpy/files/7477034/Microsoft.Windows.WCPClient.zip)
This is a complete assembly file full of such prerelease BAMLs.

**Comment by ElektroKill** [comment]
The BAML format used here appears to be very different. The `MSBAML` signature that the BamlReader is not present and instead of it a whole load of garbage is read from the BAML file. Could you perhaps provide the assemblies in which the `Parser` class lives in your examples? The class isn't present in any of the modern PresentationFramework DLLs. Ideally `PresentationFramework, Version=6.0.4030.0, Culture=neutral, PublicKeyToken=e0e73d5e60c20d3c` would be necessary as that is what is referenced in the example HelloWorld files you provided.

In all files except the `481.baml` file, a string `PreAlpha` is present which is part of the garbage read out by the BAML reader when trying to read the signature. It is likely that that string is the signature but that would mean that the way the signature is stored has been changed too.
![image](https://user-images.githubusercontent.com/37494960/140609947-94c12f36-472c-47cd-9cb2-6da5f7888194.png)

**Comment by siegfriedpammer** [comment]
> Could you perhaps provide the assemblies in which the Parser class lives in your examples?

You can find leaks of Windows Longhorn on the net. These images contain a parser which supports some of the BAMLs provided above. However, decompiling the parser is somewhat difficult, as it contains signature blobs that do not conform to any valid specification.

I am not sure yet whether this feature should be part of ILSpy. Seems it would be better to create a separate tool that supports decompiling these old BAMLs.

**Comment by christophwille** [comment]
I think this is such a fringe problem we can safely not support it.
