### ISSUE TITLE
Some C#3 restrictions are ignored and slight fail on an IEnumerable method

### ISSUE THREAD

**Issue by Sekoree** [icsharpcode/ILSpy#2539]
I tried to decompile the Assembly-CSharp of an old Unity (5.5) game (Audiosuf2) which uses .Net FX 3.5 and is limited to C#3 cause of that. Most stuff decompiled flawlessly. But for some reason it added optional method parameters which are only valid for C#4+ and a few ``ref`` keywords in methods which are C#7+. It also had an issue with ``IEnumerable<KeyValuePair<TKey,TValue>>``

Not sure if I'm allowed to share the file, but here's the code output from ILSpy which has issues and working results from dnSpy
The optional method parameters happen on both.
#### Optional Method Parameters

![image](https://user-images.githubusercontent.com/37484974/140703409-90c23ecb-10ff-4366-8772-36e5042c717a.png)

#### ``ref`` Keyword Used

ILSpy:
![image](https://user-images.githubusercontent.com/37484974/140703636-56415488-f72c-4590-8271-2707dacd2a8f.png)
dnSpy:
![image](https://user-images.githubusercontent.com/37484974/140703711-8fe7a83c-f42d-46e6-ae76-b7d34df25a08.png)

#### Issue with IEnumerable<KeyValuePair<TKey,TValue>>

ILSpy:
![image](https://user-images.githubusercontent.com/37484974/140703919-d2c5a85a-0730-4784-9be5-f0b57673254c.png)
dnSpy:
![image](https://user-images.githubusercontent.com/37484974/140703955-904c1c03-6957-42af-8b35-70fa6a720a45.png)

### Details
* Product in use: ILSpy VS 2022 extension (Preview 2)
* Version in use: ILSpy version 7.2.0.6702-preview2

**Comment by siegfriedpammer** [comment]
Problem 1) It seems that the original binary was not compiled using C# 3, but C# 4, as the optional parameter is defined *in metadata*. It might be that this is another quirk of the Mono C# compiler that it allowed optional parameters already in earlier language versions - nonetheless, this is *a bug* in the Mono C# compiler. If you want to stay close to standard C#, you should try using C# 4 with the whole codebase. You can use C# 4 with .NET Framework 3.5 as long as you do not try to use the dynamic language feature or other features that require framework support.

I see two options for us here:
1. If C# 3 is selected ignore the parameter metadata and remove the default value from the parameter declaration.
2. Just like with other features that cannot be represented differently (think generics): leave it as-is

Problem 2) As already explained above, there are some features that cannot be represented differently: ref locals are such a feature. See also https://github.com/icsharpcode/ILSpy/issues/2115#issuecomment-678629310 Since ILSpy 3.0 we take great care to *not change semantics* especially with regard to exceptions. Dereferencing a reference might result in an exception and if we reorder the instructions so that they match the pattern used for array indexing by the MS C# compiler, then we effectively change the semantics of the code. In order to represent such a difference, we use ref locals, as it could not be done otherwise. @dgrunwald do you think, we can improve this using an additional option?

Problem 3) Without the binary, it will be very difficult to fix. You can send it via a private channel: siegfried.pammer@gmail.com

**Comment by Sekoree** [comment]
I sent you an eMail with the binary (+ dependencies, just in case) and thanks for the info about 3.5 actually supporting C#4, didn't know that, it could potentially be .Net FX 4, but its detected as 3.5. The Unity DLLs how the version as 5.5 but when using another extraction tool for the entire game, it gets detected as 2017.3.0f3

**Comment by dgrunwald** [comment]
If it's a unity version from 2017 it has partial support for C# 6.
I don't think it makes sense to put effort into downgrading assemblies to older C# versions -- if it was originally compiled as C# 6, you'll need to re-compile it as C# 6.

I think the only real problem here is the finally-block.

**Comment by Sekoree** [comment]
I played around with it and it turns out it's Unity 5.5.0 after all, so it really is the .NetFX 3.5 version of C#4

**Comment by dgrunwald** [comment]
> @dgrunwald do you think, we can improve this using an additional option?

We already have an option `UseRefLocalsForAccurateOrderOfEvaluation`. But that option currently only matters within a single statement (#2050). Here we would need to move the potential exception across multiple statement, in the style of copy-propagation.
Alternatively, we would need to transform the code to `color ?? Color.White` to allow the use of a single statement.

**Comment by siegfriedpammer** [comment]
1826ac0 fixes problem 3, I don't think we can do much about the other problems. Therefore closing this.
