### ISSUE TITLE
Menu "Save Code" enable issue on changing C# version

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2550]
### Steps to reproduce
1. Drop assembly onto empty treeview
2. Check that Save Code button is enabled
3. Change C# eg from default to say C#9

### Error message shown

Save Code button gets disabled

![image](https://user-images.githubusercontent.com/765343/141848921-9704cf53-dcca-4917-b2f9-cb2ee6dcd82e.png)

If you change C# version again, issue is gone.

### Details
ILSpy version 7.2.0.6719-preview2
.NET version 4.8.3928.0

**Comment by dgrunwald** [comment]
The problem here is that (since the fix for #1504) changing the language version results in all treeview items being re-created from scratch.
This loses not only their IsExpanded state, but also makes it so that the logical focus gets lost. Thus the command bindings lose their target and end up being disabled (until the treeview gets the keyboard focus again).
