### ISSUE TITLE
msi installer, ability to choose installation directory

### ISSUE THREAD

**Issue by LaraSQP** [icsharpcode/ILSpy#2676]
The msi installer now forces itself to:

`c:\Users\someone\AppData\Local\Programs\Common\`

Please make it so that the user can choose the installation directory.

Much appreciated.

And, btw, thank you very, very much to those responsible for developing and making ILSpy available for free and open-source.

**Comment by christophwille** [comment]
This is by design - our installer is modeled after the user installer for VS Code https://code.visualstudio.com/download

The difference is that we decided to show the installation steps including the target directory - this decision was taken because given the nature of ILSpy, a completely silent installation might strike our user base as ominous or even alarming (but you can use our installer with the switch `/quiet`)
