### ISSUE TITLE
decompilation , then compile with thousands of errors, Can I get help?

### ISSUE THREAD

**Issue by lzpong** [icsharpcode/ILSpy#2685]
### Input code
down from [https://docs.microsoft.com/en-us/sysinternals/downloads/rdcman](https://docs.microsoft.com/en-us/sysinternals/downloads/rdcman)
decompilation (C#9.0),  save to rdcman project;
then Compiled with vs2019, .netframework 4.8

### Erroneous output
![image](https://user-images.githubusercontent.com/10493371/167161362-f82f91fc-a1a5-4887-86a2-a75174518fa5.png)

```c#
thousands of errors:
error CS0423
error CS0535
error CS0470
error CS0115
error CS0592

and some errors:
error CS0669
error CS0121
warning CS0465
```

### Details
* ILSpy Version 7.2.1.6856
* .Net framework Version 4.8.4488.0
* RDCMan, Version 2.90.1420.0
* Microsoft Visual Studio Community 2019  16.11.12
* windows 10 20H1 (19043.1645)

**Comment by siegfriedpammer** [comment]
1563 times CS0423 should be fixed now. The other issues remain, however.

**Comment by siegfriedpammer** [comment]
We are now down to 223 errors, some of which can be easily fixed using search and replace.
Some of the errors won't ever be fixable because some things are just forbidden in C#. For example:

* TypeLibTypeAttribute is not valid on delegates
* Properties returning ref types may only contain a get accessor

CS0121 is the only remaining issue that I think is fixable, however there is already an issue for that #1982
