### ISSUE TITLE
The multiple tabs feature works like a mess ...

### ISSUE THREAD

**Issue by cateyes99** [icsharpcode/ILSpy#2704]
### Steps to reproduce
Turned out that trying to open multiple decompiled content tabs is a mess.

First there is tab which has the decompiled content for A. When right clicking on an item B, ILSpy will focus on B first, so the current tab's content of is replaced with B's content (i.e, A is gone). Now if you choose the `Decompile to new tab` command from the popup context menu, it does decompile B to a new tab. But just ends up in 2 same tabs of B's decompiled content.
![ILSpyMultiTabsMess](https://user-images.githubusercontent.com/19678455/172510551-c36911d7-3c8c-49c0-a636-789638e63e02.gif)

To have multiple useful tabs opened, have to decompile A to a new tab first, so have two A tabs opened, then right click on B, so one of A's 2 tabs is replaced with B, then decompile B to a new tab. Now you get 3 tabs A, B, B. Now you can right click C, to get A, B, C. But if you want to open D in a new tab, have to do the same, decompile C to a new tab, thus get A, B, C, C, then click D to have A, B, C, D! what a mess.

### Details
* Product in use: ILSpy
* Version in use: 7.2.1

**Comment by siegfriedpammer** [comment]
Yes this is a known problem. Unfortunately, due to the fact that changing the selection causes a new decompilation and right click on a tree node also changes the selection, the old content will always be erased.

Do you have a any suggestion how to fix the problem without impacting users of ILSpy that don't care about multiple tabs?

Things we have already ruled out, as there cannot be any breaking changes in the UX for single-tab users:

* Clicking on a tree node must cause a new decompilation.
* Using modifier keys is not possible as these are already used to select multiple tree nodes.
* Right click on a tree node must change the selection as well so that context menu items can know their target. This is why the current workflow is unusable.

In order to fix this, we might have to refactor larger parts of SharpTreeView's input handling.

Thank you for any suggestions!

**Comment by dgrunwald** [comment]
There's a difference between focus and selection.

Note that you can press Ctrl+Up/Down to change the focused tree view item without changing the selection. (however, it seems that our theme hides the focus rectangle, so this effect is invisible unless you press Right/Left to expand/collapse the focused tree node. That's arguably a bug in the theme.).
If we make right-click do the same thing (set focus without setting the selection), we could let the context menu items act on the focused tree node instead of the selected tree node.

**Comment by siegfriedpammer** [comment]
I have just pushed a small change that delays any decompilation requests, if the right mouse button was pressed until the context menu is closed again. Can you please check, if this solves the problems for you? Also, if you detect any strange behavior involving any context menu command, please let us know. Thanks!

**Comment by cateyes99** [comment]
Hi @siegfriedpammer, I've downloaded the latest source of 702a7da2c39576a341c159e8614ee6b070ff7990 and tried out the multiple tabs feature again. Now it works much better and friendly. Thank you.
