### ISSUE TITLE
CallBuilder produces strange cast on call target, in case two very similar overloads are present

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2741]
[StrangeCast.zip](https://github.com/icsharpcode/ILSpy/files/9086809/StrangeCast.zip)

See XpoTspecInsulInfo2021:
```
public int XpoTspecInsulInfo2021Id
{
	get
	{
		return _fXpoTspecInsulInfo2021Id;
	}
	set
	{
		((PersistentBase)this).SetPropertyValue<int>("XpoTspecInsulInfo2021Id", ref _fXpoTspecInsulInfo2021Id, value);
	}
}
```
There's `((PersistentBase)this)`, but there's no such issue in the other properties defined in the same type

**Comment by siegfriedpammer** [comment]
The problem here is that there are two very similar methods defined in the base class `PersistentBase`.

```csharp
protected bool SetPropertyValue<T>(string propertyName, ref T propertyValueHolder, T newValue);
protected bool SetPropertyValue(string propertyName, ref int propertyValueHolder, int newValue);
```

The IL tells us that the generic overload should be used:

```il
IL_000d: call instance bool PersistentBase::SetPropertyValue<int32>(string, !!0&, !!0) /* 2B000081 */
```

And while it would be sufficient to specify generic type arguments to disambiguate in this case, our algorithm is not clever enough to try that combination:

https://github.com/icsharpcode/ILSpy/blob/06039f24efec4682b7979e33b1bd42b12628079c/ICSharpCode.Decompiler/CSharp/CallBuilder.cs#L991-L1031

We try the following things (in that order):
1) cast all arguments to the expected types
2) add call target, if it was optional
3) cast the target to the exact type
4) add type arguments explicitly

If steps 2/3 and 4 are swapped, then the produced code should just be:

```csharp
SetPropertyValue<int>("XpoTspecInsulInfo2021Id", ref _fXpoTspecInsulInfo2021Id, value);
```

However, I think there are many cases where this change would make the code look a lot worse... especially if the method has more than one type argument, or the type argument is a generic type with multiple levels of nesting.
Also note that there is already a `TODO` note on that issue on line 991.

**Comment by siegfriedpammer** [comment]
Accessing protected members from derived classes is perfectly fine. What do you mean?

**Comment by CreateAndInject** [comment]
@siegfriedpammer 
![image](https://user-images.githubusercontent.com/2529999/178789479-1dcf9587-63a7-4aef-8617-ebd2c16c34c8.png)
