### ISSUE TITLE
When is the next NuGet package update?

### ISSUE THREAD

**Issue by andrewcrawley** [icsharpcode/ILSpy#2742]
Apologies if an issue isn't the correct venue for this.

I'm working on improving decompiler integration for the Visual Studio debugger.  A few months back, @siegfriedpammer kindly reviewed and accepted PR #2678, which I authored as part of my team's effort to support decompilation of binaries built without symbol support.  Can you provide any guidance as to when I might see that change in a NuGet package I could consume?

Thanks!

Andrew

**Comment by christophwille** [comment]
By default, we always have the Actions artifacts (so you can pick a package and add to an internal feed), as well as our https://github.com/icsharpcode/ILSpy/packages/547741 feed (which is GH authenticated if I remember correctly, but that is GH default).

As for nuget.org - that usually happens when we cut a preview / rc / rtm build. That doesn't follow a planned schedule though. @siegfriedpammer might be able to chime in as to when that might be.

**Comment by christophwille** [comment]
Current plan - before end of July (we plan to shoot for 26th, but...).
