### ISSUE TITLE
Constant search misses properties

### ISSUE THREAD

**Issue by miloush** [icsharpcode/ILSpy#2822]
### Steps to reproduce
1. Having _PresentationFramework_ loaded, search for `FileDialogInvalidFilter` as _Constant_
2. `"FileDialogInvalidFilterIndex"` is found in `FileDialog.GetFilterExtensions()`. However, `"FileDialogInvalidFilter"` is not found in `FileDialog.Filter` property.

In fact, even searching for just `a` as _Constant_ yields more than 1000 results but suspiciously not a single property.

### Details
* Product in use: ILSpy
* Version in use: 7.2.1.6856

**Comment by siegfriedpammer** [comment]
FWIW, the current master branch lists`FileDialog.set_Filter` in the results. Of course, this could be fixed to refer to the property.

**Comment by miloush** [comment]
Cool, then I would consider it fixed. It doesn't do that for me:

![image](https://user-images.githubusercontent.com/10546952/198896167-55305cd7-aabe-49e6-9cd6-570953dd67f9.png)

**Comment by siegfriedpammer** [comment]
After a bit more testing a realized that the accessor method is only shown, iff you select "Show all types and members" (third icon in the API visibility toolbar section) and then restart ILSpy, because the change is not properly propagated to the search pane. This is fixed in my second commit.

The actual fix is in my first commit. LiteralSearchStrategy now uses `method.AccessorOwner`, if available.

Thanks for reporting this!
