### ISSUE TITLE
Provide method signature to distinguish overloaded methods

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#2862]
**Is your feature request related to a problem? Please describe.**
When trying to disassemble a single method, it's not easily possible to find overloaded methods, since the parameter types are not available in the first place, method definition only provides parameter names, which are not useful here.

**Describe the solution you'd like**
Provide a method signature that lists the individual parameter types in a C# style notation, so overloaded methods can be easily distinguished by their parameter types.

**Additional context**
See PR

**Comment by siegfriedpammer** [comment]
See https://github.com/icsharpcode/ILSpy/wiki/Getting-Started-With-ICSharpCode.Decompiler

Quoting bullet point 3:

> If you want to decompile one single member:
>
> ```csharp
> var decompiler = new CSharpDecompiler("Demo.ConsoleApp.exe", new DecompilerSettings());
> var name = new FullTypeName("Demo.ConsoleApp.Test+NestedClassTest");
> ITypeDefinition typeInfo = decompiler.TypeSystem.MainModule.Compilation.FindType(name).GetDefinition();
> var tokenOfFirstMethod = typeInfo.Methods.First().MetadataToken;
> Console.WriteLine(decompiler.DecompileAsString(tokenOfFirstMethod));
> ```

Can you explain **why** the APIs provided is not sufficient?

No... performance is not a valid argument. The `DecompilerTypeSystem` API is highly optimized/cached. If there is need for improvement, it would be much better to start fixing the problems in the existing API rather than implementing yet another layer of abstraction that needs testing, maintenance, etc. Thank you for your understanding.

**Comment by siegfriedpammer** [comment]
The above example can be simplified, if you don't want to decompile anything. You can also create a `DecompilerTypeSystem` directly and can use it in conjunction with `ReflectionDisassembler`. If you need any help with that or have any questions, I will be glad to answer those.

**Comment by tom-englert** [comment]
@siegfriedpammer that works fine, sorry for the spamming PR.

**Comment by siegfriedpammer** [comment]
No worries... Glad to hear it works for you.
