### ISSUE TITLE
MethodBodyDisassembler.ShowRawRVAOffsetAndBytes = false does not suppress all RVA comments

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#2866]
Showing RVA offsets in disassembled text makes the output hardly comparable, since these offsets frequently change. Two snapshots from the same method in different contexts always differ only by RVA.

### Steps to reproduce
1. Disassemble method when https://github.com/icsharpcode/ILSpy/blob/73cdacb6c46d7f73d54ea51b3ca750ca1ab5eaa8/ICSharpCode.Decompiler/Disassembler/MethodBodyDisassembler.cs#L64 is set to false (=default)

### Expected
No RVA offsets in output

### Actual
Every method starts with `// Method begins at RVA ...`
```
// Methods
.method public hidebysig specialname rtspecialname 
	instance void .ctor () cil managed 
{
	// Method begins at RVA 0xe957
	// Header size: 1
	// Code size: 14 (0xe)
```
### Root cause:
RVA output is not conditional:
https://github.com/icsharpcode/ILSpy/blob/73cdacb6c46d7f73d54ea51b3ca750ca1ab5eaa8/ICSharpCode.Decompiler/Disassembler/MethodBodyDisassembler.cs#L94-L97

**Comment by siegfriedpammer** [comment]
The setting is intended to toggle the following output:

![image](https://user-images.githubusercontent.com/344204/207590275-0856cffe-6813-42a0-820e-6d0b7c719fb2.png)

The header comments cannot be turned off currently, a new setting would have to be added.

However, instead of adding another setting to the disassembler, I would like to suggest the simple solution of using a regex to ignore any lines that only contain comments. Any decent diffing library should support this. For example, [DiffLib](https://www.nuget.org/packages/difflib), which we are using extensively in ILSpy. see https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler.Tests/Helpers/CodeAssert.cs#L32

Hope this helps!
