### ISSUE TITLE
[Question] How can I disable sealed class generation

### ISSUE THREAD

**Issue by drearyrainDeng** [icsharpcode/ILSpy#2918]
### From dnspy 
![image](https://user-images.githubusercontent.com/35326823/222608486-cbb10030-9ebd-4690-b2a0-c3a5bd34f794.png)

### From ILSpy
![image](https://user-images.githubusercontent.com/35326823/222608629-5bfdaf52-038f-48ec-8d84-ec8f82709c6d.png)

Is there any configuration item that can disable seal class generation?

**Comment by siegfriedpammer** [comment]
Can you please provide the assembly? Thanks!

**Comment by drearyrainDeng** [comment]
[Common.zip](https://github.com/icsharpcode/ILSpy/files/10898807/Common.zip)

@siegfriedpammer  I uploaded the version of deleting some classes. Thank you

**Comment by ElektroKill** [comment]
The issue here is caused by a, I assume maliciously placed, call instruction with a null operand present in the constructor of the display class visible when switching to IL decompilation.
![image](https://user-images.githubusercontent.com/37494960/223202595-e2e40490-8539-438d-babc-90708c904903.png)
This call instruction causes the check performed by this method to fail:
https://github.com/icsharpcode/ILSpy/blob/f801059659cdd602e5f9d5c010c968258ef09f2a/ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs#L435

Decompiling the display class constructor in C# mode leads to an exception the ILReader as a null operand is not expected.
![image](https://user-images.githubusercontent.com/37494960/223203030-798bf354-bb69-4438-b194-12029894b958.png)

Removing this instruction using a tool like dnSpy and saving the assembly back to disk leads to proper decompilation behavior.

**Comment by drearyrainDeng** [comment]
@ElektroKill  thanks for your check. In the full version, an empty function of class2 is called here. When I remove this useless call instruction with dnspy, ILSpy does not generate a sealed class. Do you know how to optimize ILSpy's code to automatically remove invalid calls like dnspy?
[Common2.zip](https://github.com/icsharpcode/ILSpy/files/10904303/Common2.zip)

**Comment by ElektroKill** [comment]
> @ElektroKill thanks for your check. In the full version, an empty function of class2 is called here. When I remove this useless call instruction with dnspy, ILSpy does not generate a sealed class. Do you know how to optimize ILSpy's code to automatically remove invalid calls like dnspy?
> [Common2.zip](https://github.com/icsharpcode/ILSpy/files/10904303/Common2.zip)

dnSpy does not remove these calls. The code responsible for translating the display classes into more readable code is just more lean on what type of code is allowed in the constructor of a display class. The reason ILSpy does not allow such instructions is for semantic correctness of the decompiled version of the code.

**Comment by siegfriedpammer** [comment]
> The reason ILSpy does not allow such instructions is for semantic correctness of the decompiled version of the code.

Exactly... I don't know for sure, but a call instruction pointing to a nil token will probably cause an InvalidProgramException at runtime anyway. Just ignoring nil tokens might be the only workaround if we still want to produce nice-looking code.

**Comment by drearyrainDeng** [comment]
Whether to ignore the "call nil" invalid instruction seems to be another problem. In Common2.zip, the class2 function called is legal, but ilspy cannot mask the seal class like dnspy (better readability)

**Comment by dgrunwald** [comment]
That call could be causing important side-effects; a decompiler should not just ignore the call because it makes the code prettier. That's a dnspy bug; the ILSpy behavior is correct.

I guess we could add a whole new feature that removes calls to empty methods to get your assembly working. But I'm not aware of any C# compiler feature adding such calls to empty methods; so we're not going to build a new feature to handle a single weird assembly.

The `ArgumentNullException` is something we should fix.

**Comment by drearyrainDeng** [comment]
> That call could be causing important side-effects; a decompiler should not just ignore the call because it makes the code prettier. That's a dnspy bug; the ILSpy behavior is correct.
> 
> I guess we could add a whole new feature that removes calls to empty methods to get your assembly working. But I'm not aware of any C# compiler feature adding such calls to empty methods; so we're not going to build a new feature to handle a single weird assembly.
> 
> The is something we should fix.`ArgumentNullException`

In other words, there is currently no feature option to delete sealed class generation (delete empty function reference) for the title problem. So I should close this problem. If someone wants to delete empty function references, it's better to reopen a feature request. Thanks all!
