### ISSUE TITLE
TopologicalSort stack overflow when decompiling long method

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#3075]
The following method uses recursion instead of iteration for the call to `Visit`:
https://github.com/icsharpcode/ILSpy/blob/bd82b945eadd0213c735d27ab88d6344f74876fe/ICSharpCode.Decompiler/IL/Instructions/BlockContainer.cs#L277

This will stack overflow when decompiling the following property:
https://github.com/microsoft/fluentui-blazor/blob/9d092562af1570269c62be9a99b6e7e9a7470c87/src/Assets/FluentUI.Icons/Icons/Icons.cs#L14

The property has the following general structure:

```
public static IEnumerable<IconInfo> AllIcons
{
    get
    {
        yield return new IconInfo { Name = "Accessibility", Variant = IconVariant.Filled, Size = IconSize.Size16 };
        yield return new IconInfo { Name = "Accessibility", Variant = IconVariant.Regular, Size = IconSize.Size16 };
        // ~14500 more 'yield return' lines 
    }
}
```

**Comment by dgrunwald** [comment]
Lots of the decompiler uses recursive algorithms. While `TopologicalSort` is easy enough to convert to an explicit stack; there are just too many other recursive methods; it's not reasonable to convert all of these (especially since many of them are more complicated than `TopologicalSort`.
The method in your assembly ends up having a dominator tree that has 15k levels, so this affects not just the initial recursion over all blocks; but also all following dominator tree traversals.

Can you run the decompiler on a larger stack instead? (e.g. using the `new Thread` constructor overload that takes an explicit stack size)

ILSpy.exe does not crash on your example, as we use `editbin.exe` to re-configure the default stack size to 16 MB. (However, ILSpy is really slow on your example, taking around ~30 minutes. We're working on a fix for that.)

**Comment by siegfriedpammer** [comment]
Decompiling `class Microsoft.Fast.Components.FluentUI.Icons` on a

	AMD Ryzen 7 3700X 8-Core Processor 

	Base speed:	3,60 GHz
	Sockets:	1
	Cores:	8
	Logical processors:	16
	Virtualization:	Enabled
	L1 cache:	512 KB
	L2 cache:	4,0 MB
	L3 cache:	32,0 MB

yields the following results for various optimizations we performed:

using commit | time (avg of 10 runs) | % of original time
-------------|-----------------------|-----------------------
a9eccdb654674f83513d801c5e2806b255804854 | 587,6s | 100,00%
0a2037ae1f938b28fbb720e6c2006570d95c89bc | 51,2s | 8,71%
09691bd27e2ec27789eb651158a5cf4341bdb418 | 47,1s | 8,02%
cef99dc1403406306477659a5ebac44ff977113e | 38,5s | 6,55%
ee160b4e2a45c0efc3059ebd671462a4ac9618ba | 25,7s | 4,37%
5a5be026d0a42a8c845e2991700a9cdf05d30717 | 25s | 4,25%

I think there's not much we can do (for now) to improve this specific case, without making the decompiler slower in the general case.

**Comment by sharwell** [comment]
@siegfriedpammer those are some impressive gains!
