### ISSUE TITLE
Unable to decompile F# compiled application

### ISSUE THREAD

**Issue by tbayart** [icsharpcode/ILSpy#3109]
Hi,

I'm looking to convert some F# code to C#.
The application is open sourced on github here : https://github.com/rfvgyhn/min-ed-launcher

### Steps to reproduce
1. Retrieve the source code
2. Compile the source code
3. Try to decompile executable in ILSpy

### Error message shown
ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.

### Details
* Product in use: ILSpy
* Version in use: e.g. 8.1.1.7464

**Comment by siegfriedpammer** [comment]
If this is a modern .NET application the exe bootstrapper does not contain managed code. If the application is called `ILSpy.exe` there is also a `ILSpy.dll`which contains the managed code.

Please note that it is not advised to use ILSpy for code conversion purposes because different languages use different patterns and code generation, which may not be easily represented in C#.

Especially things like VB's `On Error Resume Next` lead to horrible unmaintainable C# code. F# is problematic because it uses a lot of extra compiler-generated types, which are not recognized by the decompiler and not transformed to the equivalent C# features, if at all possible.

**Comment by tbayart** [comment]
Damn it, i feel dumb.
I didn't pay attention to both exe and dll generated.
As you say, the exe is only the bootstrapper, the IL code is in the dll.

Please note that attempt is motivated by curiosity, not for conversion purpose.
I'm not a F# afficionado and i wanted to understand better the code here which have barely no comment.
