### ISSUE TITLE
NullGuard messes up decompilation of async methods

### ISSUE THREAD

**Issue by JKamsker** [icsharpcode/ILSpy#3156]
### Steps to reproduce
Clone and build https://github.com/JKamsker/NullGuardDemo

With nullguard:
![grafik](https://github.com/JKamsker/NullGuardDemo/assets/11245306/1a8f6de4-c39e-4c7d-9878-13ddddae604a)

Without:
![grafik](https://github.com/JKamsker/NullGuardDemo/assets/11245306/9ee8b52b-1537-45dd-8489-01aa93a87768)

### Details
* ILSpy version 8.2.0.7535
* .NET version 6.0.25-servicing.23519.12+492abbeef0d8a6ea902ac8f90ed339c7b1d18bf4
* Used [Fody.NullGuard](https://github.com/Fody/NullGuard)

**Comment by siegfriedpammer** [comment]
This is not a bug.

Fody modifies the IL and in this case introduces new variables and even branches, which alters the async/await state-machine in a way it's no longer recognized by the decompiler.

![image](https://github.com/user-attachments/assets/d2bdf307-ff8e-4784-b573-076c1dc1fd90)

I think it is not possible for ILSpy to support all possible post-processing tools that alter the IL after the compiler: just like we do not fully support assemblies post-processed by obfuscators, which alter the IL in order to make it harder to reconstruct, we also don't want to support third-party IL rewriting tools that alter the behavior. If there is huge interest from the community in supporting a few IL rewriting tools, contributions are generally welcome, however, the core team doesn't plan on actively maintaining/supporting them - all maintenance would have to be provided by the community.
