### ISSUE TITLE
provide  msi for machine install  (machine scope)

### ISSUE THREAD

**Issue by John0King** [icsharpcode/ILSpy#3157]
**Is your feature request related to a problem? Please describe.**

current ILSPY's mis installer will not allow choose the installer dir and simply put the binary on system drive( `C:` ).

unlike  vs code,  vs code provider both installer for both  user scope and machine scope 
 you can install vscode machine wide installer with command 
`winget install vscode  --scope machine`

**Describe the solution you'd like**

please provider a msi binary for system install,  or allow  user to choose  installer directory.

**Additional context**
 
 relate #2676

**Comment by reureu** [comment]
As a workaround, you can call
`msiexec /i <ILSpyPackageFile.msi> ALLUSERS=1 INSTALLDIR="C:\Program Files\ILSpy"`
from an elevated command prompt.

**Comment by christophwille** [comment]
@John0King would that be an OK solution (if of course documented properly)?

**Comment by reureu** [comment]
@John0King 

Useless to say, `<ILSpyPackageFile.msi>` was a placeholder for the MSI-filename in my previous post.

If msiexec displays its help box, it's because it hasn't been called properly. If that's the case, please post the exact command you're using.

Here is what I see right just after launching the command:
![3157_workaround](https://github.com/icsharpcode/ILSpy/assets/47881315/7d423207-163b-4ac0-9ed9-6773cdcf0517)

This is just a standard mechanism in MSI. You call msiexec, say you want to install a package, point it to the MSI file, and pass some public properties.

However, as the MSI package has not been designed for local machine installation, there are some caveats:
* If you don't run this command from an elevated command prompt, it won't be able to elevate before it executes its installation sequence.
* You'll need to specify the INSTALLDIR again when deinstalling, otherwise, MSI won't erase the files.

As I said, it's a workaround, not the solution.

**Comment by John0King** [comment]
```
 msiexec /i "C:\Users\ABlue\Downloads\ILSpy_Installer_8.2.0.7535-x64.msi" ALLUSERS=1 INSTALLDIR="D:\Program Files\ILSpy"
```

![image](https://github.com/icsharpcode/ILSpy/assets/13639146/1752a018-962a-4e24-8240-95931b7df04f)

![image](https://github.com/icsharpcode/ILSpy/assets/13639146/35e3778c-0570-4dc5-8784-a23224289ad6)

**Comment by reureu** [comment]
@John0King ,
I'm under the impression that the properties you've specified cannot be parsed properly for some reason.

If I try this:
`msiexec /i ILSpy_Installer_8.2.0.7535-x64.msi ALLUSERS=1 INSTALLDIR=C:\Program Files\ILSpy`
then I see the same as you. It's because the quotation marks are missing for the INSTALLDIR I have specified.

What delimiter do you normally use in Chinese editions of Windows to specify long paths or paths with a space?
Or is the backslash used as folder delimiter in these editions?

Can you try this?
`msiexec /i <ILSpyPackageFile.msi> ALLUSERS=1 INSTALLDIR="D:\ILSpy"`

**Comment by reureu** [comment]
@John0King ,

Gosh! I hadn't even paid attention to your Powershell prompt!
It's not exactly a bug of Powershell. It's merely due to the way parameters are passed to a msiexec in Powershell.
Others have been confronted to that.
See here https://stackoverflow.com/questions/45223031/powershell-call-msi-with-arguments

If I really had to use Powershell to launch msiexec, I would go for
``msiexec /i ILSpy_Installer_8.2.0.7535-x64.msi ALLUSERS=1 INSTALLDIR=`"C:\Program Files\ILSpy`"``

See the backtick in front of each double quote? It is there to pass the double quotes to msiexec.

**Comment by christophwille** [comment]
Closing as we do not plan to provide (yet another) installation option when a workaround exists.
