### ISSUE TITLE
Right panel shows old info in case all is deleted in the left-hand tree

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3293]
### Steps to reproduce
1. Delete all assemblies
2. rihgt panel show old info
3. 

### Error message shown

eg:

![image](https://github.com/user-attachments/assets/82ab0c80-916e-422c-a8b0-c0fc6a3bda89)

```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```
### Details
* ILSpy version 9.0.0.7785-preview2+c1a42ccf7205f41d9ba3988926162feb6e57ca98
.NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

**Comment by siegfriedpammer** [comment]
The problem seems to be that the last tab is closed. This should not be the case. Previously the last tab was uncloseable.

**Comment by christophwille** [comment]
By previously you mean pre- #3274?

**Comment by greenozon** [comment]
added video show


https://github.com/user-attachments/assets/4f2ad40d-3801-4419-85f1-290d1d69dba3

**Comment by siegfriedpammer** [comment]
> By previously you mean pre- #3274?

Yes, our latest official release shows the following, if the assembly list is empty:

![image](https://github.com/user-attachments/assets/abda4c79-d8ef-4fa2-a9ea-ecdf2ce75efc)

There is a tab "New tab" with no content. From @greenozon's first screenshot, we can see that in the current master, there can be zero open tabs, which is not desired, because ILSpy is essentially an SDI application, with the possibility to view multiple documents. if necessary.

**Comment by christophwille** [comment]
@tom-englert

**Comment by siegfriedpammer** [comment]
@tom-englert I can still reproduce this using the latest master (ILSpy version 9.0.0.7802-preview2+7f46aab34493d01edf9801df6b86fc14d5c8ae62):

1) create/open non-empty assembly list
2) ctrl+a all tree nodes
3) hit delete
4) observe that the decompilation view is reloading/still showing old info

I also noticed that switching the current assembly list while a decompilation is in progress, it's not cancelled. When switching tree nodes the old decompilation is cancelled. I would expect the same to happen, when switching the assembly list mid-progress.

I will try to look into this, but ever since the refactoring I am no longer sure how the code is supposed to work/be organized, so actually fixing stuff is a lot harder. The code is organized better, but I still have to get used to it.

**Comment by tom-englert** [comment]
@siegfriedpammer I'll have a look, too
