### ISSUE TITLE
"Save Code..." initiates re-decompilation

### ISSUE THREAD

**Issue by YellowAfterlife** [icsharpcode/ILSpy#482]
... even if class was already decompiled and is being displayed in the right section.

... which is kind of a shame if you have already spent some minutes waiting to see the class in first place.

**Comment by dgrunwald** [comment]
I'm closing this as by-design; because the save-to-disk decompilation now can produce slightly different code from the normal decompilation (due to escaping invalid identifiers).

However, hopefully the new decompiler engine (which just landed on master) solves the "spend some minutes waiting" problem by being faster.
