### ISSUE TITLE
Translate marshal(...) attributes into MarshalAs(UnmanagedType) instead of MarshalAs(Int16)

### ISSUE THREAD

**Issue by poizan42** [icsharpcode/ILSpy#491]
Currently `mashal(...)` attributes are translated into `MarshalAs(Int16)` for both C# and VB. You need to actually look at the metadata for `System.Runtime.InteropServices.UnmanagedType` to figure out what the number means as the enum values aren't documented by Microsoft. Translating it into the proper `MarshalAs(UnmanagedType)` ctor instead would make it easier to read.

**Comment by dgrunwald** [comment]
I cannot reproduce this. `marshal()` is a special IL-level attribute; and as far as I can tell, we've been translating it to the enum reference ever since we had support for P/Invoke declarations.

Here's the current [test case](https://github.com/icsharpcode/ILSpy/blob/42a4a4de10ba29db32175c47ed59def83a841927/ICSharpCode.Decompiler.Tests/TestCases/Pretty/PInvoke.cs).

**Comment by poizan42** [comment]
Well, clearly it didn't work at some point, but I can't reproduce it on 2.4.0.1963, so I'm closing this.
