### ISSUE TITLE
ILSpy crashes when deleting more than a screenful of assemblies

### ISSUE THREAD

**Issue by 0xd4d** [icsharpcode/ILSpy#555]
- Add enough assemblies to ILSpy treeview
- Make the window smaller so some of the assemblies are not shown
- Select assembly # 2 and press Shift+END to mark the remaining (leaving asm # 1 unselected)
- Press Delete
- A really big messagebox should pop up displaying the exception

There are other ways of deleting more than a screenful of assemblies, but it doesn't always crash. Here's a patch that fixes it for me:

```diff
--- a/ILSpy/MainWindow.xaml
+++ b/ILSpy/MainWindow.xaml
@@ -117,6 +117,7 @@
 				ShowRoot="False"
 				AllowDropOrder="True"
 				AllowDrop="True"
+				VirtualizingStackPanel.IsVirtualizing="false"
 				BorderThickness="0,1,1,1" Visibility="Visible" />
 			<GridSplitter
 				Grid.ZIndex="1"
```

**Comment by weltkante** [comment]
This doesn't fix the bug, it just hides it, by changing the mode of operation of the tree.

I've debugged a bit and the real problem is that `SharpTreeView.flattener_CollectionChanged` calls `FocusNode((SharpTreeNode)SelectedItem)` before the tree is updated. FocusNode forces a layout and causing items to be rendered which are no longer in the tree but haven't yet been removed from the UI.

This happens because `flattener_CollectionChanged` subscribes in a list changed event which also is used to update the tree view content. `flattener_CollectionChanged` subscribed first so it will be invoked before the callback updating the UI.

A better fix probably would be to delay operations relying on updated UI a moment via `Dispatcher.BeginInvoke` so other event listeners also had a chance to run.
