### ISSUE TITLE
Syntax Error In Decompiled Code

### ISSUE THREAD

**Issue by tomspilman** [icsharpcode/ILSpy#571]
So if we run the following function from Mono's mscorlib thru ILSpy's decompiler:

https://github.com/mono/mono/blob/mono-3-2/mcs/class/corlib/System.IO/StreamWriter.cs#L497

```
public override Task WriteLineAsync ()
{
    CheckState ();

    DecoupledTask res;
    async_task = res = new DecoupledTask (WriteAsyncCore (CoreNewLine, 0, CoreNewLine.Length));
    return res.Task;
}
```

ILSpy returns the following code:

```
public override Task WriteLineAsync()
{
    this.CheckState();
    return (this.async_task = new DecoupledTask(this.WriteAsyncCore(this.CoreNewLine, 0, this.CoreNewLine.Length))).Task;
}
```

The problem here is that this is invalid C# syntax.  `Task` is a getter on `DecoupledTask` and not on `async_task` which is a `IDecoupledTask`.

**Comment by tomspilman** [comment]
Note for now we've worked around this by setting `DecompilerSettings.MakeAssignmentExpressions` to false...  but this makes the code much more verbose.

Ideally `MakeAssignmentExpressions` would detect the case where the assigned types are not the same and avoid the shortcut.

**Comment by siegfriedpammer** [comment]
I tried reproducing this issue, but I couldn't find a binary containing that exact version of `WriteLineAsync`. I know I am very late on this, but do you have a link to the binary? I will try to replicate it, using similar code, but I fear that it depends on the compiler version used.

**Comment by tomspilman** [comment]
@siegfriedpammer - Here is an old Mono mscorlib.dll that has the offending `StreamWriter.WriteLineAsync()` implementation.

 https://app.box.com/s/x19qsezqiybxtzokwy7dv3agd74c8qeg

That said we're looking to stop using ILSpy all together.  Primarily this is because ILSpy is not super fast and it is the main bottleneck for us as we're decompiling 1000s of classes.  Second it is because of errors like this which make ILSpy decompiled code sometimes fail in weird ways.

In the end the generated code is not always super readable anyway, so dealing with more `goto`s and lack of nice loops and stuff is ok.

**Comment by siegfriedpammer** [comment]
Thanks for getting back to me!

If you don't mind me asking: What exactly are you using ILSpy for? Would you care to post some cases where you see performance issues? Have you tried the new decompiler?

**Comment by tomspilman** [comment]
> What exactly are you using ILSpy for?

We use it in a transpiler converting C# assemblies into C++ code to run C# games on consoles.  The ILSpy decompiler was used to generate nicer C++ code and give us nicer high level blocks to work with.

The generation of the code can take anywhere from 2 minutes to 30 seconds depending on the complexity of the C# executable we're converting.  In generally pretty fast, but over 50% of that time is tied up in the decompiler step.  We're already doing all the obvious things to get more performance... fully threaded, only writing code that changed, etc.

Simply removing the decompiler and working with raw IL will give us a huge performance boost in code generation.

> Have you tried the new decompiler?

I haven't mostly because i am so busy with other work.  

Still i also dread the change... every time i have updated the decompiler in the past something is fixed and something new is broken.  Most often the broken code compiles... but generates bad results... causing bugs you cannot find until you test every inch of your game.

So i basically stopped updating a year or two ago for that reason as it seemed better to stick to the devil you know.

**Comment by siegfriedpammer** [comment]
The new decompiler produces:

	public override Task WriteLineAsync(char value)
	{
		this.CheckState();
		return ((DecoupledTask)(this.async_task = new DecoupledTask(this.WriteLineAsyncCore(value)))).Task;
	}

which seems correct, as it adds the necessary parentheses and casts.

I very well understand that you are very hesitant to update, because of very bad testing on our end. In the new decompiler we changed that and are doing our best to add tests for every special case and we are doing correctness and pretty tests, as well as roundtrip tests. The new decompiler also fixes many correctness issues and architectural deficits that were keeping us from being able to fix these issues.

For more information see https://github.com/icsharpcode/ILSpy/wiki/newdecompiler (note: it's already on `master`)

**Comment by dgrunwald** [comment]
Wait, were you decompiling IL all the way back to C# just to re-compile to C++?

Or did you use our intermediate representation (ILAst)? Your use case sounds like a good fit for the ILAst -- it gives you high-level control flow and expression-oriented code, but is otherwise much closer to IL than C# (especially with the new decompiler). It should also be easier to consume as an input language than C#.
And if you're not going via C#, you can disable most of the decompiler transforms (which is good both for performance and bug count).

**Comment by tomspilman** [comment]
> Or did you use our intermediate representation (ILAst)?

Yes I am using ILAst.  Reminds me that some of the issues i ran into were problems where `ILSpy` did fixups in the C# code printing side of things that i would have expected in the `ILAst` like some non-trival casts.

> you can disable most of the decompiler transforms 

Yeah that is how i got things working to the level i have so far.  Still some things it does just don't work and i have to hack around it.
