### ISSUE TITLE
Abnormally high resource usage on a particular method

### ISSUE THREAD

**Issue by YellowAfterlife** [icsharpcode/ILSpy#631]
If you take Relogic' Terraria' dedicated server software,
http://forums.terraria.org/index.php?threads/terraria-1-3-0-6-is-live.27035/
(linked in the beginning of the post)
and order ILSpy to decompile `Terraria.NPC`' `AI` method, something interesting happens:
- On a 32-bit system the application briefly runs out of memory (2GB limit) and backs off.
- On a 64-bit system the application does not back off, but takes suspiciously long. By "suspiciously long" I mean that when ran on an average 4-core (3.0GHz) system with 8GB RAM, the operation did not finish in 70 minutes.

For comparison, the same method from the previous major version of the game (1.2.4.1) would finish in just some 5-6 minutes.
Had the particular method grown _that_ much between versions, or is there some pitfall to this?

**Comment by weltkante** [comment]
v1241 had 79k instructions, v1306 has 136k instructions (the size of the function doubled) and the number of variables grew from 1400 to 3000 (also doubled).

So, yes, the method *did* grow *that* much between versions.

It probably would need careful optimizations of the involved algorithms to be able to decompile that one. Since it took you more than 70 minutes that indicates that some non-linear algorithms are used during decompilation, but I didn't take a closer look since my 4gb machine grinds to a halt when trying to debug the decompiler on that method ;-)

**Comment by Chicken-Bones** [comment]
I'm guessing the reason it takes so long is that the program runs out of RAM and the system starts swapping it to disk.

A heap dump at 3GB yields the following
http://puu.sh/j9WA0/c58fb0739b.png
http://puu.sh/j9WBv/14e9bbf5fc.png

I haven't yet looked at the ILSpy source to determine if there's an obvious way to optimise this, but it would appear that there are a large number of copies of the variables sitting in VariablesBefore fields.

**Comment by weltkante** [comment]
These arrays come from the control flow analysis in [ILAstBuilder.cs](https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ILAst/ILAstBuilder.cs) at the [StackAnalysis](https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ILAst/ILAstBuilder.cs#L227) function which has to examine all 136k instructions x 3k variables per instruction, so it's somewhat expected that this needs a lot of memory for this particular method.

Though, taking a look at it, it would probably profit from switching to the [ImmutableCollections nuget library](https://www.nuget.org/packages/System.Collections.Immutable) instead of using raw arrays, so it can share nodes which don't change between instructions.

One obvious example would be at [line 400](https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ILAst/ILAstBuilder.cs#L400) where it calculates unions based on arrays and allocates a new array for each one.

Using [ImmutableHashSet](https://msdn.microsoft.com/en-us/library/dn467171%28v=vs.111%29.aspx) could probably help to reduce allocations by sharing those nodes of the hashset which don't change. There are probably more opportunities to share data, I didn't look too closely at it.

**Comment by dgrunwald** [comment]
Good news: In the new decompiler, the first few steps of the decompilation pipeline seem to handle this huge method just fine now.
It doesn't take too long to get through the early passes, and only takes about 400 MB of memory. But then there seems to be some performance problem in the block transform stage. It doesn't seem to be making any progress even if I let it run for 10+ minutes. I'll have to debug this further...

**Comment by dgrunwald** [comment]
A release build fix the fix decompiles the `AI()` method in 45 seconds.

There still seem to be a few unnecessarily quadratic algorithms making up the majority of this runtime.

**Comment by siegfriedpammer** [comment]
The `AI()` method decompiles in 14 seconds on my notebook after fixing a performance bottle-neck in `AssignVariableNames`.
