### ISSUE TITLE
Add an "Open in ILSpy" option in the Call Stack window? 

### ISSUE THREAD

**Issue by kiewic** [icsharpcode/ILSpy#660]
It would be awesome if I could open ILSpy from a method call in the _Call Stack_ window during debugging, similar to the _Open in ILSpy_ in the _References_ list.

Moreover, ILSpy could go directly to the definition of the method selected in the call stack, or show results for types matching with the method name.

**Comment by donid** [comment]
I have not found a way to retrieve the currently selected row in the "Call Stack" window, but as workaround we can use the active frame (the one with the curved arrow in the screenshot). 
I could provide a PR for a feature that navigates to the method of the currently active frame - see screenshot.

![openstackframeinilspy](https://cloud.githubusercontent.com/assets/6991562/14664694/6b087678-06cd-11e6-90eb-68f873a4a61c.jpg)

**Comment by donid** [comment]
So, nobody interested in this feature? I was hoping for some comments about the usability of my proposed workaround and maybe the menu-caption that I have chosen.

BTW: this issue seems to be missing the "VS Extension" label.

**Comment by siegfriedpammer** [comment]
I tried to the feature, but I could not find the menu item in the call stack context menu.

**Comment by donid** [comment]
@siegfriedpammer: I don' quite understand your comment - the feature currently only exists in a build on my local machine. I presented the screenshot to receive comments about the naming and position of the planned menu item. In addition I hoped for comments about my planned workaround  to use the "active frame" instead of the "selected frame" - I think it is not possible to retrieve the "selected frame" through VS-extensibility (@bbi-yoyo mentioned his still unanswered StackOverflow-posting in #697). And I thought maybe @kiewic would comment if this proposal meets his needs.

**Comment by bbi-yoyo** [comment]
I do like the idea of this feature, but would certainly prefer to be able to go to any stack frame. If you can figure out how to get the code element for a stack frame you can look at my implementation of "Open Code in ILSpy" (CodeElementXmlDocKeyProvider.cs) to see how to navigate straight to the item.

Hmm, thinking about that a bit -- VS is only going to give you a code element for source code. If you want to navigate to a stack frame for which you don't have source (assuming you can get info on the stack frame in the first place) you will likely need to figure out the xml doc key generation yourself.

Also note that for stack frames for which you *do* have source, you can double-click the stack frame to get to the source, then right-click in the source code and use the new Open Code in ILSpy context menu item. Not as direct as going from the stack trace itself, but a decent workaround.

**Comment by donid** [comment]
You can go to any stack frame, but you have to remember to make it "active" by double-clicking it.

My prototype doesn't use CodeModel at all - it uses [EnvDTE.StackFrame](https://msdn.microsoft.com/en-us/library/envdte.stackframe.aspx) like this:
`EnvDTE.StackFrame currentStackFrame = debugger.CurrentStackFrame;`

**Comment by bbi-yoyo** [comment]
Oh, cool, I see. Are you able to generate an xml doc key from the stack frame in order to navigate to the item? If you look at CodeElementXmlDocKeyProvider you'll see just how many hoops I had to jump through in order to handle overloads and generics correctly.

**Comment by siegfriedpammer** [comment]
ah... OK... now I understand. I think this is a good "workaround" until we have full integration into Visual Studio.

**Comment by donid** [comment]
Sorry for the delayed response, but I took a deep dive into VS-extensibility. My prototype basically used EnvDTE.StackFrame.FunctionName and added "navigateTo", which works in many cases (if there are no generics and overloads involved). After reading @bbi-yoyo 's comment, I realized that a StackFrame provides much less information than a CodeElement. We basically get the current method signature and programming language as string - it is even missing the ref/out modifiers. To retrieve ref/out information I would have to use IDebugStackFrame2 which would require to copy 400+ lines of decompiled internal code (IDebuggerInternal) or about the same amount of code to keep track of the current stackframe via monitoring the IDebugEventCallback2-events. These steps would help to determine the correct overload regarding the parameters. When generics are involved, it gets even worse. Since the signatures are depending on the current programming language, I would need a parser that is able to parse C#, VB and maybe F# method-signatures to split them into the parts I need to create an xmldoc-key... (even Roslyn doesn't handle F#)
Furthermore, I am using exclusively VS2015U2 so I can't guarantee that above mentioned mechanism will work in all VS versions that are currently supported by ILSpy.

So, anyone cares to comment? (Especially @siegfriedpammer  and @bbi-yoyo)

**Comment by bbi-yoyo** [comment]
I wonder if it would make sense to do something on the ILSpy end (instead of in the add-in), for example if "navigateTo" is ambiguous then pop up a dialog and get the user to choose which overload to look at. On the other hand I'd expect all the overloads to be close together in the target assembly, so navigating to the first one and leaving it up to the user to look around if needed is probably fine.

Or perhaps navigateTo could be a little more flexible in the face of an ambiguous match, for example allowing you to match based on parameter count even if the actual parameter types don't quite line up -- basically do some sort of "closest match" rather than the current behaviour of requiring an exact match or falling back on the first name match.

**Comment by siegfriedpammer** [comment]
This is now built into Visual Studio 16.5 via https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#decompilation-extraction
