### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by exyi** [icsharpcode/ILSpy#665]
I have spent lot of time in ILSpy last week and I'm really missing the option to set the dark theme.

**Comment by LPayton314** [comment]
Agreed, theming options would be a welcome addition

**Comment by AraHaan** [comment]
I dont care about theming however I do admit it would be nice if it can save Managed C++ .Net Assemblies. So that way it be easier on my tons of C# projects on my quest to translate the crap from Japanese to English. Which is a pain in the ass to do as it requires a lot of time. At least the pro to ILSpy is that I do not have to remake the stuff from scratch. However I hate having to find a way to fix the code just to get the stuff to compile. Not only that but I do not have ``PmdForm.cs`` because it failed to ``read it`` but oddly it did read everything else. I hate having to try to generate that one manually.

**Comment by webmasterMeyers** [comment]
+1 A dark theme would be awesome

**Comment by AraHaan** [comment]
Ok, well reading back. I should have worded it ``I dont mind about theming however ...``

**Comment by benda** [comment]
Hi, I'm interested in working on this issue, can it be assigned to me ? Is this issue still needed / wanted? Just planning on adding a dropdown to the Options dialog in the "Display" tab to toggle between standard and dark themes.

**Comment by christophwille** [comment]
For the WPF client, yes, feel free to work on this (no one is working on that atm).

**Comment by benda** [comment]
One thing that complicates this is that you are manually drawing the tree view items (SharpTreeViewItem) - so in order to style that we'd have to add style support to the ICSharpCode.TreeView project and do that all in code which is not standard practice in the WPF world - is that OK? Not sure why that project exists really, seems like a standard tree view would work fine here? Is there something I'm missing as to what need that project serves?

**Comment by AraHaan** [comment]
What is wrong with providing a version of the xaml that is dark on it and have a mode switcher that sets the style of the control based on a property (like "IsDark")?

**Comment by benda** [comment]
Drawing a control to a series of images is not feasible and completely outside of all standard practice for a simple tree view.

**Comment by dgrunwald** [comment]
Does the standard WPF tree view do multiple selection?

Also we use:
 * drag'n'drop to reorder
 * potentially extremely deep nesting (esp. in the analyzer) -- afaik the WPF treeview crashes once you get to ca. 130 nesting levels

**Comment by benda** [comment]
Yes, the WPF tree view supports all of those requirements. I'm not aware of any issues with deep nesting - do you have a source for that? I've used it extensively on other projects without issues, including multiple selection and drag and drop.

**Comment by dgrunwald** [comment]
I remember running into this problem a long time back (not sure if .NET 4.0 or even earlier). Maybe it's fixed by now.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e64aba77-aeb5-4980-bf37-a37018865b6e/layout-recursion-reached-allowed-limit-to-avoid-stack-overflow-255?forum=wpf
If I remember correctly, WPF TreeView was using 2 nested UIElements per tree level, so the overall limit on the tree nesting depth came out to around 120.
SharpTreeView was created mostly to work around that limitation, because we were trying to display a tree of stack traces (in a profiler) and that often was deep enough to trigger the exception.
With the ILSpy analyzer it's theoretically possible to keep expanding infinitely, so I kept using the control we already had.

The post indicates that .NET 4.0 increased the limit to 4096; so I guess it's not as pressing a problem anymore. Still, in the context of an infinite tree (as with the ILSpy analyzer), all it takes is for the user to keep pressing the right arrow key for a while, and eventually a WPF TreeView would cause an exception (and not in a place where it could be easily caught; so always bringing down the whole application)

**Comment by benda** [comment]
OK so how do you want to proceed? Rather than having all colors/brushes defined in XAML so they can be easily themed, there are a few defined in code in various places so that would all need to be refactored (turned into DPs and XAML lookless templates as much as possible). Maybe you don't need to move to the standard WPF treeview. Either way that's a bit more work than I have time for now. 

You can see my current state of things in my fork, there's a toggle for the theme in Options -> Display. Best to restart after changing it. I think it's a fair start, without the changes above it doesn't all match. If you think it's OK looking enough I can start a pull request and then can enhance over time.

**Comment by spherous** [comment]
still want dark mode please.

**Comment by OFWModz** [comment]
👍 +1

**Comment by MarcoRossignoli** [comment]
+1

**Comment by krissadah** [comment]
+

**Comment by siegfriedpammer** [comment]
As basic theming is now available in nightly builds, this issue is closed. Any further bugs or issues should be aggregated and documented at #2359. Thanks!
