### ISSUE TITLE
Generate valid C# when exporting to project

### ISSUE THREAD

**Issue by exyi** [icsharpcode/ILSpy#666]
When I try to export decompiled code as .csproj, It can't be easily viewed in VisualStudio, because there are lot's of invalid type names like `<>c__DisplayClass10_.<>9__0`. I understand It's quite hard to get all of these decompiled into proper construct, but you could at least replace `<` and `>` with something valid - underscore, or some crazy Unicode chars :).

**Comment by greenozon** [comment]
names like <>c__DisplayClass10_.<>9__0
these are ... compiler generated names...

some other decompilers are smart enough to elimitate it fullly!
eg - Telerik

**Comment by weltkante** [comment]
ILSpy can do this too, it just has never been updated to decompile code generated by VS 2015 (or Roslyn)

**Comment by exyi** [comment]
@greenozon: How to fix ILSpy? Install telerik's decompiler :D

**Comment by lextm** [comment]
@exyi, how to fix? Step in and contribute your efforts if you do think that's an easy task.

**Comment by greenozon** [comment]
@weltkante 
well, the code like 
 <>c__DisplayClass10_.<>9__0

was in ILSpy way much much before the VS2015, or even VS2013...
thats the autogenerate C# code that some other decompilers knows how to  totally de-compile ...

**Comment by weltkante** [comment]
@greenozon What's your point? You obviously don't know what you're talking about if you claim ILspy can't decompile pre-roslyn code.

I stand by my point, ilspy has the algorithms to decompile it, someone just needs to step in and update it for the code patterns roslyn generates. I've [done it myself](https://github.com/weltkante/ILSpy/commit/3cf6f8eb2d5a3a30c8999070d744ea67093747f7) for some cases I needed so I know it works. Just needs to add overloads at the right places which detect the new code patterns.

**Comment by greenozon** [comment]
OK, pardon me
once I'll have some bits  (not from 2015VS) we'll get back to this point

**Comment by weltkante** [comment]
@greenozon don't bother if you just want to prove a point, I'm sure you can find an example of code ILspy can't decompile if you search a bit, but that doesn't change anything about what I said. The algorithms are still in place and just need to have patterns added to cover any cases you might dig up. The patterns which are already there are enough to decompile most of the commonly found pre-roslyn code. If the OP found *"there are lot's of invalid type names"* then at this point in time the most likely reason is because ILspy hasn't been updated to deal with roslyn generated code.

Anyways, I don't feel like this discussion is going anywhere. I made my point for readers of the issue that the probable cause is most likely roslyn generated code and that it's possible to fix it. Unless there is something else I can contribute to the issue I'll probably have nothing more to comment on. I'm not gonna pick up arguments about proving something as I've left enough information for a reader to figure it out himself wether or not what I've stated is right.

**Comment by siegfriedpammer** [comment]
As one of the (former) core members of the ILSpy team I'd like to add one last bit to the discussion. Please keep in mind that:
a) ILSpy favors keeping "correct" code instead of "nice-looking" code. So patterns that are not explicitly detected and tested, will not be transformed. "Correct" does not mean "compilable", because the compiler(s) do a lot of magic, but rather "representing the IL as correctly as possible (with all the available information) in C#".
b) In some cases ILSpy cannot detect patterns, because it requires type information from other assemblies that could not be resolved. Please ensure that any referenced assemblies can be found.
c) If you find a bug, you are welcome to report and wait (as opposed to rants) until somebody fixes it; OR: It's opensource - do it yourself! ;-)

**Comment by dgrunwald** [comment]
The new decompiler engine (which just landed on master) will now escape invalid identifiers when saving a project to disk; so that the code can be recompiled.
Moreover, it adds support for various code patterns generated by the Roslyn (VS2015+) C# compiler.
