### ISSUE TITLE
Why do regular expressions require //?

### ISSUE THREAD

**Issue by miloush** [icsharpcode/ILSpy#717]
I have always custom-built ILSpy to get regular expression support, so including that feature was great news.

The only thing I don't understand is why slashes are required to denote regular expressions? There does not seem to be any compatibility issues lifting up that requirement (perhaps except the dot which does not cause existing results to get cut though).

The problem with slashes I have is that you need to _enclose_ the expression. If slash is necessary, couldn't only the opening one be required and the closing one optional?

**Comment by AraHaan** [comment]
opening / closing slashes is used by Operating systems to verify if some directory exists without adding humungous code. I did them in Visual Basic before from the 1998 version. Yes I know it is very old but I dont care.

I have large hate to the .Net framework because if I want to make something that cant be decompiled easily I would be SOL with it due to Red Gate's .Net Reflector and of course ILSpy.

Not to mention that [petite](http://www.un4seen.com/petite) does not suppport the .Net Framework or even 64-bit compiled assemblies. They do however plan to support it in the future. >.>
