### ISSUE TITLE
Why sometimes use Cecil types and sometims use NRefactory TypeSystem?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#853]
The parameter "reference" in ITextOutput.WriteReference and "definition" in ITextOutput.WriteDefinition,
sometimes they are MethodDefinition/TypeDefition..., sometimes the are DefaultResolvedMethod/DefaultResolvedTypeDefinition

So, how can I know which one is right?

**Comment by dgrunwald** [comment]
We switched over the C# decompiler to the NR type system, but we don't want to rewrite everything else (IL disassembler, ILSpy tree view, search, analyser, ...). So we've intentionally kept using Cecil for C#'s ITextOutput.
But looks like we've forgotten a spot (WriteIdentifier/GetCurrentDefinition) and some NR types slip through...

**Comment by CreateAndInject** [comment]
Any plan to change all the parameters of ITextOutput to cecil types or change all to NR types?

**Comment by dgrunwald** [comment]
Not sure. For the "go to definition" logic we need cecil types at the moment.

On the other hand, our NR->conversion only works on type definitions, so we lose type arguments which we need for the tooltips.

WriteDefinition/WriteReference was originally meant for the highlighting when clicking a local variable (which highlight the other usages of the variable). That only requires GetHashCode()/Equals(), hence the `object` type.
What are you trying to use this information for?

Also, long-term I'm not sure if we want to keep maintaining the NR type system as C# 7 (tuples) and C# 8 (non-nullable references) make some major changes in that area. Maybe we should migrate to the Roslyn type system instead... although that would almost certainly mean forking Roslyn, as we'd need access to the internals (e.g. directly interacting with the overload resolution algorithm, before we even have a SyntaxTree).

**Comment by CreateAndInject** [comment]
Because sometimes the decompiled code isn't perfect, so I write a PlainTextOutputEx derived from ITextOutput, I may change the output content, so I need this information.

**Comment by dgrunwald** [comment]
`ITextOutput` is meant to be the language-independent interface in ILSpy, so it's somewhat restricted in the amount of information it is carrying.

Wouldn't changes to the generated code be better done on the `SyntaxTree` instead of in the text stream? If you do need text-level changes, consider working at the `TokenWriter`-level instead. You could derive from `TextTokenWriter` (or `TextWriterTokenWriter` if you don't need `ITextOutput`); or wrap it using a `DecoratingTokenWriter`. You can access the syntax tree (via StartNode/EndNode), and the associated semantics (via the ResolveResult and ILInstruction annotations).

And if there's a problem with the decompiler, feel free to report a bug or submit a fix instead of adding a workaround in post-processing.

**Comment by CreateAndInject** [comment]
If I want to rename a Variable/Field/Method, how should I do?
I try this:
    public override void StartNode(AstNode node)
    {
        if(node is VariableInitializer)
        {
            var vi = node as VariableInitializer;
            if (vi.Name == "oldName")
                vi.Name = "newName";
        }
    }

But it only rename the definition, all reference keep the old name.

**Comment by dgrunwald** [comment]
Hmm, for renaming there's indeed quite a few different cases to consider in the syntax tree:
* `VariableInitializer` -- used for fields and most local variables (definitions only)
* `EntityDeclaration` -- for method and property definitions
* `IdentifierExpression` -- used for references to variables
* `MemberReferenceExpression` -- used for field and method references
* `ForeachStatement` -- for the foreach variable
and I'm probably forgetting some special cases.

What the `TextTokenWriter` does is that it maintains a `Stack<AstNode> nodeStack` (via StartNode/EndNode), and thus can discover the parent node for any identifier being written.
But there too are various special cases for how to discover the correct node that holds the reference to the target symbol.

For now, I guess I'll change the `TextTokenWriter` to consistently use cecil references for non-local definitions and references. Local variables will keep using `ILVariable`.

**Comment by dgrunwald** [comment]
Strange, github closed this issue when I pushed my commit, but didn't link to the commit: c2898905c84e117b0a8db6c6216d895aee53ea4e

**Comment by CreateAndInject** [comment]
How to remove a AstNode?
such as:
string str="test";
I want to delete this line:
    public override void StartNode(AstNode node)
    {
        if (node is VariableDeclarationStatement)
            node.Remove();
        base.StartNode(node);
    }
But it failed.

**Comment by siegfriedpammer** [comment]
Removing the node in StartNode will lead to imbalanced stacks and some problem further down. You could try removing the node at the end of EndNode.

**Comment by CreateAndInject** [comment]
When EndNode is called, the content has already write to output, so it can not delete this line:
string str="test";

**Comment by dgrunwald** [comment]
If you want to modify the syntax tree, just do so before you start the `OutputVisitor`.
Typically you'll want to use something like: `foreach (var varDecl in syntaxTree.Descendants.OfType<VariableDeclarationStatement>()) ...`

Inheriting from `TokenWriter` is useful when you want to customize how the syntax tree is converted into text; it's not a good place to modify the syntax tree.

To get a better understanding of the syntax tree, you can use the demo application in the [NRefactory](https://github.com/icsharpcode/NRefactory) repository.

**Comment by CreateAndInject** [comment]
foreach (var varDecl in syntaxTree.Descendants.OfType<VariableDeclarationStatement>())
   varDecl.Name="_"+varDecl.Name;

This code will rename all the variable definitions, but all the variable references keep original.

By the way, whatever I rename ILVariable.Name or IdentifierExpression/Identifier, the references don't rename at one time. that's because ILSpy don't wirte ILVariable.Name, it writes IdentifierExpression/Identifier, but all the IdentifierExpression/Identifier are different objects, even if it is the same ILVariable in fact.

**Comment by siegfriedpammer** [comment]
If you want to rename variables, doing so in the C# AST is almost certainly the wrong place. I would suggest adding your own `IILTransform`, please see our implementation of `AssignVariableNames` in https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/IL/Transforms/AssignVariableNames.cs.

You would have to add your transform after our `AssignVariableNames` transform, by calling:
`csharpDecompiler.ILTransforms.Add(new MyRenameVariablesTransform())` before decompiling.

There you can easily rename variables, as shown in our implementation. If you have any more questions, please do hesitate to ask. You should probably open a new issue for future questions.

I am curious: What are you trying to accomplish in the end? Is there some bug you are trying to work around or some feature you want to implement? If you could open an issue with your specific problem and the solution you have in mind, we might be able to help you better, instead of just trial and error.
