### ISSUE TITLE
Failure to decompile for loop with conditional early return

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#861]
```cs
class ForLoopTest
{
    struct Data
    {
        public bool Condition;

        public Data(bool c)
        {
            Condition = c;
        }
    }

    bool Test()
    {
        for (int i = 0; i < 2; i++)
        {
            Data d = new Data(true);

            if (d.Condition)
                return d.Condition;
        }

        return true;
    }
}
```
Produces this:
```cs
internal class ForLoopTest
{
	private struct Data
	{
		public bool Condition;

		public Data(bool c)
		{
			this.Condition = c;
		}
	}

	private bool Test()
	{
		int i = 0;
		Data d;
		while (true)
		{
			if (i < 2)
			{
				d = new Data(true);
				if (!d.Condition)
				{
					i++;
					continue;
				}
				break;
			}
			return true;
		}
		return d.Condition;
	}
}
```

**Comment by dgrunwald** [comment]
What's happening here is that loop detection will pick a "preferred loop exit point" very early in the decompilation pipeline. In this case, the loop doesn't have an obvious exit point because all code reachable from the loop is also dominated by the loop. In this case we currently use a simple heuristic that tried to move as much code as possible out of the loop, thus preferring the more-complex return statement.
This means it ends up picking "return d.Condition;" as loop exit point (thus putting that statement outside the loop, and the other return statement within).

Once that decision's been done, there's no way to recover `i < 2` as loop condition, as the `i >= 2` case doesn't lead to the already-picked loop exit point.

A simple way of fixing this might be to tweak the heuristics to pick a better exit point. The C# compiler tends to generate IL code in source order, so simply picking the last of the possible exit points might work well.
Another approach could be to initially only include the natural loop within the loop container, then perform the usual block transforms (building up if-else-structures etc.), and only later pick the single loop exit point.

**Comment by mmusu3** [comment]
Hi, thanks for addressing this issue. However, I have found another test case similar to the first that is still decompiled incorrectly.
```cs
class Item { }

void Test2(int[] ids)
{
    for (int i = 0; i < ids.Length; i++)
    {
        Item item;
        TryGetItem(ids[i], out item);

        if (item == null)
            return;
    }
}

void TryGetItem(int id, out Item item) => item = null;
```
Produces:
```cs
private class Item
{
}

private void Test2(int[] ids)
{
	int i = 0;
	while (i < ids.Length)
	{
		Item item = default(Item);
		this.TryGetItem(ids[i], out item);
		if (item != null)
		{
			i++;
			continue;
		}
		break;
	}
}

private void TryGetItem(int id, out Item item)
{
	item = null;
}
```

**Comment by dgrunwald** [comment]
Your new test case is different: the exit point is obvious with `break;` and `return;` being equivalent; here the problem is merely that the if-condition is inverted. I think the best solution might be to just make the for-loop-pattern slightly more flexible.

**Comment by dgrunwald** [comment]
@mmusu3 I cannot reproduce the problem with `Test2`.
Which compiler was that code built with? I don't remember fixing anything like this...

**Comment by mmusu3** [comment]
I can still reproduce the issue as of 7af15d27cddcd6c4ff8ab8db48d8f0bb4fee7689. I am using VS 15.4 c# 7 in release mode.
