### ISSUE TITLE
Can't navigate to method when clicking a event handler.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#912]
private static void Main()
{
    Console.CancelKeyPress += new ConsoleCancelEventHandler(**DoCancelKeyPress**);// click DoCancelKeyPress
}

static void DoCancelKeyPress(object sender, ConsoleCancelEventArgs e)
{
    throw new NotImplementedException();
}

by the way, the lastest version will remove "new ConsoleCancelEventHandler(", is there any way to control whether remove or not in DecompilationOptions/DecompilerSettings？

**Comment by dgrunwald** [comment]
Yeah, we'll need to figure out a way to represent which overload is chosen here.
We need the `MethodGroupResolveResult` because the expression alone isn't choosing an overload, only the implicit conversion to `ConsoleCancelEventHandler` is. But in the current design, there's no good place to store the ResolveResult associated with the conversion.

**Comment by CreateAndInject** [comment]
v3.0.0.2897 decompile it like this:
Console.CancelKeyPress += **new ConsoleCancelEventHandler(**DoCancelKeyPress**)**;
and the lastest decompile it like this:
Console.CancelKeyPress += DoCancelKeyPress;

is there any way to control whether remove or not in DecompilationOptions/DecompilerSettings？

**Comment by dgrunwald** [comment]
I've added `DecompilerSettings.UseImplicitMethodGroupConversion` to control this behavior.

**Comment by siegfriedpammer** [comment]
This was fixed in e4b15256ababf09b6bcf18fd04705de5aef7d771
