### ISSUE TITLE
Missing explicit casts for implicit operators

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#926]
Explicit casts that use implicit operators aren't decompiled correctly.
The output doesn't compile because C1 does not contain a member called Name.

Source:
```cs
class C1
{
    public static implicit operator Type(C1 c) => c.GetType();
}

void Test()
{
    var c = new C1();
    var name = ((Type)c).Name;
}
```
Output:
```cs
private class C1
{
    public static implicit operator Type(C1 c)
    {
        return c.GetType();
    }
}

private void Test()
{
    string _ = new C1().Name;
}
```

**Comment by tamlin-mike** [comment]
I was bitten by the same issue, though in my case the destination type of the assign was an `object` field, making it pure agony to try to hunt the bug down.

As a workaround, until the core issue is fixed, could a decompiler option to explicitly include casts help, whether they seems to be required or not? Yes, it would likely produce quite ugly decompiled code, but hopefully it would resolve any and all issues of this kind until the core problem has been fully analyzed and solved.

**Comment by dgrunwald** [comment]
The problem here is that user-defined operators are handled in a post-processing step (ReplaceMethodCallsWithOperators), after the cast-inserting logic is already done. I think we'll need to handle op_Implicit calls directly within the ExpressionBuilder, probably in a manner similar to boxing conversions.

**Comment by tamlin-mike** [comment]
That sounds reasonable, even more so since this op_Implicit was to manually box an object to a more serialization-friendly type. :-)

Yes, earlier seems more appropriate, since it also indeed changes the type of the expression, and could in some obscure case even require multiple consecutive (op_Implicit) casts. Should be fairly straight-forward to create a tiny repro + regression test for it too (once fixed).

**Comment by tamlin-mike** [comment]
@dgrunwald  Excellent, works like a charm! Thank you so much!
