### ISSUE TITLE
Port to Xamarin.Forms

### ISSUE THREAD

**Issue by robertsundstrom** [icsharpcode/ILSpy#942]
In order for ILSpy to run on Mac and Linux (become x-plat), port UI to Xamarin.Forms.

**Comment by christophwille** [comment]
The main issue with switching away from WPF is AvalonEdit for displaying decompiled source, navigation from symbol to source et cetera. We had prototypes already (eg https://github.com/mkrueger/ILSpy/tree/xwt), but it is simply too much work for us.

Current focus is on making it possible to create xplat UIs - netstandard2.0 was our work item this regard, and now we try to get #931 off the ground plus hope someone would want to join in making #941 a reality (I personally think VSCode is the best way forward for xplat UIs because it has all the necessary infrastructure, especially editor-wise)

**Comment by jeremymeng** [comment]
Has anyone looked at http://avaloniaui.net/?

**Comment by siegfriedpammer** [comment]
I tried Avalonia a few weeks ago, but it is still very unstable and missing a lot of components, e.g. a TreeView. I don't see ILSpy running on non-Windows platforms any time soon.

**Comment by christophwille** [comment]
At the moment (never say never, though), switching from WPF to anything else isn't even remotely going to make it to our backlog. That's why I am closing the issue - but not adding a "Won't fix" label, because contributions are welcome.
