### ISSUE TITLE
How? Symbols & Source for the Decompiler Nuget Package

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#943]
Taking a private discussion between @siegfriedpammer and myself to the public forum.

What is today's suggested / accepted way of publishing pdb / source? symbolsource.org seems pretty much dead, and many modern environs expect debug symbols alongside the original dlls.

Links from the discussion:

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages
https://github.com/dotnet/roslyn/issues/3
https://github.com/ctaggart/SourceLink

What does everyone use / do these days?

Edit: via SourceLink (end of readme.md) I saw this uservoice item https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/19107733-debugger-should-support-c-compiler-embed-optio with an answer dated Oct 20th (so very recent)

Edit 2: apparently others are discussing too https://github.com/npgsql/npgsql/issues/1479

**Comment by m0sa** [comment]
`<DebugType>embedded</DebugType>` is the new hotness - bakes the portable pdb info into the dll. Needs .NET 4.7.1 or .2 IIRC to show stack traces, though.

**Comment by KirillOsenkov** [comment]
Yup, embedding the pdb into the dll is now supported. Also use SourceLink to map to the sources on Github. Also consider Nerdbank.GitVersioning to bake the Git Sha into the dlls.

**Comment by siegfriedpammer** [comment]
Tracking dotnet/roslyn#19127 ... are there any other issues that still need to be fixed before this works out of the box in VS?

**Comment by siegfriedpammer** [comment]
Just added the necessary fixes to our nuget pack process, to support the new source embedding into pdb.

We now push nightly nupkgs to https://ci.appveyor.com/nuget/ilspy-masterfeed, which you can simply add to your package sources in VS.

Step by step walkthrough:
Important: This requires Visual Studio 2017 15.5 preview2 or later.

1) Add our package source in VS:
![grafik](https://user-images.githubusercontent.com/344204/32095332-116d3478-bb03-11e7-98db-f3060f1c5845.png)

2) Open up manage packages, switch to the newly created package source and enable `Include prerelease` and install the package.
![grafik](https://user-images.githubusercontent.com/344204/32095444-7fcf0f9a-bb03-11e7-9ea3-a1b62836ac90.png)

3) Disable `Just My Code` in Debugging settings, this is necessary because we are publishing dlls built in release mode.
![grafik](https://user-images.githubusercontent.com/344204/32095522-bb8321b6-bb03-11e7-8e7d-1e0bee22fb6a.png)

4) Just step into the decompiler source code anytime you need:
![grafik](https://user-images.githubusercontent.com/344204/32095733-68143cda-bb04-11e7-9ca0-fff80bbb6e2b.png)

If you want to add the same to your project, follow these links and add the required bits:
* Add `IncludeSymbolsInPackage`: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj#L27
* Use `DebugType: portable`, otherwise  source embedding is not supported: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj#L33
* Currently MSBuild does not yet support `EmbedSources` as a property, this enable the following workaround: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj#L593

Now MSBuild should pass the correct flags to `csc` and invoke `nuget pack` properly.

**Comment by diverdan92** [comment]
The NuGet team is also looking into make this experience better. Feel free to join the discussion there: https://github.com/NuGet/Home/issues/6104

**Comment by christophwille** [comment]
Milestone 3.0 intentionally removed - it is implemented, but via workarounds. We will keep this issue open to keep tracking the related issues. Will close once we can remove the workarounds.

**Comment by christophwille** [comment]
Also see https://github.com/NuGet/NuGet.Client/pull/1971
