### ISSUE TITLE
Make it possible to decompile a list of assemblies to a solution

### ISSUE THREAD

**Issue by erik-kallen** [icsharpcode/ILSpy#972]
Thanks for a fantastic tool!

It would be even greater if it were possible to decompile a set of assemblies to a solution file with all references to the included projects replaced with real `<ProjectReference>` elements in the .csproj.

I might have the time to do this  myself, but in that case I would appreciate some hints about where to start.

**Comment by dgrunwald** [comment]
The class `WholeProjectDecompiler` is currently doing the project decompilation.

Decompiling a whole solution would require specifying a list of input modules, and modifying the WholeProjectDecompiler to emit project references.

But I'm not sure how the UI would look like. Offer `.sln` instead of (in addition to?) `.csproj` when multiple assemblies are selected? Or a whole new main menu command?
The "Save to disk" logic when multiple nodes are selected is currently unsuitable for such a task...

**Comment by siegfriedpammer** [comment]
It would probably be a good idea to integrate this feature into the Console (`ICSharpCode.Decompiler.Console`).

**Comment by erik-kallen** [comment]
Having the feature as a command-line tool would be good enough for me

**Comment by guibirow** [comment]
Other day I had to decompile a list of packages dependent on each other, around 10 csproj, and I had a bit of work to do one by and reference each other to build a solution.

A feature like this would be awesome,

I see two possible approaches:

1 - Do the process in two stages, First select multiple packages in the list and 'Save' would request a folder to save and create a project to each one using the same dll name without changing much the existing funcitonality, would be just loop passing each package to a save command, then an improvement later could create the link to the references(if any) to build the solution

2 - Select one package and click 'Generate' will prompt to select a list of referenced packages, this will build the chain of dependencies. Maybe a treeview to show the nested dependecies as well.
