### ISSUE TITLE
Unknown result type (might be due to invalid IL)

### ISSUE THREAD

**Issue by bprg** [icsharpcode/ILSpy#980]
![s](https://user-images.githubusercontent.com/706507/32965383-277a2008-cb8b-11e7-9f73-ef7d3a2cd8f9.png)

[Functional.Maybe.zip](https://github.com/icsharpcode/ILSpy/files/1483563/Functional.Maybe.zip)

**Comment by dgrunwald** [comment]
The warnings about unknown result types is solved with #1085.

But the lambdas still don't decompile correctly, because `Func` is still an unknown type, and the whole lambda decompilation process doesn't work if we don't have the delegate type definition available.
The problem seems to be that we resolve `mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes` to the .NET 2.0 corelib, which does not contain `System.Func`.

The assembly is compiled against `[TargetFramework(".NETPortable,Version=v4.0,Profile=Profile5")]`, which means a portable class library in the `.NET Framework 4 + Windows 8` profile.
The reference assembly are in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.0\Profile\Profile5`. mscorlib.dll there has version number 2.0.5.0 (despite being a .NET 4.0 assembly!) and contains `System.Func` etc.

I guess we should resolve the portable class libraries assemblies to the .NET 4.x GAC instead of the .NET 2.0 GAC.

**Comment by dgrunwald** [comment]
@siegfriedpammer fixed the assembly lookup problem in cc62002864b0f9e7bd1347d3641c9704c919fde1 and I just fixed another small problem with lambdas in generic functions.
`MaybeConvertions` should now decompile correctly.
